Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-09, with the labels that each got.

#781 Minor map fixes.
  html/changelogs/changelog flaksim 31 august.yml.txt
  maps/first_contact/maps/Exoplanet Research/ExoResearch_0.dmm
  maps/first_contact/maps/UNSC_Bertels/Heavycorvette.dmi
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/areas.dm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/UNSC_Bertels/outfits.dm
  maps/first_contact/maps/UNSC_Bertels/overmap.dm
  maps/first_contact/maps/kig_yar_pirates/Corvette2.dmi
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/odst_training/maps/Exoplanet Research/ExoResearch_0.dmm
  maps/odst_training/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/odst_training/maps/UNSC_Bertels/Heavycorvette.dmi
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/odst_training/maps/UNSC_Bertels/areas.dm
  maps/odst_training/maps/UNSC_Bertels/jobs.dm
  maps/odst_training/maps/UNSC_Bertels/outfits.dm
  maps/odst_training/maps/UNSC_Bertels/overmap.dm
Labels: enhancement/QOL, mapping

#785 Various QoL Additions
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/misc/armourspecials.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  html/changelogs/Ingredients-8-20-2018.yml
  html/changelogs/cael_cov_14-8.yml
  html/changelogs/cael_cov_14.8.yml
Labels: enhancement/QOL

#787 minor outfit and map tweaks.
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/halo/power/reactor.dm
  code/modules/halo/weapons/melee.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/areas.dm
  maps/first_contact/maps/UNSC_Bertels/outfits.dm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/odst_training/maps/UNSC_Bertels/areas.dm
  maps/odst_training/maps/UNSC_Bertels/outfits.dm
  maps/overmap_ships/CCV_Comet.dmm
Labels: enhancement/QOL, mapping

#793 More QoL Changes
  code/modules/halo/flood/flood_bio.dmi
  code/modules/halo/flood/flood_spawn_bio.dm
  code/modules/halo/misc/admin_start_flood_attack.dm
  code/modules/halo/overmap/overmap_projectiles/flood_projectiles.dm
  code/modules/halo/vehicles/mongoose.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: bug, enhancement/QOL

#802 Flood Forms and more!
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_bio.dmi
  code/modules/halo/flood/flood_bio_large.dmi
  code/modules/halo/flood/flood_combat_major.dmi
  code/modules/halo/flood/flood_combat_minor.dmi
  code/modules/halo/flood/floodjuggernaut.dmi
  code/modules/halo/icons/overmap/big civ ships.dmi
  html/changelogs/BDpuffy420- Flood.yml
Labels: enhancement/QOL, feature, spriting

#798 Various mostly Covenant changes
  baystation12.dme
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job/job.dm
  code/modules/clothing/clothing.dm
  code/modules/halo/covenant/chair.dm
  code/modules/halo/covenant/chair.dmi
  code/modules/halo/covenant/lekgolo_spawner.dm
  code/modules/halo/covenant/lekgolo_tank.dmi
  code/modules/halo/covenant/prophet.dm
  code/modules/halo/jobs/UNSC_ship/_defines.dm
  code/modules/halo/splashworks/covenant.png
  code/modules/halo/turfs/covenant/floor.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/procs/announce.dm
  code/world.dm
  html/changelogs/cael_cov_9.9.yml
  maps/first_contact/maps/kig_yar_pirates/areas.dm
  maps/~mapsystem/maps_jobs.dm
  test/check-paths.sh
Labels: bug, enhancement/QOL

#804 Hotfixes.
  baystation12.dme
  code/game/machinery/vending.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/vehicles/pelican.dm
  html/changelogs/changelog flaksim 11 september.yml
  icons/mob/head.dmi
  icons/mob/suit.dmi
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_1.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
Labels: bug, enhancement/QOL

#809 SDV Class Corvette.
  code/modules/hydroponics/seed_storage.dm
  html/changelogs/changelog flaksim 14 september.yml
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Covenant Corvette/Corvette2.dmi
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/areas.dm
  maps/first_contact/maps/Covenant Corvette/backup/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/includes.dm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/Covenant Corvette/outfits.dm
  maps/first_contact/maps/Covenant Corvette/overmap.dm
  maps/first_contact/maps/Covenant Corvette/ship implementation documentation.dm
  maps/first_contact/maps/Covenant Corvette/spawns_jobs.dm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/areas.dm
  maps/first_contact/maps/UNSC_Bertels/backup/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/overmap.dm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/overall_jobdefs.dm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/odst_training/maps/UNSC_Bertels/areas.dm
  maps/odst_training/maps/UNSC_Bertels/overmap.dm
Labels: enhancement/QOL, mapping

#811 Fixes marine armor.
  baystation12.dme
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/areas.dm
  maps/insurrection/mapdef.dm
  maps/odst_training/maps/Exoplanet Research/ExoResearch_2.dmm
Labels: enhancement/QOL

#818 Fixes Geminus mode.
  baystation12.dme
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/overall_outfits.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate_innies_geminus.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
Labels: enhancement/QOL

#820 Covenant arc work
  baystation12.dme
  code/controllers/configuration.dm
  code/game/antagonist/_antagonist_setup.dm
  code/game/jobs/job_controller.dm
  code/modules/clothing/underwear/base.dm
  code/modules/halo/NPC/npc_buysell.dm
  code/modules/halo/NPC/npc_interact.dm
  code/modules/halo/NPC/npc_trade.dm
  code/modules/halo/clothing/special_armour.dm
  code/modules/halo/covenant/grav128.dmi
  code/modules/halo/covenant/grav64.dmi
  code/modules/halo/covenant/pillar_lift.dm
  code/modules/halo/covenant/repulsor.dmi
  code/modules/halo/covenant/repulsor_engine.dm
  code/modules/halo/icons/species/Sangheili_Bodysuit.dmi
  code/modules/halo/icons/species/Sangheili_Combat_Harness.dmi
  code/modules/halo/icons/species/r_elite.dmi
  code/modules/halo/lobby_music/Covenant Dance.ogg
  code/modules/halo/lobby_music/covenant_music.dm
  code/modules/halo/lobby_music/halo_music.dm
  code/modules/halo/lobby_music/odst_music.dm
  code/modules/halo/overmap/fusion_thruster.dm
  code/modules/halo/overmap/fusion_thruster.dmi
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species_items/grunt_outfits.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/kig-yar_outfits.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/new_player/new_player.dm
  code/world.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/BDpuffy420- Flood.yml
  html/changelogs/Ingredients - 8.22.2018.yml
  html/changelogs/cael_cov_9.9.yml
  html/changelogs/changelog flaksim 10 september.yml
  html/changelogs/changelog flaksim 11 september.yml
  html/changelogs/changelog flaksim 14 september.yml
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/kig_yar_pirates/spawns_jobs.dm
  maps/slayer/slayer.dm
  nano/templates/npc.tmpl
Labels: enhancement/QOL, feature

#830 Misc Covenant work
  baystation12.dme
  code/_onclick/hud/screen_objects.dm
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job_controller.dm
  code/game/jobs/whitelist.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/banjob.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/halo/clothing/grunt_leg_armor.dmi
  code/modules/halo/clothing/mob_spartanhelm.dmi
  code/modules/halo/clothing/mob_spartansuit.dmi
  code/modules/halo/clothing/spartan.dm
  code/modules/halo/clothing/spartan.dmi
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/spartan_armour_variants.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/clothing/spartan_gear.dmi
  code/modules/halo/clothing/special_armour.dm
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/covenant/grav128.dmi
  code/modules/halo/covenant/medmachines.dm
  code/modules/halo/covenant/medmachines.dmi
  code/modules/halo/covenant/repulsor_engine.dm
  code/modules/halo/covenant/spirit.dm
  code/modules/halo/icons/species/grunt_gear.dmi
  code/modules/halo/icons/species/r_Augmented_Human.dmi
  code/modules/halo/misc/armourspecials.dm
  code/modules/halo/misc/armourspecials/armourspecials.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/misc/armourspecials/dispenseitems.dm
  code/modules/halo/misc/armourspecials/gear.dm
  code/modules/halo/misc/armourspecials/gear_defs.dm
  code/modules/halo/misc/armourspecials/shieldmonitor.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/misc/armourspecials/thrusters.dm
  code/modules/halo/misc/faction_whitelist.dm
  code/modules/halo/overmap/fusion_thruster.dm
  code/modules/halo/overmap/fusion_thruster.dmi
  code/modules/halo/overmap/slipspace_gen.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/spartan.dm
  code/modules/halo/structures/diesel_gen.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/stripping.dm
  code/modules/mob/new_player/new_player.dm
  html/changelog.html
  maps/first_contact/maps/Asteroid Listening Post/spawns_jobs.dm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/kig_yar_pirates/spawns_jobs.dm
  maps/slayer/slayer_outfits.dm
Labels: bug, enhancement/QOL, feature, spriting

#837 Fixes several lights and wiring on all bertels variants.
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
Labels: enhancement/QOL, mapping

#838 allows MAC designator linking.
  code/modules/halo/machinery/MAC.dm
Labels: enhancement/QOL
