Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-06, with the labels that each got.

#628 Roles and airlocks update.
  code/modules/food/replicator.dm
  maps/Asteroid Listening Post/Asteroid2.dmm
  maps/Exoplanet Icy/KS7535_2.dmm
  maps/Exoplanet Mining/PYK248.dmm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/spawns_jobs.dm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/corvette_spawns.dm
  maps/first_contact/overall_jobdefs.dm
  maps/first_contact/overall_outfits.dm
Labels: enhancement/QOL, feature, mapping

#630 Research acces fixes, corvette QA pass.
  maps/Asteroid Listening Post/Asteroid2.dmm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
Labels: bug, enhancement/QOL, mapping

#618 Covenant species additions and equipment changes
  code/__defines/species_lists.dm
  code/game/jobs/whitelist.dm
  code/modules/halo/icons/species/Skirmishers.dmi
  code/modules/halo/icons/species/r_skirmisher_template.dmi
  code/modules/halo/icons/species/r_skirmishers.dmi
  code/modules/halo/icons/species/skirm_clothing.dmi
  code/modules/halo/icons/species/skirm_fullsprite.dmi
  code/modules/halo/species_items/kig-yar.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/species/outsider/grunts.dm
  code/modules/mob/living/carbon/human/species/outsider/kig-yar.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: enhancement/QOL, feature

#633 An Octoal... lot of changes.. tehe..
  baystation12.dme
  code/game/machinery/nuclear_bomb.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/armband.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  html/changelogs/octoal-lot-of-changes.yml
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
  maps/Exoplanet Research/includes.dm
  maps/Exoplanet Research/spawn_jobs.dm
Labels: enhancement/QOL, feature

#634 Add firelocks everywhere on the Corvette
  html/changelogs/blox-firelocks.yml
  maps/first_contact/maps/UNSC_Corvette.dmm
Labels: enhancement/QOL, mapping, oversight

#636 nanolaminate material upgrade
  code/modules/halo/turfs/covenant/materials.dm
  code/modules/halo/turfs/covenant/walls.dm
  html/changelogs/XO11 - nanolaminate buff.yml
Labels: bug, enhancement/QOL

#629 Colony mode expansion
  baystation12.dme
  code/game/gamemodes/extended/extended.dm
  code/modules/halo/icons/Hrunting.dmi
  code/modules/halo/icons/Plasma Cannon .dmi
  code/modules/halo/icons/Plasma Cannon 1.dmi
  code/modules/halo/icons/mecha_Hruntingyggdrasilincluded.dmi
  code/modules/halo/icons/overmap/Cruiser.dmi
  code/modules/halo/icons/overmap/big civ ships.dmi
  code/modules/halo/overmap/npc_ships.dm
  code/modules/halo/vehicles/finalwarthog-chaingun.dmi
  html/changelogs/BDpuffy420 - Colony Changes.yml
  maps/Exoplanet Mining/spawns_jobs.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/unsc_frigate_innies_geminus.dm
  maps/unsc_frigate/unsc_frigate_map.dm
Labels: enhancement/QOL, feature, overmap

#648 Modified M392 and Moderator Atmos Adjustment
  code/modules/admin/verbs/grief_fixers.dm
  code/modules/halo/machinery/ammo_fabricator.dm
  code/modules/halo/machinery/ammo_fabricator_datums.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/snipers.dm
  html/changelogs/inniegunstuff.yml
Labels: enhancement/QOL

#651 Remodel of Kig-Yar ship+Adding weapons to Frigate.
  html/changelogs/Flaksim Update 7 june - kopie.yml
  maps/Exoplanet Mining/spawns_jobs.dm
  maps/covenant_ships/kig_yar_pirates/backup/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
  maps/unsc_frigate/unsc_frigate_areas.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
Labels: enhancement/QOL, mapping

#653 "Hotfix" for vessel problems+ minor additions.
  code/modules/halo/species_items/sangheili.dm
  html/changelogs/Flaksim Update 8 june.yml
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/overall_overmap.dm
  maps/unsc_frigate/lifts.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
  maps/unsc_frigate/unsc_frigate.dm
  maps/unsc_frigate/unsc_frigate_areas.dm
Labels: bug, enhancement/QOL, mapping

#654 Bug fixes and kig-yar engine rework.
  html/changelogs/Flaksim Update 8 june 2.yml
  maps/Exoplanet Research/spawns_jobs.dm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/pirate.dmi
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/overall_jobdefs.dm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
Labels: bug, enhancement/QOL, mapping, overmap

#660 Report New Notes and Bans to Cicero
  code/controllers/configuration.dm
  code/modules/admin/player_notes.dm
Labels: enhancement/QOL, feature

#641 Mark V Spartan Armour and variants
  code/modules/halo/clothing/mob_spartanhelm.dmi
  code/modules/halo/clothing/mob_spartansuit.dmi
  code/modules/halo/clothing/spartan.dm
  code/modules/halo/clothing/spartan.dmi
  code/modules/halo/icons/species/Spartan_Armor__Female_Aug (1).dmi
  html/changelogs/mk5 armour.yml
Labels: enhancement/QOL

#661 ODST Nerf
  code/game/machinery/vending.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/structures/gunvendors.dm
  html/changelogs/ODST-Nerf.yml
Labels: enhancement/QOL

#655 Various changes to signal-transmission, Comms and otherwise.
  baystation12.dme
  code/controllers/communications.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/telecomms_jammers.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/machinery/telecomms_relays.dm
  maps/Asteroid Listening Post/Asteroid1.dmm
  maps/Asteroid Listening Post/Asteroid2.dmm
  maps/Exoplanet Icy/KS7535_1.dmm
  maps/Exoplanet Icy/KS7535_2.dmm
  maps/Exoplanet Mining/PYK248.dmm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/CCV_Slow_But_Steady.dmm
  maps/first_contact/maps/CCV_Star.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
Labels: enhancement/QOL, feature, mapping

#668 Update note report to indicate the ckey the note is set on
  code/modules/admin/player_notes.dm
Labels: enhancement/QOL

#671 Cut Content
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: mapping, oversight

#673 FC mode fixes.
  html/changelogs/Flaksim Update 12 june 2.yml
  maps/Asteroid Listening Post/Asteroid1.dmm
  maps/Asteroid Listening Post/Asteroid2.dmm
  maps/Exoplanet Mining/PYK248.dmm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/CCV_Slow_But_Steady.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/overall_jobdefs.dm
  maps/first_contact/overall_overmap.dm
  maps/first_contact/slowbutsteady.dmi
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate_areas.dm
  maps/unsc_frigate/unsc_frigate_overmap.dm
Labels: bug, enhancement/QOL

#677 Replaces gungnir sprites with maxattacker's sprites
  code/modules/halo/clothing/spartan.dm
  code/modules/halo/clothing/spartan.dmi
Labels: enhancement/QOL, oversight, spriting

#680 Fixes invisible npcs
  code/modules/halo/NPC/NPC_types/colonist.dm
Labels: bug

#681 Misc bugfixes
  code/_helpers/global_access.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/mob/living/carbon/human/species/outsider/grunts.dm
  maps/unsc_frigate/outfits/marines.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
  tools/GenerateGlobalVarAccess/gen_globals.py
Labels: bug

#685 vehicle self-loading and ghost-control fixes
  code/modules/halo/vehicles/vehiclebase.dm
Labels: bug

#684 Some tweaks and fixes to mining
  code/modules/mining/mine_turfs.dm
  html/changelogs/cael_mining1.yml
  icons/obj/mining.dmi
  icons/turf/walls.dmi
  maps/geminus_city/geminuscity_2.dmm
Labels: bug, enhancement/QOL, mapping

#694 Add startup time logging
  code/world.dm
Labels: enhancement/QOL

#695 Adds NPCs to the Geminus City Map
  code/modules/halo/NPC/NPC_types/colonist.dm
  code/modules/halo/NPC/NPC_types/crop_trader.dm
  code/modules/halo/NPC/NPC_types/mineral_trader.dm
  code/modules/halo/NPC/NPC_types/weapon_smuggler.dm
  html/changelogs/cael_npc2.yml
  maps/Exoplanet Mining/PYK248.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/geminuscity_4.dmm
  maps/insurrection/innie_base1.dmm
  maps/insurrection/innie_base2.dmm
  maps/insurrection/innie_base3.dmm
  maps/insurrection/innie_base4.dmm
Labels: feature, mapping

#699 Removes 2/3 of NPCs to reduce processing lag
  maps/Exoplanet Mining/PYK248.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/insurrection/innie_base2.dmm
  maps/insurrection/innie_base3.dmm
  maps/insurrection/innie_base4.dmm
Labels: bug, mapping
