Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-04, with the labels that each got.

#514 General Additions and Fixes
  code/game/machinery/vending.dm
  code/game/objects/random/random.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/odst_prowler/ODST_Ship.dmm
  maps/unsc_frigate/outfits/marines.dm
Labels: bug, enhancement/QOL, feature, mapping

#517 General Vehicle fixes + incorporating Nalar's comms fixes.
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/mob/living/say.dm
  html/changelogs/comms-fixes-XO-11&Nalar.yml
Labels: bug, enhancement/QOL

#520 fixes game-breaking vehicle bug
  code/modules/halo/vehicles/vehiclebase.dm
Labels: bug, enhancement/QOL

#522 Final gen fixes before OM project
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/interiorobjs.dm
  maps/odst_prowler/ODST_Ship.dmm
Labels: bug, enhancement/QOL, mapping

#524 NPC spaceships.
  baystation12.dme
  code/_helpers/global_access.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/overmap/freighter.dmi
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/overmap/npc_ships.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/overmap/ships/ship.dm
  maps/civ_hauler/civhauler.dmm
  test/run-test.sh
Labels: enhancement/QOL, feature, overmap

#527 Attachments and Sprite Updates
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/rifles.dm
  code/modules/projectiles/attachments/sights.dm
  code/modules/projectiles/projectile/bullets.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
Labels: enhancement/QOL, spriting

#531 Revert "More NPC ship work"
  baystation12.dme
  code/__defines/npc_comms_authority_levels.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/npc_comms.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_cargo_ship.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/overmap/npc_ships.dm
  code/modules/halo/overmap/umbilicals.dm
Labels: bug

#529 Fixes UNSC and colony new arrival announces.
  code/game/jobs/job/job.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/jobs/UNSC_ship/_defines.dm
  code/modules/mob/new_player/new_player.dm
  code/procs/announce.dm
  html/changelogs/announce-fix-nalar.yml
  maps/geminus_city/geminus_city_jobs.dm
  maps/insurrection/insurrection_jobs.dm
  maps/unsc_frigate/jobs/command.dm
  maps/unsc_frigate/jobs/marines.dm
  test/check-paths.sh
Labels: enhancement/QOL, feature

#532 Pistol In-hands
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/pistols.dm
Labels: enhancement/QOL, spriting

#534 More NPC ship work
  baystation12.dme
  code/__defines/npc_comms_authority_levels.dm
  code/game/jobs/job/job.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/jobs/UNSC_ship/_defines.dm
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/npc_comms.dm
  code/modules/halo/machinery/npc_comms.dmi
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_cargo_ship.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/overmap/npc_ships.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/rifles.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/attachments/sights.dm
  code/modules/projectiles/projectile/bullets.dm
  code/procs/announce.dm
  html/changelogs/announce-fix-nalar.yml
  maps/geminus_city/geminus_city_jobs.dm
  maps/insurrection/insurrection_jobs.dm
  maps/unsc_frigate/jobs/command.dm
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
  test/check-paths.sh
Labels: enhancement/QOL, feature

#535 small fix to NPC can_board logic
  code/modules/halo/overmap/npc_cargo_ship.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/overmap/npc_ships.dm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/civ_hauler/civhauler.dmm
  maps/civ_hauler/hauler_area.dm
  maps/unsc_frigate/unsc_frigate_base_includes.dm
Labels: bug, enhancement/QOL, feature

#538 Sprite update
  code/modules/halo/icons/banshee.dmi
  code/modules/halo/icons/species/Jiralhanae.dmi
  code/modules/halo/icons/species/Jiralhanae_Bodysuit.dmi
  code/modules/halo/icons/species/Jiralhanae_Captain_Armor.dmi
  code/modules/halo/icons/species/Jiralhanae_Major_Armor.dmi
  code/modules/halo/icons/species/Jiralhanae_Minor_Armor.dmi
  code/modules/halo/icons/species/Prophets.dmi
  code/modules/halo/turfs/covenant/covviedoor.dmi
  code/modules/halo/turfs/covenant/covviewalls.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
Labels: enhancement/QOL, spriting

#539 ship captain ghost role
  baystation12.dme
  code/game/gamemodes/extended/extended.dm
  code/modules/mob/observer/ghost/role_manager.dm
  maps/civ_hauler/civhauler.dmm
  maps/civ_hauler/ship_cap_ghost_role.dm
Labels: enhancement/QOL, feature, overmap

#540 New ODST Prowler map
  maps/odst_prowler/ODST_Ship.dmm
Labels: enhancement/QOL, feature, mapping

#543 Multiple Fixes
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/overmap/npc_cargo_ship.dm
  code/modules/halo/overmap/npc_ships.dm
  code/procs/announce.dm
  maps/civ_hauler/civhauler.dmm
  maps/odst_prowler/ODST_Ship.dmm
Labels: bug, enhancement/QOL, feature, mapping

#545 Adds a new admin verb
  baystation12.dme
  code/modules/halo/flood/flood_bio_med.dmi
  code/modules/halo/flood/flood_spawn_bio.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/misc/admin_start_flood_attack.dm
  code/modules/halo/misc/flood_inv_end.ogg
  code/modules/halo/misc/flood_inv_start.ogg
  code/modules/halo/overmap/overmap_projectiles/flood_overmap_proj.dmi
  code/modules/halo/overmap/overmap_projectiles/flood_projectiles.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/unsc_frigate/unsc_frigate_overmap.dm
Labels: enhancement/QOL, feature

#546 ODST Armor Update
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL, spriting

#547 Various vehicle fixes: Explosion handling, Occupant pull, Vehicles-as-cargo. Also implements spirit dropship
  baystation12.dme
  code/modules/halo/icons/Covenant_Projectiles.dmi
  code/modules/halo/sounds/spirit_firesound.ogg
  code/modules/halo/vehicles/spirit.dmi
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
Labels: bug, enhancement/QOL, feature

#554 Attachments
  code/modules/halo/structures/gunvendors.dm
  maps/unsc_frigate/unsc_frigate-3.dmm
Labels: enhancement/QOL, mapping

#555 Backpack slowdown.
  code/__defines/items_clothing.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/storage.dm
Labels: enhancement/QOL, feature

#556 Communication channel colours
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/comms/channel_keys.dm
  html/changelogs/comms-colours-first-nalar.yml
Labels: enhancement/QOL

#558 Minor mapping fixes
  html/changelogs/nalar-mapping-fixes-faxes.yml
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate_map.dm
Labels: bug, mapping, oversight

#559 Fixes announcements
  code/procs/announce.dm
  html/changelogs/announce-fix-nalar-1.yml
Labels: enhancement/QOL, feature

#552 Covenant Balancing and additions
  code/modules/halo/sounds/hunter_charge.ogg
  code/modules/halo/species_items/lekgolo.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/halo/weapons/covenant/melee.dm
  maps/slayer/death_asteroid.dmm
Labels: enhancement/QOL, feature

#561 Fixes medbay
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/mob_jumpsuit_ship.dmi
  code/modules/halo/clothing/mob_marine.dmi
  maps/odst_prowler/ODST_Ship.dmm
Labels: enhancement/QOL, mapping

#564 Marine Sprite updates+other minor fixes.
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/icons/objs/item_marine.dmi
  code/modules/halo/icons/objs/marine.dmi
  code/modules/halo/structures/ODST_Droppod.dmi
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
  maps/unsc_frigate/outfits/marines.dm
Labels: enhancement/QOL, spriting

#563 Various rebalances and fixes
  code/modules/halo/vehicles/pelican.dm
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/covenant/pistols.dm
Labels: enhancement/QOL

#568 Various comms tweaks & fixes
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/jobs/UNSC_ship/_defines.dm
  code/procs/announce.dm
  html/changelogs/comms-tweaks-1-nalar.yml
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/outfits/command.dm
  maps/unsc_frigate/outfits/marines.dm
  maps/unsc_frigate/unsc_frigate_overmap.dm
  maps/unsc_frigate/unsc_frigate_spawns.dm
  test/check-paths.sh
Labels: enhancement/QOL, feature, overmap, oversight

#569 Bullet wall damage tweaks
  code/game/turfs/simulated/walls.dm
  html/changelogs/wall-damage-tweak-nalar.yml
Labels: enhancement/QOL

#570 Money Update
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/economy/cash.dm
  maps/geminus_city/geminus_city_outfits.dm
Labels: enhancement/QOL

#573 Tiny Changes
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/insurrection/innie_base4.dmm
  maps/insurrection/insurrection_jobs.dm
  maps/unsc_frigate/jobs/command.dm
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
Labels: enhancement/QOL, mapping
