Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-07, with the labels that each got.

#716 potential drop pod fix
  code/modules/halo/vehicles/drop_pod.dm
Labels: bug, enhancement/QOL

#718 Fixes SOEIV pods on corvette.
  baystation12.dme
  maps/first_contact/maps/UNSC_Corvette.dmm
Labels: mapping, overmap

#710 Small ONI base fixes
  code/game/mecha/mecha_parts.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
Labels: enhancement/QOL

#723 Rename Tvaoans
  code/modules/halo/species_items/kig-yar.dm
  code/modules/mob/living/carbon/human/species/outsider/kig-yar.dm
Labels: enhancement/QOL

#726 Revert innie mode map and remove whitelist lock on innie leader
  maps/insurrection/insurrection.dm
  maps/insurrection/insurrection_jobs.dm
Labels: enhancement/QOL
