Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-02, with the labels that each got.

#436 Projectile internal phasing device removal
  code/datums/observation/moved.dm
  code/modules/halo/vehicles/pelican.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/projectile.dm
Labels: bug, oversight

#437 Squad Waypoints
  baystation12.dme
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/squads/hud_glasses.dmi
  code/modules/halo/squads/squad-waypoint-controller.dm
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/squads/waypoint_manager.dmi
  code/modules/halo/squads/waypoint_object.dm
  code/modules/halo/squads/waypoints.dmi
  code/modules/halo/weapons/snipers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/detective.dm
  maps/unsc_frigate/outfits/marines.dm
  test/check-paths.sh
Labels: enhancement/QOL, feature

#439 Geminus Hotfix
  code/datums/outfits/outfit.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/comms/commsitems.dm
  code/modules/halo/comms/headsets.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminus_city_outfits.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/unsc_frigate/unsc_frigate_overmap.dm
Labels: enhancement/QOL

#442 Desodone Hotfix6
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/smg.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminus_city_outfits.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/interiorobjs.dm
  maps/insurrection/ODST_staging.dmm
  maps/insurrection/innie_base1.dmm
  maps/insurrection/insurrection_jobs.dm
Labels: enhancement/QOL
