Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-10, with the labels that each got.

#844 Change log, added in more money for Oni. Created Vault for money to b…
  html/changelogs/IngredientsExo Research Change 9.30.2018.yml
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
Labels: enhancement/QOL, mapping

#848 Comms Jammer Toggling
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/telecomms_jammers.dm
Labels: enhancement/QOL, feature

#849 Makes flood infestor forms have the PASSTABLE flag
  code/modules/halo/flood/flood.dm
Labels: feature

#859 Various Vehicle Fixes
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: enhancement/QOL, feature

#860 Some flood work
  code/modules/halo/flood/flood.dm
Labels: bug

#862 Gives the Spirit Dropship some useful overmap and view range
  code/modules/halo/vehicles/spirit_dropship.dm
Labels: enhancement/QOL

#864 Makes plasma grenades reliable
  code/modules/halo/weapons/covenant/grenades.dm
Labels: enhancement/QOL, feature

#865 Fixes the covenant ship's cloaking device.
  maps/first_contact/maps/Covenant Corvette/overmap.dm
Labels: enhancement/QOL

#867 All weapons can Parry
  code/__defines/items_clothing.dm
  code/game/objects/weapons.dm
  code/modules/halo/weapons/covenant/melee.dm
  html/changelogs/XO-11 - OmniParry.yml
Labels: enhancement/QOL, feature

#868 Flood Update
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_carrier.dmi
  code/modules/halo/flood/flood_combat_depotguard.dmi
  code/modules/halo/flood/flood_combat_human.dmi
  code/modules/halo/flood/flood_combat_odst.dmi
  code/modules/halo/flood/flood_combat_oni.dmi
  code/modules/halo/flood/flood_infection.dmi
  code/modules/halo/flood/flood_spawn.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, feature

#870 Stranded fixes
  code/controllers/communications.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/icons/turfs/seafloor.dmi
  maps/desert_outpost/desert_outpost.dmm
  maps/desert_outpost/desert_outpost_map.dm
  maps/desert_outpost/gamemode/mode_stranded.dm
  maps/desert_outpost/gamemode/mode_stranded_attackers_spawn.dm
  maps/desert_outpost/gamemode/mode_stranded_start.dm
  maps/desert_outpost/turfs_areas.dm
Labels: bug, enhancement/QOL

#873 Small change to ensure parrying doesn't destroy guns too easily.
  code/__defines/items_clothing.dm
  code/game/objects/weapons.dm
Labels: enhancement/QOL

#872 Lowers stranded wave time to 5 mins
  maps/desert_outpost/gamemode/mode_stranded.dm
Labels: enhancement/QOL

#875 Minor map fixes.
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/areas.dm
  maps/first_contact/maps/UNSC_Prowler/UNSC_Prowler_Deck_1.dmm
Labels: enhancement/QOL, mapping

#877 Modifies Gear armour-special slot-checking.
  code/modules/halo/misc/armourspecials/gear.dm
Labels: enhancement/QOL, feature

#881 Map fixes and various additions
  html/changelogs/Delnth-alpha.yml
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/CCV_Deliverance.dmm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/Covenant Corvette/outfits.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: enhancement/QOL, mapping

#884 Admin Planet
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/Admin Planet/areas.dm
  maps/first_contact/maps/Admin Planet/includes.dm
  maps/first_contact/maps/Admin Planet/overmap.dm
  maps/first_contact/maps/Admin Planet/sector_icon.dmi
  maps/first_contact/maps/Admin Planet/surface.dmm
Labels: enhancement/QOL, feature, mapping

#887 FC Elite Ultra loadout fix + map fix
  maps/first_contact/maps/Admin Planet/surface.dmm
  maps/first_contact/maps/CCV_Deliverance.dmm
  maps/first_contact/maps/Covenant Corvette/outfits.dm
Labels: bug, enhancement/QOL, mapping

#888 OPR Comms fixes.
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/first_contact/maps/Covenant Corvette/overmap.dm
Labels: enhancement/QOL

#889 Payloads additions and kig-yar suit
  html/changelogs/erty80s 10.29.2018.yml
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
Labels: enhancement/QOL, feature
