Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-05, with the labels that each got.

#578 Sprite update
  code/modules/halo/icons/Marine_EVA.dmi
  code/modules/halo/icons/machinery/ODST_Weapon_Lock.dmi
  code/modules/halo/icons/machinery/covenant/Covie_Obj_Stuff.dmi
  code/modules/halo/icons/machinery/covenant/covviedoor.dmi
  code/modules/halo/icons/species/Sangheili.dmi
  code/modules/halo/icons/species/Skirmishers.dmi
  code/modules/halo/icons/species/Spartan_Armor__Female_Aug (1).dmi
  code/modules/halo/icons/turfs/MarineStuff.dmi
  code/modules/halo/icons/turfs/covviewalls.dmi
  code/modules/halo/icons/turfs/x.dmi
  code/modules/halo/shuttles/pelican.dmi
  code/modules/halo/vehicles/finalwarthog.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
Labels: enhancement/QOL, spriting

#580 More sprites
  code/modules/halo/icons/species/Prophets.dmi
  code/modules/halo/icons/species/SanShyuum.dmi
  code/modules/halo/vehicles/Scorpion.dmi
  code/modules/halo/vehicles/finalwarthog-turretless.dmi
Labels: enhancement/QOL, spriting

#579 First Contact Scenario
  baystation12.dme
  code/__defines/species_lists.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/objects/structures/window.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/icons/energy_dagger_inhand.dmi
  code/modules/halo/icons/machinery/covenant/doors.dmi
  code/modules/halo/icons/machinery/covenant/light.dmi
  code/modules/halo/icons/overmap/umbilical_covenant.dmi
  code/modules/halo/machinery/covenant/doors.dm
  code/modules/halo/machinery/covenant/lights.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/structures/covenant/window_icon.dmi
  code/modules/halo/structures/covenant/windows.dm
  code/modules/halo/structures/sofa.dm
  code/modules/halo/turfs/road_and_pavements.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/living/carbon/human/species/outsider/grunts.dm
  code/modules/mob/living/carbon/human/species/outsider/kig-yar.dm
  code/modules/mob/living/carbon/human/species/outsider/sangheili.dm
  code/modules/mob/new_player/new_player.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/areas.dm
  maps/Exoplanet Research/backup/ExoResearch_1.dmm
  maps/Exoplanet Research/backup/ExoResearch_2.dmm
  maps/Exoplanet Research/includes.dm
  maps/Exoplanet Research/overmap.dm
  maps/Exoplanet Research/sector_icon.dmi
  maps/Exoplanet Research/spawns_jobs.dm
  maps/covenant_ships/kig_yar_pirates/areas.dm
  maps/covenant_ships/kig_yar_pirates/backup/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/includes.dm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/overmap.dm
  maps/covenant_ships/kig_yar_pirates/pirate.dmi
  maps/covenant_ships/kig_yar_pirates/spawns_jobs.dm
  maps/first_contact/all_includes.dm
  maps/first_contact/corvette.dmi
  maps/first_contact/freighter.dmi
  maps/first_contact/mapdef.dm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/CCV_Slow_But_Steady.dmm
  maps/first_contact/maps/CCV_Star.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/ccv_star_spawns.dm
  maps/first_contact/maps/comet_spawns.dm
  maps/first_contact/maps/corvette_spawns.dm
  maps/first_contact/maps/sbs_spawns.dm
  maps/first_contact/overall_jobdefs.dm
  maps/first_contact/overall_outfits.dm
  maps/first_contact/overall_overmap.dm
  maps/geminus_city/citymapturfs.dm
  maps/geminus_city/interiorstructures.dm
  maps/unsc_frigate/outfits/command.dm
Labels: enhancement/QOL, feature, overmap

#581 First contact scenario fixes/changes
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
Labels: bug, feature

#582 Adds Warthog Chain-gun sprites
  code/modules/halo/vehicles/finalwarthog-chaingun.dmi
Labels: spriting

#583 First Contact Fixes
  code/game/periodic_news.dm
  code/modules/halo/machinery/npc_comms.dm
  code/modules/halo/overmap/npc_ships.dm
  code/modules/halo/shuttles/dropship.dm
  code/modules/halo/shuttles/dropship_landing_controller.dm
  code/modules/halo/shuttles/dropship_landing_points.dm
  code/modules/halo/shuttles/pelican.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/sector_icon.dmi
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/ccv_star_spawns.dm
  maps/first_contact/maps/sbs_spawns.dm
  maps/first_contact/overall_jobdefs.dm
  maps/first_contact/overall_outfits.dm
  maps/first_contact/overall_overmap.dm
  maps/insurrection/insurrection_items.dm
  maps/odst_prowler/ODST_Ship.dmm
  maps/odst_prowler/backup/ODST_Ship.dmm
  maps/odst_prowler/odst_ship_overmap.dm
  maps/unsc_frigate/backup/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
Labels: bug, enhancement/QOL, mapping

#590 Overmap ship weapons sprites
  code/modules/halo/icons/32x64.dmi
  code/modules/halo/icons/beamline64x32.dmi
  code/modules/halo/icons/lasers.dmi
  code/modules/halo/icons/missile.dmi
  code/modules/halo/icons/ship_battles.dmi
  code/modules/halo/icons/ship_battles_96x.dmi
  code/modules/halo/icons/species/Skirmisher_inhand.dmi
  code/modules/halo/icons/species/Skirmishers.dmi
  code/modules/halo/icons/supplybeacon.dmi
  code/modules/halo/icons/worlds.dmi
Labels: enhancement/QOL, spriting

#591 Deck Guns
  baystation12.dme
  code/game/turfs/simulated/walls.dm
  code/modules/halo/machinery/deck_chaingun.dmi
  code/modules/halo/machinery/deck_gun.dm
  code/modules/halo/machinery/deck_gun.dmi
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/sounds/deck_gun_fire.ogg
  code/modules/halo/turfs/covenant/materials.dm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/covenant_ships/kig_yar_pirates/overmap.dm
  maps/first_contact/overall_overmap.dm
  maps/overmap_ships/om_ship_areas.dm
Labels: feature

#589 First Contact tweaks.
  code/game/machinery/vending.dm
  code/modules/halo/chemicals/containers.dm
  maps/Exoplanet Icy/KS7535_1.dmm
  maps/Exoplanet Icy/KS7535_2.dmm
  maps/Exoplanet Icy/areas.dm
  maps/Exoplanet Icy/includes.dm
  maps/Exoplanet Icy/overmap.dm
  maps/Exoplanet Icy/sector_icon.dmi
  maps/Exoplanet Icy/spawns_jobs.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/overmap.dm
  maps/Exoplanet Research/spawns_jobs.dm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/spawns_jobs.dm
  maps/first_contact/all_includes.dm
  maps/first_contact/corvette.dmi
  maps/first_contact/mapdef.dm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/backup/UNSC_Corvette.dmm
  maps/first_contact/overall_jobdefs.dm
  maps/overmap_ships/UNSC_Corvette.dmm
  maps/overmap_ships/om_ship_areas.dm
Labels: enhancement/QOL, feature, mapping

#592 fixes based on test
  code/modules/halo/chemicals/containers.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/spawns_jobs.dm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/overall_jobdefs.dm
Labels: enhancement/QOL, mapping

#595 Assorted Fixes and features
  baystation12.dme
  code/game/sound.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/sounds/r_alert_alarm_loop.ogg
  code/modules/halo/sounds/r_alert_alarm_loop_j1.ogg
  code/modules/halo/sounds/r_alert_alarm_loop_j2.ogg
  code/modules/halo/sounds/r_alert_alarm_loop_j3.ogg
  code/modules/halo/structures/sandbag.dm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/spawns_jobs.dm
  maps/first_contact/overall_overmap.dm
Labels: enhancement/QOL

#604 Ship-V-Ship additions and other balancing
  baystation12.dme
  code/modules/halo/machinery/covie_pulse_turret.dm
  code/modules/halo/machinery/deck_gun.dm
  code/modules/halo/machinery/deck_missile_pod.dmi
  code/modules/halo/machinery/missile_pods.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/machinery/pulse_turret.dmi
  code/modules/halo/machinery/pulse_turret_tracers.dmi
  code/modules/halo/sounds/pulse_turret_fire.ogg
  code/modules/halo/sounds/rocket_pod_fire.ogg
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/handheld_shields.dm
  code/modules/halo/weapons/explosives.dm
  code/modules/overmap/sectors.dm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/covenant_ships/kig_yar_pirates/areas.dm
  maps/covenant_ships/kig_yar_pirates/kig_yar_pirates.dmm
  maps/covenant_ships/kig_yar_pirates/overmap.dm
  maps/covenant_ships/kig_yar_pirates/pirate.dmi
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/overall_overmap.dm
  maps/overmap_ships/om_ship_areas.dm
Labels: enhancement/QOL, feature

#610 umbilical object loading
  code/modules/halo/overmap/umbilicals.dm
Labels: enhancement/QOL, feature

#606 Map fixes.
  code/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/crates.dm
  maps/Asteroid Listening Post/Asteroid2.dmm
  maps/Exoplanet Icy/KS7535_2.dmm
  maps/Exoplanet Mining/PYK248.dmm
  maps/Exoplanet Mining/areas.dm
  maps/Exoplanet Mining/includes.dm
  maps/Exoplanet Mining/overmap.dm
  maps/Exoplanet Mining/sector_icon.dmi
  maps/Exoplanet Mining/spawns_jobs.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/spawns_jobs.dm
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/CCV_Slow_But_Steady.dmm
  maps/first_contact/maps/CCV_Star.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/corvette_spawns.dm
  maps/first_contact/overall_jobdefs.dm
Labels: enhancement/QOL, mapping, overmap

#615 Covenant wall and Projeresist window explosion buffs
  code/game/objects/structures/window.dm
  code/modules/halo/turfs/covenant/materials.dm
Labels: enhancement/QOL

#617 Fixes an Icon issue with the walls on research and jobdef/bloodpacks
  maps/Asteroid Listening Post/spawns_jobs.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/overall_jobdefs.dm
Labels: bug, mapping

#612 Geminus City Tweaks/ Theta Project Change
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, mapping

#621 Fixes space turfs opening on planets
  maps/Exoplanet Icy/areas.dm
  maps/Exoplanet Mining/areas.dm
  maps/Exoplanet Research/areas.dm
  maps/desert_outpost/turfs_areas.dm
  maps/geminus_city/areas.dm
Labels: bug, enhancement/QOL

#619 Asteroid mining fix
  maps/Exoplanet Mining/PYK248.dmm
Labels: bug, mapping, oversight
