Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-08, with the labels that each got.

#730 New ONI armor
  baystation12.dme
  code/modules/halo/clothing/item_oni.dmi
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/oni_guard.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/machete.dmi
  code/modules/halo/weapons/melee.dm
Labels: enhancement/QOL, spriting

#731 Adds ONI Gear.
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/storage.dmi
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/Exoplanet Research/spawn_jobs.dm
  maps/first_contact/maps/UNSC_Corvette.dmm
Labels: enhancement/QOL

#733 Fixes minor bugs.
  code/modules/halo/clothing/donator_ODST.dmi
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  html/changelogs/Flaksim update 08 august.yml
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Asteroid Listening Post/areas.dm
  maps/first_contact/maps/Asteroid Listening Post/spawns_jobs.dm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_0.dmm
  maps/first_contact/maps/Exoplanet Research/spawn_jobs.dm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/comet_spawns.dm
  maps/first_contact/maps/kig_yar_pirates/spawns_jobs.dm
  maps/first_contact/overall_jobdefs.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
Labels: enhancement/QOL, mapping

#735 Minor Fixes.
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Asteroid Listening Post/areas.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Icy/lift.dm
  maps/first_contact/maps/Exoplanet Mining/PYK248.dmm
  maps/first_contact/maps/Exoplanet Mining/backup/PYK248.dmm
  maps/first_contact/maps/Exoplanet Research/spawn_jobs.dm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/insurrection/innie_base1.dmm
Labels: bug, enhancement/QOL

#737 Add Shields to Kig-Yar Vessel
  html/changelogs/bloxgate - Shields.yml
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/kig_yar_pirates/overmap.dm
Labels: bug, enhancement/QOL, mapping, overmap, oversight

#738 Fixes overmap droppods
  code/modules/halo/vehicles/drop_pod.dm
Labels: bug

#745 Adds incapacitated checks to vehicle stuff
  code/modules/halo/vehicles/vehiclebase.dm
Labels: enhancement/QOL, feature

#744 Escape Pods, Boarding Pods, and a boarding-beacon launcher.
  baystation12.dme
  code/modules/halo/machinery/boarding_beacon_console.dmi
  code/modules/halo/machinery/boarding_beacon_launcher.dm
  code/modules/halo/machinery/boarding_beacon_proj.dmi
  code/modules/halo/vehicles/boarding_pod.dm
  code/modules/halo/vehicles/bumblebee_full.dmi
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/escape_pods.dm
  html/changelogs/boarding pods - XO11.yml
Labels: enhancement/QOL, feature

#747 Urgent fixes
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/vehicles/boarding_pod.dm
  code/modules/halo/vehicles/drop_pod.dm
  maps/area_holders/backup/overmap_ship_area_holder.dmm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Exoplanet Research/spawn_jobs.dm
  maps/first_contact/maps/UNSC_Corvette.dmm
  maps/first_contact/maps/UNSC_Corvette2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/first_contact/maps/UNSC_Thorin/areas.dm
  maps/first_contact/maps/UNSC_Thorin/includes.dm
  maps/first_contact/maps/UNSC_Thorin/lifts.dm
  maps/first_contact/maps/UNSC_Thorin/overmap.dm
  maps/first_contact/maps/UNSC_Thorin/spawns_jobs.dm
  maps/first_contact/overall_overmap.dm
  maps/overmap_ships/om_ship_areas.dm
  maps/unsc_frigate/unsc_frigate.dm
  maps/unsc_frigate/unsc_frigate_base_includes.dm
Labels: bug, enhancement/QOL

#750 Adds buckets.
  code/game/machinery/vending.dm
  code/modules/halo/structures/geminus_city_outfits.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Icy/areas.dm
  maps/first_contact/maps/Exoplanet Icy/spawns_jobs.dm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/overall_jobdefs.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
Labels: enhancement/QOL, feature, mapping

#741 Covenant features
  baystation12.dme
  code/game/machinery/doors/multi_tile.dm
  code/modules/ZAS/Atom.dm
  code/modules/halo/NPC/npc_interact.dm
  code/modules/halo/covenant/antimatter_bomb.dm
  code/modules/halo/covenant/banshee.dm
  code/modules/halo/covenant/bed.dm
  code/modules/halo/covenant/bed.dmi
  code/modules/halo/covenant/door128.dmi
  code/modules/halo/covenant/door128ew.dmi
  code/modules/halo/covenant/door64.dmi
  code/modules/halo/covenant/door64ew.dmi
  code/modules/halo/covenant/door96.dmi
  code/modules/halo/covenant/door96ew.dmi
  code/modules/halo/covenant/drone.dm
  code/modules/halo/covenant/drone.dmi
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/covenant/energybarricade.dmi
  code/modules/halo/covenant/engineer.dm
  code/modules/halo/covenant/engineer.dmi
  code/modules/halo/covenant/food_nipple.dm
  code/modules/halo/covenant/food_nipple.dmi
  code/modules/halo/covenant/grav.dm
  code/modules/halo/covenant/grav128.dmi
  code/modules/halo/covenant/grav32.dmi
  code/modules/halo/covenant/grav64.dmi
  code/modules/halo/covenant/grav96.dmi
  code/modules/halo/covenant/multitile_airlocks.dm
  code/modules/halo/covenant/pillar_lift.dm
  code/modules/halo/covenant/pillar_lift.dmi
  code/modules/halo/covenant/pinch_fusion.dm
  code/modules/halo/covenant/pinch_fusion128x128.dmi
  code/modules/halo/covenant/prophet.dm
  code/modules/halo/covenant/prophet.dmi
  code/modules/halo/covenant/ramp.dm
  code/modules/halo/covenant/ramp.dmi
  code/modules/halo/covenant/shadow.dm
  code/modules/halo/covenant/shadow.dmi
  code/modules/halo/covenant/shipnames.dm
  code/modules/halo/icons/AI_Melon.dmi
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/icons/Graffiti.dmi
  code/modules/halo/icons/banshee.dmi
  code/modules/halo/icons/species/SanShyuum.dmi
  code/modules/halo/machinery/covie_pulse_turret.dm
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/spirit.dmi
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/movement.dm
  config/names/covenant_ship_names.txt
  html/changelogs/cael_cov_14.8.yml
Labels: feature

#752 Minor Kig-Yar Ship additions.
  code/__defines/species_lists.dm
  code/modules/halo/covenant/drone.dm
  code/modules/halo/covenant/multitile_airlocks.dm
  code/modules/halo/doors/Airlockblastdouble.dmi
  code/modules/halo/doors/Airlockdouble.dmi
  html/changelogs/changelog flaksim 18 august.yml
  icons/obj/doors/Door2x1glass.dmi
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/CCV_Comet.dmm
  maps/first_contact/maps/CCV_Slow_But_Steady.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_0.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
Labels: enhancement/QOL, feature, mapping

#758 kig yar door fixes and thorin cell charger fix
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
Labels: enhancement/QOL, mapping

#763 MA5B AR was spawning instead of the M98
  html/changelogs/Ingredients - 8.20.2018.yml
  maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
Labels: enhancement/QOL

#759 Minor map improvements.
  code/modules/halo/clothing/odst.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Icy/backup/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Icy/spawns_jobs.dm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/unsc_frigate/unsc_frigate_innies_geminus.dm
Labels: enhancement/QOL, in-progress

#764 Medical Freighter
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/first_contact/deliverance.dmi
  maps/first_contact/maps/CCV_Deliverance.dmm
  maps/first_contact/maps/ccv_deliverance_spawns.dm
  maps/first_contact/overall_overmap.dm
  maps/overmap_ships/om_ship_areas.dm
Labels: enhancement/QOL, feature, mapping

#767 Minor additions.
  maps/first_contact/deliverance.dmi
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/overall_jobdefs.dm
Labels: enhancement/QOL

#774 Various fixes and tweaks
  code/modules/halo/clothing/grunt_leg_armor.dmi
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/living/carbon/human/species/outsider/grunts.dm
  code/modules/organs/external/head.dm
  code/modules/organs/external/standard.dm
Labels: bug, enhancement/QOL

#776 Updates UNSC Bertels significantly, self contained job roles and spawns
  baystation12.dme
  html/changelogs/changelog flaksim 29 august.yml
  maps/first_contact/all_includes.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/areas.dm
  maps/first_contact/maps/UNSC_Bertels/includes.dm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/UNSC_Bertels/outfits.dm
  maps/first_contact/maps/UNSC_Bertels/ship implementation documentation.dm
  maps/first_contact/maps/UNSC_Bertels/spawns_jobs.dm
  maps/first_contact/overall_jobdefs.dm
  maps/odst_training/maps/Exoplanet Research/spawn_jobs.dm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/odst_training/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/odst_training/maps/UNSC_Bertels/areas.dm
  maps/odst_training/maps/UNSC_Bertels/includes.dm
  maps/odst_training/maps/UNSC_Bertels/jobs.dm
  maps/odst_training/maps/UNSC_Bertels/outfits.dm
  maps/odst_training/maps/UNSC_Bertels/ship implementation documentation.dm
  maps/odst_training/maps/UNSC_Bertels/spawns_jobs.dm
  maps/odst_training/overall_jobdefs.dm
  maps/unsc_frigate/outfits/command.dm
  maps/unsc_frigate/unsc_frigate_base_includes.dm
Labels: enhancement/QOL, mapping
