Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-12, with the labels that each got.

#963 Geminus Map Fixes
  maps/geminus_city/geminuscity_2.dmm
Labels: mapping

#964 Various fixes and changes.
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/melee.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/ammunition.dm
  maps/Flaksim Map Project/Desertground +1.dmm
  maps/Flaksim Map Project/Desertground -1.dmm
  maps/Flaksim Map Project/Desertground.dmm
  maps/Flaksim Map Project/Implementation documentation.dm
  maps/Flaksim Map Project/areas.dm
  maps/Flaksim Map Project/includes.dm
  maps/Flaksim Map Project/jobs.dm
  maps/Flaksim Map Project/outfits.dm
  maps/Flaksim Map Project/overmap.dm
  maps/Flaksim Map Project/spawns_jobs.dm
  maps/first_contact/maps/Covenant Corvette/outfits.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/UNSC_Prowler/UNSC_Prowler_Deck_1.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/first_contact/maps/URF Commando Ship/prowler.dmi
  maps/geminus_city/backup/geminuscity_2.dmm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_2.dmm.orig
Labels: enhancement/QOL, feature

#971 Fix mislinked cryos on bertels and thorin
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: mapping, oversight

#972 Spartan Laser + Spartan Shield sounds + Misc Armour changes
  baystation12.dme
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/sounds/Shields_Gone.ogg
  code/modules/halo/sounds/Shields_Recharge.ogg
  code/modules/halo/sounds/Spartan_Laser_Beam_Shot_Sound_Effect.ogg
  code/modules/halo/sounds/Spartan_Laser_Charge_Sound_Effect.ogg
  code/modules/halo/species_items/spartan.dm
  code/modules/halo/weapons/charged.dm
  code/modules/halo/weapons/energy.dm
  code/modules/halo/weapons/projectiles/beams.dm
  code/modules/projectiles/gun.dm
Labels: Do Not Merge, in-progress

#977 Donor Gear December Update Part 1
  code/modules/halo/clothing/SpartanHussarKit.dmi
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/spartan_armour_variants.dm
  code/modules/halo/clothing/urc_commando_variants.dm
  code/modules/halo/clothing/urf_commando.dmi
Labels: feature

#980 Sprite update
  code/modules/halo/overmap/icons/Sparrowhawk.dmi
  code/modules/halo/overmap/icons/components.dmi
  code/modules/halo/overmap/icons/fire.dmi
  code/modules/halo/overmap/icons/longsword.dmi
  code/modules/halo/overmap/icons/mount_background.dmi
  code/modules/halo/overmap/icons/overmap_vehicle_hud.dmi
  code/modules/halo/overmap/icons/overmap_vehicles.dmi
  code/modules/halo/overmap/icons/pelican.dmi
  code/modules/halo/overmap/icons/pelican_old.dmi
  code/modules/halo/overmap/icons/sabre.dmi
  code/modules/halo/overmap/icons/weapons.dmi
  code/modules/halo/turfs/covenant/Covvie_newwalls (1).dmi
  code/modules/halo/turfs/covenant/Covvie_newwalls.dmi
  icons/turf/space.dmi
  icons/turf/wall_masks.dmi
  maps/first_contact/maps/Exoplanet Icy/ks7.png
  maps/first_contact/maps/Exoplanet Icy/sector_icon.dmi
  maps/first_contact/maps/Exoplanet Research/sector_icon.dmi
  maps/first_contact/maps/Exoplanet Research/vt9.png
Labels: enhancement/QOL, spriting

#985 Huragok
  baystation12.dme
  code/modules/halo/misc/huragok.dm
  code/modules/halo/misc/huragok.dmi
Labels: feature

#1002 Offical 2530 timeskip
  code/_global_vars/configuration.dm
Labels: enhancement/QOL

#1009 Misc bugfixes and tweaks
  code/game/turfs/biomes/grass_doodads.dm
  code/game/turfs/biomes/rock_doodads.dm
  code/modules/awaymissions/corpse.dm
  code/modules/halo/covenant/design_cov_tools.dm
  code/modules/halo/covenant/design_weapon_brute.dm
  code/modules/halo/covenant/gas_processor.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_interact_hand.dm
  code/modules/halo/misc/gas_collector.dm
  code/modules/halo/misc/gas_collector_interact.dm
  code/modules/halo/misc/gas_geyser.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/jiralhanae_outfit.dm
  code/modules/halo/weapons/explosives.dm
  code/modules/halo/weapons/icons/cov_bomb.dmi
  code/modules/halo/weapons/icons/explosives.dmi
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/multiz/structures.dm
  code/modules/shieldgen/shieldwallgen.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/packwar/doisac_surface.dmm
  maps/packwar/mode_packwar.dm
  nano/templates/autosurgeon.tmpl
  nano/templates/gas_collector.tmpl
Labels: enhancement/QOL, oversight

#1011 Legkolo buffnerf, fix for missing unggoy tanks
  baystation12.dme
  code/__defines/species_lists.dm
  code/_onclick/hud/action.dm
  code/modules/halo/icons/species/hunter_actions.dmi
  code/modules/halo/icons/species/hunters.dmi
  code/modules/halo/misc/admin_covenant_strike_team.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/species_items/grunt_outfits.dm
  code/modules/halo/species_items/lekgolo.dm
  code/modules/halo/species_items/lekgolo_attack.dm
  code/modules/halo/species_items/lekgolo_defence.dm
  code/modules/halo/species_items/lekgolo_language.dm
  code/modules/halo/species_items/lekgolo_ui.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living_defense.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/Covenant Corvette/outfits.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Mining/PYK248.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Prowler/UNSC_Prowler_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/packwar/mode_packwar.dm
Labels: enhancement/QOL

#1014 Covenant tweaks and fixes
  baystation12.dme
  code/modules/halo/covenant/drop_pod.dm
  code/modules/halo/splashworks/brutes.jpg
  code/modules/halo/splashworks/covenant.jpg
  code/modules/halo/splashworks/covenant.png
  code/modules/halo/splashworks/title5.jpg
  code/modules/halo/splashworks/title5.png
  code/modules/halo/splashworks/title6.jpg
  code/modules/halo/splashworks/title6.png
  code/modules/halo/structures/ODST_Droppod.dmi
  code/modules/halo/turfs/covenant/floor.dm
  code/modules/halo/turfs/covenant/materials.dm
  code/modules/halo/turfs/covenant/walls.dm
  code/modules/halo/vehicles/drop_pod.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/turf/wall_masks.dmi
  maps/ccs_battlecruiser/mapdef.dm
  maps/crashsite_zeta/crashsite_zeta_map.dm
  maps/desert_outpost/desert_outpost_map.dm
  maps/first_contact/mapdef.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/geminus_city/geminus_city_map.dm
  maps/insurrection/mapdef.dm
  maps/odst_training/mapdef.dm
  maps/packwar/doisac.dm
  maps/slayer/death_asteroid_map.dm
  maps/unsc_frigate/unsc_frigate_map.dm
Labels: enhancement/QOL
