Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-11, with the labels that each got.

#892 Two small bugfixes
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/weapons/covenant/handheld_shields.dm
Labels: bug

#897 unggoy spawn fix
  code/modules/halo/species/grunts.dm
Labels: enhancement/QOL, oversight

#898 Implements Grunt Deacons
  code/modules/halo/icons/species/grunt_gear.dmi
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/grunt_outfits.dm
Labels: feature

#841 Covenant tweakfixes
  baystation12.dme
  code/__defines/species_lists.dm
  code/datums/outfits/outfit.dm
  code/game/gamemodes/gameticker.dm
  code/modules/customitems/item_spawning.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/clothing/spartan_gear.dmi
  code/modules/halo/loadout/ammo.dm
  code/modules/halo/loadout/weapons.dm
  code/modules/halo/misc/armourspecials/gear_defs.dm
  code/modules/halo/species/spartan.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/new_player/new_player.dm
  html/changelog.html
  maps/ccs_battlecruiser/_opredflag_includes.dm
  maps/ccs_battlecruiser/ccs_areas.dmi
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser2.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser3.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser_areas.dm
  maps/ccs_battlecruiser/jobs/elite.dm
  maps/ccs_battlecruiser/jobs/grunt.dm
  maps/ccs_battlecruiser/jobs/hunter.dm
  maps/ccs_battlecruiser/jobs/jackal.dm
  maps/ccs_battlecruiser/jobs/prophet.dm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/ccs_battlecruiser/mode_opredflag.dm
  maps/ccs_battlecruiser/opr_hud_icons.dmi
Labels: bug, enhancement/QOL, feature

#905 Species-wide melee force multiplier.
  code/_onclick/item_attack.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/mob/living/carbon/human/species/species.dm
Labels: feature

#908 Fix Kig-Yar/Spartan spawns
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/spartan.dm
Labels: bug, oversight

#909 Operation: Red Flag tweaks and fixes
  baystation12.dme
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/spartan_armour_variants.dm
  code/modules/halo/covenant/comms.dm
  code/modules/halo/covenant/comms.dmi
  code/modules/halo/covenant/crate.dm
  code/modules/halo/covenant/crate.dmi
  code/modules/halo/covenant/grav32.dmi
  code/modules/halo/covenant/jump_pad.dm
  code/modules/halo/covenant/slipspace.dm
  code/modules/halo/covenant/slipspace.dmi
  code/modules/halo/icons/species/skirm_clothing.dmi
  code/modules/halo/species_items/skirmisher_armour.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/living/carbon/brain/brain.dm
  html/changelog.html
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser2.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser3.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/jobs/hunter.dm
  maps/ccs_battlecruiser/jobs/jackal.dm
  maps/ccs_battlecruiser/jobs/prophet.dm
  maps/ccs_battlecruiser/mode_opredflag.dm
  maps/ccs_battlecruiser/planet_staging.dmm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
Labels: bug, enhancement/QOL, feature, mapping, spriting

#911 Tweaks and fixes to Operation: Red Flag
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/spartan.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/species.dm
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser2.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser3.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/planet_staging.dmm
Labels: enhancement/QOL, feature

#912 Nerfs plasmagrenades slightly
  code/modules/halo/weapons/covenant/grenades.dm
Labels: enhancement/QOL

#920 Covenant tweaks and fixes
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/halo/covenant/multitile_airlocks.dm
  code/modules/halo/icons/species/r_Augmented_Human.dmi
  code/modules/halo/icons/species/r_kig-yar.dmi
  code/modules/halo/icons/species/r_sanshyuum.dmi
  code/modules/halo/icons/species/r_unggoy.dmi
  code/modules/halo/machinery/covenant/doors.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/skirmisher_outfits.dm
  code/modules/halo/weapons/covenant/handheld_shields.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/new_player/preferences_setup.dm
  html/changelog.html
Labels: bug, enhancement/QOL, feature

#921 Flood infestation changes
  baystation12.dme
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_infection_chem.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  maps/desert_outpost/gamemode/mode_stranded.dm
  maps/desert_outpost/gamemode/mode_stranded_attackers_spawn.dm
Labels: enhancement/QOL, feature

#929 Adds secure airlocks to covenant corvette in FC
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
Labels: enhancement/QOL, mapping

#934 Misc Covenant fixes and tweaks
  baystation12.dme
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/comms/covenant_comms.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/misc/armourspecials/holo_decoy.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/lekgolo.dm
  code/modules/halo/species_items/sanshyuum.dm
  code/modules/halo/species_items/spartan.dm
  code/modules/mob/living/say.dm
  code/modules/projectiles/projectile.dm
  code/procs/announce.dm
  html/changelog.html
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/jobs/hunter.dm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/ccs_battlecruiser/mode_opredflag.dm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
Labels: bug, enhancement/QOL

#924 Add URF Commando Equipment
  baystation12.dme
  code/modules/halo/clothing/urc_commando_variants.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/clothing/urf_commando.dmi
  code/modules/halo/clothing/urf_commando_sets.dm
Labels: enhancement/QOL, feature, in-progress

#936 OPRF player navigation and misc cov tweaks
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sanshyuum.dm
  maps/ccs_battlecruiser/_opredflag_includes.dm
  maps/ccs_battlecruiser/arrow.dmi
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser2.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser3.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/jobs/elite.dm
  maps/ccs_battlecruiser/jobs/grunt.dm
  maps/ccs_battlecruiser/jobs/hunter.dm
  maps/ccs_battlecruiser/jobs/jackal.dm
  maps/ccs_battlecruiser/jobs/prophet.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/ccs_battlecruiser/mode_opredflag.dm
  maps/ccs_battlecruiser/playernav.dm
Labels: feature

#950 Rebalances Speed Chems
  code/__defines/chemistry.dm
  code/__defines/mobs.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/chemicals/recipes.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: enhancement/QOL

#949 Misc Covenant work
  baystation12.dme
  code/modules/halo/covenant/cleaning_drone.dm
  code/modules/halo/covenant/cleaning_drone.dmi
  code/modules/halo/covenant/cryotube.dm
  code/modules/halo/covenant/cryotube.dmi
  maps/first_contact/overall_jobdefs.dm
Labels: bug, feature

#948 Cryostation13
  html/changelog.html
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Prowler/UNSC_Prowler_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, mapping

#953 NPC ship work
  code/__defines/npc_comms_authority_levels.dm
  code/modules/halo/machinery/npc_comms.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_cargo_ship.dm
  code/modules/halo/overmap/npc_ships.dm
Labels: enhancement/QOL

#952 Adds autosurgeons
  baystation12.dme
  code/modules/halo/machinery/autosurgeon/_defines.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon.dmi
  code/modules/halo/machinery/autosurgeon/autosurgeon_firstaid.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_interact_hand.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_interact_item.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_interact_ui.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_process.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_topic.dm
  code/modules/halo/machinery/autosurgeon/covenant.dm
  code/modules/halo/machinery/autosurgeon/~autosurgeon.dm
  nano/templates/autosurgeon.tmpl
Labels: feature

#959 Avarice Mapping Hotfix
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/structures/gunvendors.dm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/first_contact/maps/URF Commando Ship/jobs.dm
Labels: enhancement/QOL, mapping, oversight

#961 New megamap.
  code/modules/halo/clothing/odst.dm
  code/modules/halo/structures/gunvendors.dm
  maps/Flaksim Map Project/Desertground +1.dmm
  maps/Flaksim Map Project/Desertground -1.dmm
  maps/Flaksim Map Project/Desertground.dmm
  maps/Flaksim Map Project/Implementation documentation.dm
  maps/Flaksim Map Project/areas.dm
  maps/Flaksim Map Project/includes.dm
  maps/Flaksim Map Project/jobs.dm
  maps/Flaksim Map Project/outfits.dm
  maps/Flaksim Map Project/overmap.dm
  maps/Flaksim Map Project/spawns_jobs.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/UNSC_Prowler/UNSC_Prowler_Deck_1.dmm
  maps/first_contact/maps/URF Commando Ship/prowler.dmi
  maps/geminus_city/backup/geminuscity_2.dmm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminuscity_2.dmm
Labels: feature, in-progress, mapping
