Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2018-03, with the labels that each got.

#443 Desodone Hotfix7
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/halo/weapons/snipers.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminus_city_outfits.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/interiorobjs.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_geminus.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
Labels: enhancement/QOL, mapping

#444 Overmap Weapons + MAC and orbital bombardment designators
  baystation12.dme
  code/modules/halo/clothing/odst.dm
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/laser_designator.dm
  code/modules/halo/machinery/laser_designator.dmi
  code/modules/halo/machinery/mac_ammo.dmi
  code/modules/halo/machinery/mac_cannon.dmi
  code/modules/halo/machinery/mac_gun_fire.ogg
  code/modules/halo/machinery/mac_gun_load.ogg
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/machinery/overmap_weapon_ammo.dm
  code/modules/halo/machinery/overmap_weapon_base.dmi
  code/modules/halo/structures/drop_pods.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/gun.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate_areas.dm
  maps/unsc_frigate/unsc_frigate_overmap.dm
Labels: Zlevels, enhancement/QOL, feature, mapping, overmap

#447 ID cards apply the correct access again
  code/game/objects/items/weapons/cards_ids.dm
Labels: enhancement/QOL, oversight

#449 Flashbang And SRS Stun nerf
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_helpers.dm
  icons/mob/screen1.dmi
Labels: Controversial, enhancement/QOL, oversight

#450 Weapon Vendor Unlock Buttons
  baystation12.dme
  code/modules/halo/machinery/buttons/basic_weapon_vendor_unlock.dm
  code/modules/halo/machinery/buttons/heavy_weapon_vendor_unlock.dm
  maps/unsc_frigate/unsc_frigate-3.dmm
Labels: feature

#461 Innsurrectionist Update
  code/game/objects/items/devices/spy_bug.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/halo/weapons/explosives.dm
  code/modules/reagents/reagent_containers/pill.dm
  maps/insurrection/innie_base1.dmm
  maps/insurrection/insurrection_outfits.dm
  maps/unsc_frigate/unsc_frigate-4.dmm
Labels: enhancement/QOL, feature

#465 Re-enables crafting
  baystation12.dme
  code/modules/materials/material_recipes.dm
  html/changelogs/crafting-reenable.yml
  maps/desert_outpost/gamemode/materials.dm
  maps/~mapsystem/material_recipes.dm
Labels: feature

#464 Buttons
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/snipers.dm
  icons/mob/ties.dmi
  icons/obj/clothing/ties.dmi
  maps/insurrection/innie_base1.dmm
  maps/insurrection/innie_base2.dmm
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/outfits/logistics.dm
  maps/unsc_frigate/outfits/marines.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
  sdv_corvette.dmm
Labels: enhancement/QOL, mapping

#467 General Tweaking Madness
  code/game/objects/items/weapons/explosives.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/halo/clothing/jumpsuits.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/deploy_kits.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/streetobjs.dm
  maps/insurrection/innie_base1.dmm
  maps/insurrection/insurrection_outfits.dm
  maps/unsc_frigate/outfits/marines.dm
  maps/unsc_frigate/unsc_frigate-3.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
Labels: enhancement/QOL, mapping

#471 Small code cut
  code/game/machinery/portable_turret.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/alien/resin.dm
  code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
  code/modules/admin/topic.dm
  code/modules/clothing/clothing.dm
  code/modules/ghosttrap/trap.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_mobs.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/materials/materials.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/alien_attacks.dm
  code/modules/mob/living/carbon/alien/alien_damage.dm
  code/modules/mob/living/carbon/alien/death.dm
  code/modules/mob/living/carbon/alien/diona/death.dm
  code/modules/mob/living/carbon/alien/diona/diona.dm
  code/modules/mob/living/carbon/alien/diona/diona_attacks.dm
  code/modules/mob/living/carbon/alien/diona/diona_powers.dm
  code/modules/mob/living/carbon/alien/diona/life.dm
  code/modules/mob/living/carbon/alien/diona/progression.dm
  code/modules/mob/living/carbon/alien/diona/say_understands.dm
  code/modules/mob/living/carbon/alien/diona/update_icons.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/alien/larva/powers.dm
  code/modules/mob/living/carbon/alien/larva/progression.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/alien/progression.dm
  code/modules/mob/living/carbon/alien/say.dm
  code/modules/mob/living/carbon/alien/update_icons.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_powers.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/alien_species.dm
  code/modules/mob/living/carbon/human/species/xenomorphs/xenomorphs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/external/diona.dm
  code/modules/organs/external/xenos.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/spells/racial_wizard.dm
Labels: enhancement/QOL

#472 ODST whitelisting.
  code/controllers/configuration.dm
  code/game/jobs/job/job.dm
  code/game/jobs/whitelist.dm
  code/modules/admin/banjob.dm
  code/modules/mob/new_player/new_player.dm
  data/whitelist.txt
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/unsc_frigate-3.dmm
Labels: enhancement/QOL, feature

#473 Geminius City Updates/Bugfixes
  html/changelogs/DoctorOctopusTheOctopi-PR-473.yml
  maps/geminus_city/geminuscity_2.dmm
Labels: bug, enhancement/QOL, mapping

#482 Big Changes
  html/changelogs/DoctorOctopusTheOctopi-PR-473.yml
  maps/geminus_city/geminuscity_2.dmm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
Labels: enhancement/QOL, mapping

#488 Tranquility2.1
  baystation12.dme
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/halo/weapons/melee.dm
  code/modules/halo/weapons/rifles.dm
  data/whitelist.txt
  maps/DesoMaps/CA-Ace_of_Spades-z1.dmm
  maps/DesoMaps/CA-Ace_of_Spades-z2.dmm
  maps/DesoMaps/CA-Ace_of_Spades.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/interiorobjs.dm
  maps/insurrection/ODST_staging.dmm
  maps/insurrection/backup/ODST_staging.dmm
  maps/insurrection/hangar_door.dmi
  maps/insurrection/innie_base1.dmm
  maps/insurrection/innie_base2.dmm
  maps/insurrection/innie_base3.dmm
  maps/insurrection/innie_base4.dmm
  maps/insurrection/innie_base_areas.dm
  maps/insurrection/innie_base_overmap.dm
  maps/insurrection/insurrection.dm
  maps/insurrection/insurrection_items.dm
  maps/insurrection/sector_icon.dmi
  maps/old/backup/tranquility-z1.dmm
  maps/old/oldinnie_base1.dmm
  maps/old/oldinnie_base2.dmm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
  maps/unsc_frigate/unsc_frigate_innies_geminus.dm
Labels: enhancement/QOL, feature, mapping

#493 Fixes/Minor Additions
  code/modules/halo/clothing/spartan.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminus_city_outfits.dm
  maps/unsc_frigate/outfits/command.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
  maps/unsc_frigate/unsc_frigate-4.dmm
Labels: Do Not Merge, enhancement/QOL, feature

#498 Some Buffs for Spartans
  baystation12.dme
  code/modules/halo/chemicals/toxins.dm
  code/modules/halo/species_items/spartan.dm
  code/modules/mob/living/carbon/human/species/station/spartan.dm
  code/modules/organs/internal/liver.dm
  html/changelogs/bloxgate-spartan-buffing.yml
Labels: enhancement/QOL, feature

#502 UNSC Bonanza
  code/game/machinery/nuclear_bomb.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/paperwork/folders.dm
  code/modules/security levels/keycard authentication.dm
  html/changelogs/octop-unsc-bonanza.yml
  icons/obj/bureaucracy.dmi
  maps/unsc_frigate/frigate_hud_icons.dmi
  maps/unsc_frigate/jobs/command.dm
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/jobs/naval_security.dm
  maps/unsc_frigate/outfits/command.dm
  maps/unsc_frigate/outfits/marines.dm
  maps/unsc_frigate/outfits/medical.dm
  maps/unsc_frigate/outfits/naval_security.dm
  maps/unsc_frigate/outfits/pilot.dm
  maps/unsc_frigate/outfits/technical.dm
  maps/unsc_frigate/unsc_frigate-1.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
Labels: bug, enhancement/QOL, feature, mapping

#495 Implements a weapon attachment system.
  baystation12.dme
  code/modules/halo/icons/attachments/barrel.dmi
  code/modules/halo/icons/attachments/sights.dmi
  code/modules/halo/icons/attachments/stocks.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/smg.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/attachment_system.dm
  code/modules/projectiles/attachments/barrel.dm
  code/modules/projectiles/attachments/sights.dm
  code/modules/projectiles/attachments/stocks.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile.dm
  html/changelogs/DoctorOctopusTheOctopi-PR-473.yml
  html/changelogs/Terror4000rus-InnieBaseTweak.yml
Labels: feature, in-progress

#505 Small fixes/additions
  code/modules/halo/clothing/jumpsuits.dm
  maps/insurrection/insurrection_spawns.dm
  maps/odst_prowler/ODST_Ship.dmm
  maps/unsc_frigate/frigate_hud_icons.dmi
  maps/unsc_frigate/jobs/marines.dm
  maps/unsc_frigate/jobs/unsc_jobs_includes.dm
  maps/unsc_frigate/outfits/marines.dm
  maps/unsc_frigate/unsc_frigate-2.dmm
  maps/unsc_frigate/unsc_frigate-3.dmm
  maps/unsc_frigate/unsc_frigate_spawndefs_geminus.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_innies_geminus.dm
  maps/unsc_frigate/unsc_frigate_spawndefs_insurrection.dm
  maps/unsc_frigate/unsc_frigate_spawns.dm
Labels: bug, enhancement/QOL, feature, mapping

#506 Whitelist/Umbilical fix
  code/game/jobs/whitelist.dm
  code/modules/halo/overmap/umbilicals.dm
Labels: bug

#510 Innie Medical Stuff
  maps/insurrection/innie_base3.dmm
  maps/insurrection/innie_base4.dmm
  maps/insurrection/innie_base_map.dm
Labels: enhancement/QOL, mapping

#511 Wowie! Look at all these changes.
  code/game/machinery/nuclear_bomb.dm
  code/game/machinery/portable_turret.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/mob/living/carbon/human/npcs.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  html/changelogs/octo-gcrd-changes.yml
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/unsc_frigate/unsc_frigate-2.dmm
Labels: bug, enhancement/QOL, feature, mapping

#513 Vehicle Overhaul
  baystation12.dme
  code/modules/halo/shuttles/pelican.dmi
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/mongoose.dm
  code/modules/halo/vehicles/pelican.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, feature

#512 Misc Stranded fixes
  code/game/turfs/biome.dm
  code/game/turfs/daynight_cycle.dm
  code/modules/halo/flood/flood.dm
  html/changelogs/cael_stranded_march.yml
  maps/crashsite_zeta/crashsite-zeta.dmm
  maps/desert_outpost/desert_outpost.dmm
  maps/desert_outpost/gamemode/mode_stranded.dm
  maps/desert_outpost/gamemode/mode_stranded_start.dm
Labels: bug
