Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-06, with the labels that each got.

#1587 readds geminus jobdef
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/halo/overmap/player_shuttles.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
Labels: bug

#1590 Fixes KS7's Co-ord console
  maps/ks7_elmsville/KS7_535_2_Glassed.dmm
Labels: enhancement/QOL, mapping

#1592 nerfs glassed ks7's autoturret
  code/modules/halo/weapons/autoturret.dm
Labels: enhancement/QOL

#1595 fixes geminus uber-pelican
  code/modules/halo/vehicles/pelican.dm
  maps/geminus_city/geminuscity_2.dmm
Labels: bug

#1597 URF armor fix
  code/modules/halo/clothing/inniearmor.dmi
Labels: enhancement/QOL

#1599 Legacy Fixes
  maps/Admin Planet/surface.dmm
  maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/Exoplanet Research/ExoResearch_0.dmm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/ExoResearch_3.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/URF Commando Ship/first_deck.dmm
  maps/faction_bases/Covenant_Station.dmm
  maps/faction_bases/Human_Station_1.dmm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/ks7_elmsville/KS7_535_2_Glassed.dmm
Labels: Zlevels, bug, mapping, oversight

#1598 Enable CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement/QOL

#1601 Fix some misc mapping issues
  code/modules/halo/misc/loot_distributor.dm
  maps/UNSC_Bertels/outfits.dm
  maps/faction_bases/Innie_Base.dmm
Labels: bug

#1596 Geminus MAC rebalance
  code/modules/halo/species/kig-yar.dm
  html/changelogs/XO-11 - GeminusMac.yml
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, feature

#1603 Renames insurrection gamemode and mapset to operation trebuchet
  .travis.yml
  maps/operation_trebuchet/ODST_staging.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/Heavycorvette.dmi
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_1.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_2.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/areas.dm
  maps/operation_trebuchet/UNSC_Yolotanker/includes.dm
  maps/operation_trebuchet/UNSC_Yolotanker/jobs.dm
  maps/operation_trebuchet/UNSC_Yolotanker/outfits.dm
  maps/operation_trebuchet/UNSC_Yolotanker/overmap.dm
  maps/operation_trebuchet/UNSC_Yolotanker/ship implementation documentation.dm
  maps/operation_trebuchet/UNSC_Yolotanker/spawns_jobs.dm
  maps/operation_trebuchet/hangar_door.dmi
  maps/operation_trebuchet/innie_base1.dmm
  maps/operation_trebuchet/innie_base2.dmm
  maps/operation_trebuchet/innie_base3.dmm
  maps/operation_trebuchet/innie_base4.dmm
  maps/operation_trebuchet/innie_base_areas.dm
  maps/operation_trebuchet/innie_base_overmap.dm
  maps/operation_trebuchet/insurrection_gm.dm
  maps/operation_trebuchet/insurrection_hud_icons.dmi
  maps/operation_trebuchet/insurrection_items.dm
  maps/operation_trebuchet/insurrection_jobs.dm
  maps/operation_trebuchet/insurrection_outfits.dm
  maps/operation_trebuchet/insurrection_spawns.dm
  maps/operation_trebuchet/mapdef.dm
  maps/operation_trebuchet/oldinnie_base1.dmm
  maps/operation_trebuchet/oldinnie_base2.dmm
  maps/operation_trebuchet/operation_trebuchet.dm
  maps/operation_trebuchet/sector_icon.dmi
  maps/operation_trebuchet/unsc_staging_areas.dm
Labels: enhancement/QOL

#1604 Fix misc travis map issues
  code/modules/halo/misc/loot_distributor.dm
  maps/Admin Planet/areas.dm
  maps/Asteroid Listening Post/areas.dm
  maps/Covenant Corvette/areas.dm
  maps/UNSC_Bertels/outfits.dm
  maps/UNSC_Thorin/includes.dm
  maps/URF Commando Ship/areas.dm
  maps/civ_ships/CCV_Comet.dm
  maps/faction_bases/Innie_Base.dmm
Labels: enhancement/QOL

#1606 Disable kigyar shipmistress role
  maps/Covenant Corvette/jobs.dm
  maps/_gamemodes/invasion/jobdefs_geminus.dm
  maps/faction_bases/faction_spawns.dm
Labels: enhancement/QOL

#1605 UNSC and Covenant start knowing the location of geminus colony
  code/modules/halo/overmap/nav_data_computer.dm
Labels: enhancement/QOL

#1609 misc fixes
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/smg.dm
  code/modules/halo/weapons/snipers.dm
  html/changelogs/bdpuffy420-general-miscfixes.yml
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/faction_bases/Human_Station_2.dmm
  maps/faction_bases/Innie_Base.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, mapping, oversight, spriting

#1562 [DNM] Overmap Autopilot Adjustments
  code/modules/overmap/ships/computers/helm.dm
  html/changelogs/bloxgate - autopilot.yml
Labels: enhancement/QOL, overmap

#1608 Geminus underground
  baystation12.dme
  code/modules/halo/Forerunner/Monitor.dmi
  code/modules/halo/Forerunner/Sentinel.dmi
  code/modules/halo/Forerunner/monitor.dm
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/misc/giant_rat.dm
  code/modules/halo/misc/giant_rat.dmi
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/overmap/sectors.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/RenGusta-Gun-Balance-Refactor.yml
  html/changelogs/XO-11 - GeminusMac.yml
  maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/Asteroid Listening Post/includes.dm
  maps/Asteroid Listening Post/jobs.dm
  maps/Asteroid Listening Post/overmap.dm
  maps/Asteroid Listening Post/spawns.dm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/URF Commando Ship/includes.dm
  maps/URF Commando Ship/jobs.dm
  maps/URF Commando Ship/spawns.dm
  maps/URF Commando Ship/spawns_jobs.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/_gamemodes/invasion/innie_crew_spawns.dm
  maps/_gamemodes/invasion/jobdefs_geminus.dm
  maps/_gamemodes/invasion/overall_outfits.dm
  maps/faction_bases/faction_base.dm
  maps/faction_bases/faction_spawns.dm
  maps/faction_bases/faction_spawns_innie.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/bumpstairs.dm
  maps/geminus_city/fakewall.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/innie_outfits.dm
  maps/geminus_city/innie_spawns.dm
  maps/geminus_city/sewer_tunnel_thin.dm
Labels: feature, mapping

#1612 Sprite fix and ACL-55
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/icons/objs/halohumanmisc.dmi
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/launchers.dm
Labels: enhancement/QOL, feature, spriting

#1615 Geminus underground fixes
  maps/geminus_city/bumpstairs.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/innie_jobs.dm
Labels: bug, mapping

#1616 More tweaks and fixes Geminus underground
  baystation12.dme
  code/game/turfs/simulated/water.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/bdpuffy420-general-miscfixes.yml
  maps/geminus_city/bumpstairs.dm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/sewer_tunnel_thin.dm
Labels: bug, enhancement/QOL, mapping

#1617 Shield generator cap
  code/modules/shield_generators/shield_generator.dm
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
Labels: feature

#1623 General Geminus and more QOL
  code/game/movietitles.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  html/changelogs/BDpuffy420-Geminusfixes.yml
  maps/_gamemodes/invasion/jobdefs_geminus.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/geminuscity_2.dmm
  sound/AI/welcome.ogg
  sound/music/THUNDERDOME.ogg
Labels: enhancement/QOL, mapping

#1625 Adds Covenant IDs and Grunt Heavy Sprites
  code/modules/halo/covenant/Cards.dmi
  code/modules/halo/icons/species/grunt_gear.dmi
Labels: enhancement/QOL

#1618 Finalises work on the Ship Targeting system
  code/__defines/superstructure_defines.dm
  code/modules/halo/machinery/scanning_console.dm
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/overmap_projectile.dm
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/turfs/covenant/floor.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
  html/changelogs/XO-11 - Targeting System.yml
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/Covenant Corvette/areas.dm
  maps/Covenant Corvette/overmap.dm
  maps/Exoplanet Research/overmap.dm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/UNSC_Bertels/overmap.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, feature

#1624 Adds Revolution gamemode
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/bloxgate - autopilot.yml
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/_gamemodes/invasion/overall_jobdefs_geminus.dm
  maps/geminus_city/geminus_city_jobs.dm
Labels: feature

#1628 Properly lock Revolution jobs
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job_controller.dm
  code/modules/mob/new_player/new_player.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
Labels: bug

#1629 Avarice and LMG changes
  code/modules/halo/weapons/lmg.dm
  html/changelogs/xo-11 - LMG Changes.yml
  maps/URF Commando Ship/first_deck.dmm
Labels: enhancement/QOL

#1632 Some tweaks and fixes
  code/modules/halo/Forerunner/monitor.dm
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: feature

#1634 Various overmap combat fixes
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/overmap/ships/ship.dm
  code/modules/shield_generators/shield_generator.dm
Labels: bug

#1635 potential biofoam IB-heal reliability fix
  code/modules/halo/chemicals/medicine.dm
Labels: bug

#1636 Simple animal tweaks and fixes
  code/modules/halo/Forerunner/monitor.dm
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/projectile.dm
Labels: bug, enhancement/QOL

#1637 Fix simple mob and geminus sewer rat respawns
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  maps/geminus_city/sewer_tunnel_thin.dm
Labels: bug

#1640 Donor item updates and cov battlenet chat
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/spartan_armour_large.dmi
  code/modules/halo/comms/channel_keys.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/xo-11 - LMG Changes.yml
Labels: bug, feature

#1641 Spawns rewrite (for the fourth time this year)
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job_controller.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/mob/new_player/new_player.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/Covenant Corvette/jobs.dm
  maps/UNSC_Bertels/jobs.dm
  maps/URF Commando Ship/jobs.dm
  maps/_gamemodes/faction.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/jobdefs_geminus.dm
  maps/faction_bases/faction_spawns_cov.dm
  maps/faction_bases/faction_spawns_unsc.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminus_city_spawns.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/innie_jobs.dm
  maps/~mapsystem/maps.dm
Labels: bug, enhancement/QOL

#1647 Adds directions & Drained Canister sprites
  code/modules/halo/icons/objs/halohumanmisc.dmi
  code/modules/halo/structures/Optican.dmi
Labels: enhancement/QOL

#1646 Covenant changes
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species_items/skirmisher_outfits.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/effects/projectiles.dmi
  maps/Covenant Corvette/jobs.dm
  maps/Covenant Corvette/outfits.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/ccs_battlecruiser/jobs/elite.dm
  maps/ccs_battlecruiser/jobs/hunter.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/ccs_battlecruiser/opr_hud_icons.dmi
  maps/geminus_city/geminus_hud_icons.dmi
Labels: enhancement/QOL

#1652 Sons of Eridanus update
  code/game/machinery/biogenerator.dm
  code/modules/halo/icons/overmap/big civ ships.dmi
  code/modules/halo/icons/overmap/big_civ_ships.dmi
  html/changelogs/Koenigsegg-PR-#1652.yml
  maps/Asteroid Listening Post/overmap.dm
  maps/URF Commando Ship/areas.dm
  maps/URF Commando Ship/first_deck.dmm
  maps/URF Commando Ship/jobs.dm
  maps/URF Commando Ship/mariner-class.dmi
  maps/URF Commando Ship/old/first_deck.dmm
  maps/URF Commando Ship/old/second_deck.dmm
  maps/URF Commando Ship/outfits.dm
  maps/URF Commando Ship/overmap.dm
  maps/URF Commando Ship/prowler.dmi
  maps/URF Commando Ship/second_deck.dmm
  maps/URF Commando Ship/spawns.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/_gamemodes/invasion/jobdefs_geminus.dm
Labels: enhancement/QOL

#1653 Geminus Innie base cargo shuttle
  baystation12.dme
  code/_helpers/global_access.dm
  code/controllers/master_controller.dm
  code/datums/supplypacks/security.dm
  code/game/gamemodes/gameticker.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/halo/NPC/npc_setup_trade.dm
  code/modules/halo/NPC/npc_trade.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/npc_factions.dm
  code/modules/halo/factions/npc_quests.dm
  code/modules/halo/insurrection/access_ids.dm
  code/modules/halo/insurrection/antagonist.dm
  code/modules/halo/insurrection/gamemode.dm
  code/modules/halo/insurrection/innie_factions_comms.dm
  code/modules/halo/insurrection/innie_factions_controller.dm
  code/modules/halo/insurrection/map.dm
  code/modules/halo/insurrection/objectives.dm
  code/modules/halo/insurrection/radios_freqs.dm
  code/modules/halo/trade/_trade_controller.dm
  html/changelog.html
  html/changelogs/cael_innies_cargo.yml
  icons/obj/storage.dmi
  maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/URF Commando Ship/jobs.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/innie_supply/_controller.dm
  maps/geminus_city/innie_supply/area.dm
  maps/geminus_city/innie_supply/computer.dm
  maps/geminus_city/innie_supply/export.dm
  maps/geminus_city/innie_supply/program.dm
  maps/geminus_city/innie_supply/shuttle.dm
  maps/geminus_city/unit_tests.dm
  maps/~mapsystem/maps_unit_testing.dm
  nano/templates/supply_innie.tmpl
  test/check-paths.sh
  test/run-test.sh
Labels: bug, feature, mapping

#1633 Changes job roles
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/Covenant Corvette/jobs.dm
  maps/Exoplanet Research/spawn_jobs.dm
  maps/UNSC_Bertels/jobs.dm
  maps/_gamemodes/invasion/jobdefs_geminus.dm
Labels: Controversial, enhancement/QOL

#1657 Geminus Innie tweaks
  animal_big.dmi
  baystation12.dme
  code/modules/halo/misc/animals/alligator.dm
  code/modules/halo/misc/animals/animal_big.dmi
  code/modules/halo/misc/animals/dogs.dm
  code/modules/halo/misc/animals/dogs.dmi
  code/modules/halo/misc/animals/giant_rat.dm
  code/modules/halo/misc/animals/giant_rat.dmi
  code/modules/halo/misc/animals/great_white.dm
  code/modules/halo/misc/animals/jaguar.dm
  code/modules/halo/misc/animals/panther.dm
  code/modules/halo/misc/animals/velociraptor.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  maps/geminus_city/bumpstairs.dm
  maps/geminus_city/fakewall.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/geminuscity_4.dmm
  maps/geminus_city/innie_supply/_controller.dm
  maps/geminus_city/sewer_tunnel_thin.dm
Labels: enhancement/QOL

#1655 Job species fix for gamemodes
  code/_global_vars/lists/locations.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/objects/effects/landmarks.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/unit_tests/job_tests.dm
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Heaven_Above/frigate_hud_icons.dmi
  maps/URF Commando Ship/jobs.dm
  maps/_gamemodes/invasion/jobdefs_ks7elmsville.dm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/crashsite_zeta/crashsite_zeta_map.dm
  maps/desert_outpost/desert_outpost_map.dm
  maps/desert_outpost/jobs.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/operation_trebuchet/UNSC_Yolotanker/jobs.dm
  maps/operation_trebuchet/UNSC_Yolotanker/spawns_jobs.dm
  maps/operation_trebuchet/insurrection_hud_icons.dmi
  maps/operation_trebuchet/insurrection_jobs.dm
  maps/operation_trebuchet/insurrection_spawns.dm
  maps/operation_trebuchet/mapdef.dm
  maps/~mapsystem/maps.dm
Labels: bug, enhancement/QOL

#1660 Simple mob pathing
  animal_big.dmi
  baystation12.dme
  code/game/objects/effects/landmarks.dm
  code/modules/awaymissions/corpse.dm
  code/modules/halo/Forerunner/monitor.dm
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_npc.dm
  code/modules/halo/flood/flood_spawn.dm
  code/modules/halo/flood/flood_spawn_bio.dm
  code/modules/halo/flood/flood_spawn_proxy.dm
  code/modules/halo/flood/ghost_role.dm
  code/modules/halo/misc/simple_mob_ai.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  maps/_gamemodes/stranded/mode_stranded_attackers_spawn.dm
  maps/_gamemodes/stranded/mode_stranded_start.dm
  maps/crashsite_zeta/crashsite-zeta.dmm
  maps/desert_outpost/desert_outpost.dmm
  maps/geminus_city/bumpstairs.dm
Labels: enhancement/QOL, feature

#1656 Moves the UNSC faction base to orbiting VT9, gives it automated SMAC, boosts boarding range
  baystation12.dme
  code/controllers/ProcessScheduler/core/process.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/overmap/weapons/auto_mac_console.dm
  code/modules/halo/overmap/weapons/auto_mac_program.dm
  code/modules/halo/unsc/access.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase_air_overmap.dm
  maps/Exoplanet Research/overmap.dm
  maps/UNSC_Bertels/jobs.dm
  maps/URF Commando Ship/jobs.dm
  maps/URF Commando Ship/overmap.dm
  maps/faction_bases/Cassius_Station/Cassius_Station.dm
  maps/faction_bases/Cassius_Station/Cassius_Station_1.dmm
  maps/faction_bases/Cassius_Station/Cassius_Station_2.dmm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/innie_supply/program.dm
  maps/geminus_city/invasion_geminus.dm
  nano/templates/auto_mac.tmpl
Labels: Controversial, enhancement/QOL, feature, mapping
