Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-03, with the labels that each got.

#1297 crawling/prone addition
  code/__defines/mobs.dm
  code/_onclick/click.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: feature

#1305 HA Fixes
  config/example/admin_ranks.txt
  config/example/admins.txt
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/ship_ai.dm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/overall_jobdefs.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminuscity_2.dmm
Labels: bug, enhancement/QOL

#1300 Covenant Training Pistol
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/icons/Covenant_Projectiles.dmi
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/pistols.dm
Labels: enhancement/QOL, feature

#1316 Ha Tweaks
  html/changelogs/stingray540.yml
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/command.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/flight.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/logistics.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/marines.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/medical.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/naval_security.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/operations.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/pilot.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/tactical.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/technical.dm
  maps/first_contact/maps/UNSC_Heaven_Above/lifts.dm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-1.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-3.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-4.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate_areas.dm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate_overmap.dm
Labels: enhancement/QOL

#1318 HA Map Tweaks
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-3.dmm
Labels: enhancement/QOL

#1321 Heavens Above Map Fixes
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-1.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-3.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-4.dmm
Labels: enhancement/QOL

#1325 Adds Covvie Stunbaton Sprite And Covenant Food
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/icons/Covenant food.dmi
Labels: enhancement/QOL

#1342 Fixes overmap on geminus to address travis failure
  code/modules/halo/structures/stairs_decorative.dm
  code/modules/overmap/sectors.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_city_map.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_2.dmm.orig
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/geminuscity_4.dmm
Labels: bug, mapping

#1341 map fix
  maps/first_contact/maps/faction_bases/Innie_Base.dmm
Labels: bug, enhancement/QOL, mapping, oversight

#1339 Gamemodes and objectives system
  baystation12.dme
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/game_mode_latespawn.dm
  code/game/jobs/job/job.dm
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/misc/payload.dm
  code/modules/overmap/sectors.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/stingray540.yml
  maps/_gamemodes/faction.dm
  maps/_gamemodes/invasion/first_contact.dm
  maps/_gamemodes/invasion/insurrection.dm
  maps/_gamemodes/invasion/invasion.dm
  maps/_gamemodes/invasion/objectives.dm
  maps/_gamemodes/invasion/objectives_cov.dm
  maps/_gamemodes/invasion/objectives_innie.dm
  maps/_gamemodes/invasion/objectives_unsc.dm
  maps/_gamemodes/invasion/oni_cryopod.dm
  maps/first_contact/first_contact.dm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/command.dm
  maps/first_contact/maps/URF Commando Ship/jobs.dm
  maps/first_contact/maps/innie_crew_jobs.dm
  maps/first_contact/maps/odst_crew_jobs.dm
Labels: feature

#1344 Some QOL and QA stuff for objectives in Invasion gamemode
  code/datums/mind.dm
  code/game/jobs/job/job.dm
  code/modules/halo/covenant/ramp.dm
  maps/_gamemodes/faction.dm
  maps/_gamemodes/invasion/invasion.dm
  maps/_gamemodes/invasion/objectives_cov.dm
  maps/_gamemodes/invasion/objectives_innie.dm
  maps/_gamemodes/invasion/objectives_unsc.dm
  maps/first_contact/maps/faction_bases/Covenant_Station.dmm
Labels: bug, enhancement/QOL

#1345 Adds URF gadget sprites
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/icons/URF gadgetry.dmi
Labels: enhancement/QOL

#1343 Perma ship destruction
  baystation12.dme
  code/__defines/superstructure_defines.dm
  code/modules/halo/overmap/hull_segments.dmi
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/overmap/_defines.dm
  code/modules/overmap/hull_segments.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
Labels: feature

#1034 More Discord Integration
  baystation12.dme
  code/controllers/configuration.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/ext_scripts/discord.dm
  code/modules/halo/misc/payload.dm
  html/changelogs/bloxgate-discord-integration.yml
Labels: enhancement/QOL, feature

#1346 Some tweaks to ships and objectives
  maps/_gamemodes/faction.dm
  maps/_gamemodes/invasion/invasion.dm
  maps/first_contact/first_contact.dm
  maps/first_contact/mapdef.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-1.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-3.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-4.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/first_contact/maps/URF Commando Ship/second_deck.dmm
  maps/first_contact/maps/faction_bases/Covenant_Defense.dmm
  maps/first_contact/maps/faction_bases/Covenant_Shuttle.dmm
  maps/first_contact/maps/faction_bases/Covenant_Station.dmm
  maps/first_contact/maps/faction_bases/Human_Defense.dmm
  maps/first_contact/maps/faction_bases/Human_Shuttle.dmm
  maps/first_contact/maps/faction_bases/Human_Station_1.dmm
  maps/first_contact/maps/faction_bases/Human_Station_2.dmm
  maps/first_contact/maps/faction_bases/Innie_Base.dmm
  maps/first_contact/maps/faction_bases/Innie_Shuttle.dmm
  maps/first_contact/maps/kig_yar_pirates/backup/kig_yar_pirates.dmm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/kig_yar_pirates/missionary.dmm
Labels: enhancement/QOL, mapping, overmap

#1347 FC tweaks and fixes
  maps/_gamemodes/invasion/invasion.dm
  maps/_gamemodes/invasion/oni_cryopod.dm
  maps/first_contact/maps/faction_bases/Human_Station_1.dmm
  maps/first_contact/maps/faction_bases/Human_Station_2.dmm
  maps/first_contact/overall_jobdefs.dm
Labels: enhancement/QOL, mapping

#1348 Some major last minute fixes
  maps/first_contact/first_contact.dm
  maps/first_contact/overall_jobdefs.dm
Labels: bug, enhancement/QOL

#1352 re-re does hull segment placement
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-1.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-3.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-4.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
Labels: mapping

#1357 New Energy Barricade Sprites
  code/modules/halo/covenant/energybarricade.dmi
Labels: enhancement/QOL

#1354 Bugfixes and tweaks for objectives and gamemode
  code/game/jobs/job_controller.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/halo/covenant/multitile_airlocks.dm
  code/modules/halo/covenant/slipspace.dm
  code/modules/halo/covenant/slipspace.dmi
  code/modules/halo/machinery/covenant/doors.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/engines/engine.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/bloxgate-discord-integration.yml
  maps/_gamemodes/invasion/invasion.dm
  maps/_gamemodes/invasion/objectives.dm
  maps/_gamemodes/invasion/objectives_cov.dm
  maps/_gamemodes/invasion/objectives_unsc.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/overmap.dm
  maps/first_contact/maps/kig_yar_pirates/overmap.dm
Labels: bug, enhancement/QOL, feature, mapping, overmap

#1361 HA QOL Fixes
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-1.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-3.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-4.dmm
Labels: enhancement/QOL, mapping

#1360 FC spawn and other bugfixes
  code/controllers/voting.dm
  code/controllers/voting/vote_types.dm
  code/game/jobs/job_controller.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/multiz/structures.dm
  maps/_gamemodes/invasion/invasion.dm
  maps/first_contact/maps/faction_bases/faction_spawns.dm
  maps/first_contact/overall_jobdefs.dm
Labels: bug, spawn bug

#1363 Slipspace Drives
  baystation12.dme
  code/modules/halo/covenant/slipspace.dm
  code/modules/halo/icons/machinery/covenant/slipspace_drive.dmi
  code/modules/halo/icons/machinery/slipspace_drive.dmi
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/sounds/slipspace_jump.ogg
  html/changelogs/XO11 - Slipspace Drives.yml
  maps/first_contact/mapdef.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, feature, mapping

#1365 Covenant repair features
  baystation12.dme
  code/modules/halo/covenant/ammo_belt.dm
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/covenant/energybarricade.dmi
  code/modules/halo/covenant/energybarricade_vacuum.dm
  code/modules/halo/covenant/tools.dm
  code/modules/halo/covenant/tools.dmi
  code/modules/halo/turfs/covenant/floor.dm
  code/modules/halo/turfs/covenant/floors.dmi
  code/modules/halo/turfs/covenant/materials.dm
  code/modules/materials/material_recipes.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/XO11 - Slipspace Drives.yml
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
Labels: enhancement/QOL, feature, mapping

#1366 Fixes minor bug with ODST helmets
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst_items.dmi
Labels: bug

#1368 Various fixes
  code/modules/halo/machinery/npc_comms.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/overmap/automated_defense.dm
  maps/_gamemodes/invasion/invasion.dm
  maps/first_contact/maps/faction_bases/Innie_Shuttle.dmm
Labels: bug

#1370 Makes slipspace re-entry create jump alerts
  code/modules/halo/machinery/slipspace_engine.dm
Labels: feature

#1372 Fixes a couple of covenant visual bugs (mostly elites)
  code/modules/halo/covenant/ammo_belt.dm
  code/modules/halo/covenant/tools.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
Labels: bug

#1373 Disables admin log spam from ship combat (1 minute cooldown)
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/covie_pulse_turret.dm
  code/modules/halo/machinery/missile_pods.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/overmap/sectors.dm
Labels: enhancement/QOL

#1374 Bunch Of Things 2, Electric Boogaloo
  code/modules/halo/covenant/Wallocker.dmi
  code/modules/halo/covenant/internals.dmi
  code/modules/halo/covenant/medical.dmi
  code/modules/halo/covenant/slipspace.dmi
  code/modules/halo/turfs/covenant/floors.dmi
  icons/obj/Cryogenic2.dmi
  icons/obj/chemical.dmi
  icons/obj/iv_drip.dmi
  icons/obj/syringe.dmi
  icons/obj/walllocker.dmi
Labels: enhancement/QOL, spriting

#1381 GonTar's Covenant Ship Remastered / Faction Bases update
  html/changelogs/Gontars_Covenant_Ship_Remastered_FactionBases_fix.yml
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/faction_bases/Covenant_Station.dmm
  maps/first_contact/maps/faction_bases/Human_Station_1.dmm
  maps/first_contact/maps/faction_bases/Innie_Base.dmm
Labels: enhancement/QOL, mapping

#1376 Vehicle exit-location fix
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: bug

#1387 Slipspace drive overloading + minor SDV mapfix
  code/modules/halo/covenant/slipspace.dm
  code/modules/halo/covenant/slipspace.dmi
  code/modules/halo/icons/machinery/covenant/slipspace_drive.dmi
  code/modules/halo/icons/machinery/engine2.dmi
  code/modules/halo/icons/machinery/slipspace_drive.dmi
  code/modules/halo/icons/machinery/slipspace_jump_effects.dmi
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/overmap/slipspace_gen.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
Labels: enhancement/QOL, feature

#1390 Fixes innie defense platforms firing on eachother when loaded in
  code/modules/halo/overmap/automated_defense.dm
  maps/first_contact/maps/faction_bases/Innie_Defense.dmm
Labels: bug

#1389 Eluxor MK2 Update for Innie Base
  maps/first_contact/maps/faction_bases/Innie_Base.dmm
Labels: enhancement/QOL, mapping
