Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-02, with the labels that each got.

#1203 Makes covenant weapons irradiate humans
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/projectiles/gun.dm
Labels: feature

#1193 Needle rifle. Hopefully now.
  code/modules/halo/icons/Covenant_Projectiles.dmi
  code/modules/halo/sounds/cov_needlerifle_fire.ogg
  code/modules/halo/sounds/cov_needlerifle_reload.ogg
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/snipers.dm
Labels: enhancement/QOL, feature

#1212 Faction Base Hotfix
  maps/first_contact/overall_jobdefs.dm
Labels: bug

#1213 Faction Bases Hotfix 2
  maps/first_contact/maps/faction_bases/Innie_Base.dmm
  maps/first_contact/maps/faction_bases/faction_spawns.dm
Labels: bug

#1214 actually fixes innie base spawns
  maps/first_contact/maps/faction_bases/faction_spawns.dm
Labels: bug

#1215 Removes blast doors from avarice and bertels
  code/modules/halo/species_items/skirmisher_outfits.dm
  maps/first_contact/maps/Covenant Corvette/outfits.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
Labels: bug

#1218 Increases Automated Defenses Lockon Delay
  code/modules/halo/overmap/automated_defense.dm
Labels: enhancement/QOL

#1219 Energy Projector and Pulse Laser flash radius change
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/machinery/covie_pulse_turret.dm
Labels: enhancement/QOL

#1220 Removes boarding pod sector-landing message
  code/modules/halo/vehicles/boarding_pod.dm
Labels: enhancement/QOL

#1232 Various Faction base related fixes
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/nav_computer.dmi
  code/modules/halo/overmap/umbilicals.dm
  code/modules/overmap/sectors.dm
  html/changelogs/Faction Bases - XO-11.yml
  maps/first_contact/mapdef.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Exoplanet Research/spawn_jobs.dm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/first_contact/maps/URF Commando Ship/includes.dm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/kig_yar_pirates/missionary.dmm
  maps/first_contact/overall_jobdefs.dm
Labels: bug, enhancement/QOL

#1200 Misc mostly Covenant tweaks
  baystation12.dme
  code/__defines/species_lists.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/multi_tile.dm
  code/modules/halo/covenant/crate.dmi
  code/modules/halo/covenant/drone.dm
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/covenant/energybarricade.dmi
  code/modules/halo/covenant/multitile_airlocks.dm
  code/modules/halo/covenant/plasma_drill.dm
  code/modules/halo/covenant/plasma_drill.dmi
  code/modules/halo/covenant/plasmacharge.dm
  code/modules/halo/covenant/weapon_rack.dm
  code/modules/halo/doors/Airlockblastdouble.dmi
  code/modules/halo/doors/Airlockdouble.dmi
  code/modules/halo/doors/Longer Blastdoor.dmi
  code/modules/halo/doors/Secure2x1.dmi
  code/modules/halo/doors/blastdoor.dmi
  code/modules/halo/doors/halo_doors.dm
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/icons/Covenant_Projectiles.dmi
  code/modules/halo/misc/human_roomba.dm
  code/modules/halo/misc/roomba_unsc.dmi
  code/modules/halo/misc/roomba_urf.dmi
  code/modules/halo/species_items/lekgolo.dm
  code/modules/halo/vote/vote.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/bot/cleanbot.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser2.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser3.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/planet_staging.dmm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/backup/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/kig_yar_pirates/missionary.dmm
Labels: Controversial, enhancement/QOL, feature

#1235 Mclovin/Gulag Donor Gear
  code/modules/halo/clothing/ODSTDonorPackage.dmi
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/clothing/urc_commando_variants.dm
  code/modules/halo/clothing/urf_commando.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/machete.dmi
Labels: enhancement/QOL, spriting

#1234 Biofoam stops internal bleeds + a plasma nade duplication fix
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/weapons/covenant/grenades.dm
Labels: bug

#1236 NPC cargo ship groundwork
  baystation12.dme
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/npc_cargo_crate.dm
  code/modules/halo/overmap/npc_cargo_ship.dm
Labels: feature

#1238 Replaces the Kig-Yar Raider with a Kig-Yar Missionary Ship.
  code/modules/halo/overmap/faction_base.dm
  code/modules/halo/overmap/nav_data_computer.dm
  maps/first_contact/maps/kig_yar_pirates/includes.dm
  maps/first_contact/maps/kig_yar_pirates/kig_yar_pirates.dmm
  maps/first_contact/maps/kig_yar_pirates/missionary.dmi
  maps/first_contact/maps/kig_yar_pirates/missionary.dmm
  maps/first_contact/maps/kig_yar_pirates/overmap.dm
Labels: enhancement/QOL

#1239 Adds a missing counter-reset to cargo ship dynamic stocking code
  code/modules/halo/overmap/base_npc_ships.dm
Labels: bug

#1240 Changes the NPC ship z-clearing method
  code/modules/halo/overmap/npc_shipmap_handler.dm
Labels: enhancement/QOL

#1243 decreases HMG and chaingun dispersion
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/chaingun.dm
Labels: enhancement/QOL

#1244 T'voan blood colour fix
  code/modules/halo/species/kig-yar.dm
Labels: bug

#1245 General fixes and additions
  code/modules/halo/structures/gunvendors.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/faction_bases/Innie_Base.dmm
Labels: enhancement/QOL

#1250 missionary ship fix
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/kig_yar_pirates/missionary.dmm
Labels: bug

#1254 various crucial fixes
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
Labels: bug

#1257 NPC ship deload fix
  code/modules/halo/overmap/base_npc_ships.dm
Labels: bug

#1263 Misc bug fixes
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sanshyuum.dm
  code/modules/mob/living/carbon/human/species/species.dm
Labels: bug

#1260 makes NPC ship clearing set to run in background
  code/modules/halo/overmap/npc_shipmap_handler.dm
Labels: bug

#1265 Elite Nerfs (And other small nerfs/buffs)
  code/modules/halo/species/sangheili.dm
  code/modules/halo/vehicles/mongoose.dm
  code/modules/halo/weapons/covenant/melee.dm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
Labels: bug, enhancement/QOL

#1267 Increases plasma rifle fire delay
  code/modules/halo/weapons/covenant/rifles.dm
Labels: enhancement/QOL

#1268 fixed drop pods on insurrection
  code/modules/halo/vehicles/drop_pod.dm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_1.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_2.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
  maps/insurrection/mapdef.dm
Labels: bug, enhancement/QOL, mapping, oversight

#1269 possible comms fix
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_1.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_2.dmm
  maps/insurrection/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
  maps/insurrection/innie_base1.dmm
  maps/insurrection/innie_base2.dmm
  maps/insurrection/innie_base3.dmm
  maps/insurrection/innie_base4.dmm
  maps/insurrection/innie_base_areas.dm
Labels: bug, enhancement/QOL, oversight

#1273 Unggoy tank slot fix
  code/modules/halo/species_items/grunt.dm
Labels: bug, oversight

#1277 Kig-Yar missionary ship power fix
  code/modules/halo/turfs/covenant/floor.dm
  code/modules/halo/turfs/covenant/floors.dmi
  maps/first_contact/maps/kig_yar_pirates/missionary.dmm
Labels: bug, oversight

#1272 Update grenades.dm
  code/modules/halo/weapons/covenant/grenades.dm
Labels: enhancement/QOL

#1282 Misc small bugfixes
  code/modules/halo/covenant/cleaning_drone.dm
  code/modules/halo/species_items/sangheili.dm
Labels: bug

#1286 Job spawn partial rewrite
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job_controller.dm
  code/modules/admin/banjob.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_spawnpoints.dm
  maps/first_contact/first_contact.dm
  maps/first_contact/maps/Admin Planet/backup/surface.dmm
  maps/first_contact/maps/Asteroid Listening Post/backup/Asteroid_2.dmm
  maps/first_contact/maps/UNSC_Bertels/backup/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/backup/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/backup/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Prowler/backup/UNSC_Prowler_Deck_2.dmm
  maps/first_contact/maps/UNSC_Thorin/backup/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/URF Commando Ship/backup/first_deck.dmm
  maps/first_contact/maps/URF Commando Ship/jobs.dm
  maps/first_contact/maps/URF Commando Ship/spawns_jobs.dm
  maps/first_contact/maps/ccv_deliverance_spawns.dm
  maps/first_contact/maps/civ_crew_jobs.dm
  maps/first_contact/maps/faction_bases/backup/Covenant_Station.dmm
  maps/first_contact/maps/faction_bases/faction_spawns.dm
  maps/first_contact/maps/innie_crew_jobs.dm
  maps/first_contact/maps/medic_crew_jobs.dm
  maps/first_contact/maps/odst_crew_jobs.dm
  maps/first_contact/overall_jobdefs.dm
  maps/first_contact/overall_overmap.dm
  maps/overmap_ships/CCV_Comet.dm
  maps/overmap_ships/CCV_Deliverance.dm
  maps/overmap_ships/CCV_Slow_But_Steady.dm
  maps/overmap_ships/CCV_Star.dm
  maps/overmap_ships/_om_ship_areas_definition.dm
  maps/overmap_ships/nh_overmap.dm
  maps/overmap_ships/om_ship_areas.dm
  maps/~mapsystem/maps.dm
Labels: bug, enhancement/QOL

#1291 Fixes sentient, burrowing, fast growing trees on the admin planet
  maps/first_contact/maps/Admin Planet/areas.dm
  maps/first_contact/maps/Admin Planet/surface.dmm
Labels: bug, mapping

#1293 Adds Plasma Cannon & Needle Cannon Sprites
  code/modules/halo/icons/missile.dmi
Labels: enhancement/QOL, spriting

#1296 Moves many features of the MAC to variables instead of hardcoded values
  code/modules/halo/machinery/MAC.dm
Labels: enhancement/QOL
