Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-05, with the labels that each got.

#1479 More DAV lights
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/weapons/covenant/grenades.dm
  maps/first_contact/maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
Labels: feature, mapping

#1480 adds warthog variant destroyed sprites
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/vehicles/GCPD_Warthog.dmi
  code/modules/halo/vehicles/finalwarthog-chaingun.dmi
  code/modules/halo/vehicles/finalwarthog-turretless.dmi
  code/modules/halo/vehicles/finalwarthog.dmi
Labels: enhancement/QOL, spriting

#1481 HA -> Bertels Replace
  maps/_gamemodes/invasion/invasion.dm
  maps/first_contact/first_contact.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/areas.dm
  maps/first_contact/maps/UNSC_Bertels/backup/UNSC_Bertels_Deck_3.dmm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_2.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
  maps/first_contact/maps/faction_bases/faction_spawns.dm
  maps/first_contact/overall_jobdefs.dm
Labels: feature, mapping

#1482 Various changes
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/covenant/ammo.dm
Labels: feature

#1487 Honour guards + Prophets
  code/__defines/species_lists.dm
  code/modules/halo/icons/species/Sangheili_Combat_Harness.dmi
  code/modules/halo/misc/armourspecials/gear_defs.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/halo/species_items/sanshyuum.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  maps/ccs_battlecruiser/jobs/prophet.dm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/faction_bases/faction_spawns.dm
  maps/first_contact/overall_jobdefs.dm
Labels: enhancement/QOL, feature

#1491 applies dispersion to lmg base code
  code/modules/halo/weapons/lmg.dm
Labels: bug

#1490 stops simplemob stairdancing
  code/modules/halo/vehicles/spirit.dmi
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: bug, feature

#1494 Donor stuff
  code/modules/halo/clothing/commandopack.dmi
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/clothing/urc_commando_variants.dm
  code/modules/halo/clothing/urf_commando.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/machete.dmi
Labels: enhancement/QOL

#1496 disables ODP map loading
  code/modules/halo/machinery/boarding_beacon_launcher.dm
  code/modules/halo/overmap/automated_defense.dm
Labels: enhancement/QOL, feature

#1497 fixes control_tag setting on bertels global deck gun control
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
Labels: enhancement/QOL, feature

#1499 glassing changes
  code/modules/halo/overmap/weapons/Energy_projector.dm
  maps/_gamemodes/invasion/objectives_cov.dm
Labels: feature

#1501 Updates Covvie Nav Sprite
  code/modules/halo/icons/machinery/covenant/consoles.dmi
Labels: enhancement/QOL, spriting

#1502 Many changes
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/weapons/overmap_projectile.dm
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/wraith.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/grenades.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: enhancement/QOL, feature, mapping

#1504 Fuel rod launcher
  baystation12.dme
  code/game/objects/explosion.dm
  code/modules/halo/icons/fuel_rod_cannon.dmi
  code/modules/halo/sounds/fuel_rod_fire.ogg
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/launchers.dm
  code/modules/projectiles/gun.dm
Labels: feature

#1503 Bertels NavSec gear
  baystation12.dme
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/halo/clothing/closets.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/weapons/melee.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
Labels: enhancement/QOL, feature, mapping

#1507 Fixes glassing and removes the long-range slipspace drive
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  maps/first_contact/maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
Labels: bug

#1515 Elite tweaks
  code/modules/halo/species_items/sangheili.dm
Labels: enhancement/QOL

#1508 ship-v-ship energy projector explosion nerf
  code/modules/halo/overmap/weapons/Energy_projector.dm
Labels: enhancement/QOL

#1517 Minor species changes
  baystation12.dme
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/sanshyuum.dm
Labels: feature

#1518 Vehicle headlights
  code/modules/halo/vehicles/SOEIV.dm
  code/modules/halo/vehicles/boarding_pod.dm
  code/modules/halo/vehicles/bull.dm
  code/modules/halo/vehicles/cobra.dm
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/mongoose.dm
  code/modules/halo/vehicles/pelican.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/shadow.dm
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/warthog.dm
  code/modules/halo/vehicles/wraith.dm
Labels: enhancement/QOL, feature

#1416 Send a message to the general discord channel on server startup
  code/modules/ext_scripts/discord.dm
Labels: enhancement/QOL

#1519 New fax departments
  maps/first_contact/mapdef.dm
Labels: enhancement/QOL, feature

#1520 Various hotfixes
  code/_global_vars/configuration.dm
  code/_helpers/time.dm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: enhancement/QOL, mapping, oversight

#1521 Stop cyro from killing people if used properly
  code/__defines/chemistry.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  html/changelogs/cryofix.yml
Labels: bug, enhancement/QOL

#1526 fixes glassed ks7 mapfile
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2_Glassed.dmm
Labels: bug, mapping

#1528 random job assignment checks whitelist
  code/game/jobs/job_controller.dm
  maps/first_contact/maps/Covenant Corvette/overmap.dm
Labels: bug

#1524 Tactical HUD remote viewing
  baystation12.dme
  code/modules/clothing/head/helmet.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/kigyar_ranger.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/pilot.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/squads/camera_console.dmi
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/squads/hud_glasses.dmi
  code/modules/halo/squads/squad-waypoint-controller.dm
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/squads/squad_camera_console.dm
  code/modules/halo/squads/waypoint_manager.dmi
  code/modules/halo/vehicles/bull.dm
  code/modules/halo/vehicles/vehiclebase.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/cryofix.yml
  maps/first_contact/maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, feature, mapping

#1529 Donor stuff
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
Labels: enhancement/QOL

#1532 Monitors, Sentinels, Halos Oh My!
  code/modules/halo/Forerunner/Halo.dmi
  code/modules/halo/Forerunner/Monitor.dmi
  code/modules/halo/Forerunner/Sentinel.dmi
  maps/first_contact/maps/innie_crew_jobs.dm
Labels: enhancement/QOL, spriting

#1539 Removes Vagina From Covvie Pods
  code/modules/halo/vehicles/covenant_pods.dmi
Labels: enhancement/QOL, oversight, spriting

#1536 Minor Changes
  code/game/objects/effects/spiders.dm
  code/modules/halo/clothing/kigyar_ranger.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species_items/grunt_outfits.dm
  code/modules/halo/squads/squad_camera_console.dm
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/shadow.dm
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/wraith.dm
  code/modules/halo/weapons/autoturret.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  maps/first_contact/maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1_Glassed.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2_Glassed.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
Labels: enhancement/QOL, feature, mapping

#1541 War crimes
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/items/weapons/flamethrower.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/ZAS/Fire.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/effects/fire.dmi
  icons/obj/flamethrower.dmi
Labels: bug, feature

#1544 Remove Payload Arming/Detonation Discord Pings
  code/modules/ext_scripts/discord.dm
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/misc/payload.dm
Labels: enhancement/QOL

#1545 Moves the UNSC Base's nuke
  maps/first_contact/maps/faction_bases/Human_Station_1.dmm
Labels: enhancement/QOL, oversight

#1542 ONI Base - Swaps the jukebox for a cigarette vendor.
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
Labels: enhancement/QOL, mapping

#1546 Buildable landmines, Innie RGL12 and nitroglycerin chem mix
  baystation12.dme
  code/game/objects/effects/chem/foam.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/igniter.dm
  code/modules/halo/weapons/explosives.dm
  code/modules/halo/weapons/icons/explosives.dmi
  code/modules/halo/weapons/landmine.dm
  code/modules/halo/weapons/landmine_construct.dm
  code/modules/halo/weapons/landmine_presets.dm
  code/modules/halo/weapons/launchers.dm
  code/modules/materials/material_recipes.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Recipes.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: feature

#1548 Fixes area tile
  maps/first_contact/maps/faction_bases/Human_Station_1.dmm
Labels: mapping, oversight

#1550 Adds additional UNSC Marine Job Title - Combat Technician
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
Labels: enhancement/QOL

#1527 Cryo Tweaks
  baystation12.dme
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/chemicals/recipes.dm
  code/modules/halo/machinery/medical/thermopod.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  html/changelogs/bloxgate - Cryo.yml
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  nano/templates/thermopod.tmpl
Labels: enhancement/QOL, feature, mapping

#1553 Flamer tweaks
  code/game/objects/items/weapons/flamethrower.dm
  code/modules/ZAS/Fire.dm
  code/modules/reagents/Chemistry-Machinery.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/bdpuffy420urfarmorupdate.yml
Labels: bug, enhancement/QOL

#1559 Fixes Mclovin's donator gear.
  code/modules/halo/clothing/doneritems.dm
Labels: enhancement/QOL

#1556 Send more of ahelp conversations to Discord
  code/modules/admin/verbs/adminpm.dm
Labels: enhancement/QOL, feature

#1561 Fix line endings in Human Station level 1
  maps/first_contact/maps/faction_bases/Human_Station_1.dmm
Labels: mapping

#1560 Attempt to fix helm machine controller hangs
  code/modules/overmap/ships/computers/helm.dm
Labels: bug, overmap

#1563 Fixes the generate_switchable_maps.sh script
  generate_switchable_maps.sh
Labels: enhancement/QOL

#1568 Adds an extra null-value check to waypoint manager code
  code/modules/halo/squads/squad-waypoint-manager.dm
Labels: bug

#1569 Parry changes
  code/game/objects/weapons.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/weapons/covenant/melee.dm
Labels: enhancement/QOL, feature

#1567 The Ultra Strikes Back
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/innie_crew_jobs.dm
Labels: enhancement/QOL

#1572 Allows the option to disable error logging when unable to load a file
  code/_helpers/files.dm
  code/_helpers/type2type.dm
  code/game/jobs/whitelist.dm
Labels: enhancement/QOL

#1576 Readds Glassed KS7
  code/modules/halo/overmap/nav_data_computer.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/ks7_elmsville/ks7_elmsville.dm
  maps/ks7_elmsville/overmap.dm
Labels: feature, oversight

#1578 Fix for a faction tieing with itself in points
  maps/_gamemodes/invasion/gamemode.dm
Labels: bug

#1573 Moderate factions cleanup
  baystation12.dme
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/halo/overmap/automated_defense.dm
  code/modules/overmap/sectors.dm
  maps/Covenant Corvette/overmap.dm
  maps/Exoplanet Research/overmap.dm
  maps/UNSC_Bertels/overmap.dm
  maps/_gamemodes/faction.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/_gamemodes/invasion/_includes_ks7elmsville.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/objectives_cov.dm
  maps/faction_bases/Human_Station_1.dmm
  maps/faction_bases/Human_Station_2.dmm
  maps/faction_bases/base_areas.dm
  maps/faction_bases/faction_base.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/ks7_elmsville/overmap.dm
Labels: bug, enhancement/QOL

#1580 Slayer fixes
  maps/_gamemodes/teamslayer_covenantvspartan.dm
  maps/slayer/slayer_outfits.dm
Labels: bug

#1582 Makes overmap projectiles use their custom reload delays instead of the base 2 second delay
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: bug, enhancement/QOL

#1583 equips shuttles with slipspace drives
  maps/faction_bases/Covenant_Shuttle.dmm
  maps/faction_bases/Human_Shuttle.dmm
  maps/faction_bases/Innie_Shuttle.dmm
Labels: enhancement/QOL

#1584 Fax fix
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/URF Commando Ship/first_deck.dmm
  maps/faction_bases/Covenant_Station.dmm
  maps/faction_bases/Human_Station_1.dmm
  maps/faction_bases/Innie_Base.dmm
Labels: enhancement/QOL

#1586 nullobj fix
  maps/faction_bases/Covenant_Station.dmm
  maps/faction_bases/Human_Station_1.dmm
  maps/faction_bases/Innie_Base.dmm
  maps/faction_bases/backup/Covenant_Station.dmm
Labels: bug, mapping
