Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-04, with the labels that each got.

#1393 Flood Infestor Revivification
  code/modules/halo/flood/flood.dm
  code/modules/halo/machinery/slipspace_engine.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  html/changelogs/xo-11 - flood_infestor_features.yml
Labels: feature

#1392 Ship Scanning Consoles
  baystation12.dme
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/machinery/scanning_console.dm
  code/modules/halo/machinery/ship_scanning_console.dmi
  code/modules/overmap/sectors.dm
  code/modules/overmap/targeting_datum.dm
  html/changelogs/XO-11 - Ship Scanning Consoles.yml
  maps/first_contact/maps/Asteroid Listening Post/overmap.dm
  maps/first_contact/maps/Exoplanet Icy/overmap.dm
  maps/first_contact/maps/Exoplanet Research/overmap.dm
  maps/geminus_city/geminus_city_overmap.dm
Labels: feature

#1396 makes flood combat forms revive only once
  code/modules/halo/flood/flood.dm
Labels: enhancement/QOL

#1400 Bugfixes
  code/modules/emotes/definitions/audible.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/projectiles/gun.dm
Labels: bug

#1401 Lowers amount of max flood simplemobs in stranded
  maps/_gamemodes/stranded/mode_stranded_start.dm
Labels: enhancement/QOL

#1405 GC Additions
  maps/geminus_city/backup/geminuscity_2.dmm
Labels: enhancement/QOL, mapping

#1406 Flood form revivification fixes
  code/modules/halo/flood/flood.dm
Labels: bug

#1408 Adds Supply Pods, Fixes Covvie Pods
  code/modules/halo/structures/supply_pods.dmi
  code/modules/halo/vehicles/covenant_pods.dmi
Labels: enhancement/QOL, spriting

#1410 Disable autohealing brain damage
  code/modules/organs/internal/brain.dm
Labels: Do Not Merge, bug

#1411 moves shipmaphandler maxz caching
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/overmap/sectors.dm
Labels: bug

#1419 prone system changes
  code/game/objects/items.dm
  code/modules/halo/weapons/charged.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/energy.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/mob/inventory.dm
  code/modules/mob/mob.dm
Labels: enhancement/QOL

#1420 plasnade rebalance
  code/modules/halo/weapons/covenant/grenades.dm
Labels: enhancement/QOL

#1421 simplemob painscreams and death-sounds
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: enhancement/QOL

#1423 Covie Pod fix and HA job skimming
  code/modules/halo/vehicles/boarding_pod.dm
  code/modules/halo/vehicles/escape_pods.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/command.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/flight.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/logistics.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/operations.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/pilot.dm
  maps/first_contact/maps/UNSC_Heaven_Above/jobs/tactical.dm
Labels: enhancement/QOL, oversight

#1424 Covvie nav, URF gadgets, food nipple sprites
  code/modules/halo/covenant/food_nipple.dmi
  code/modules/halo/icons/machinery/covenant/consoles.dmi
  code/modules/halo/weapons/icons/URF gadgetry.dmi
Labels: enhancement/QOL, spriting

#1426 Update NPC speech upate
  code/modules/halo/NPC/NPC_types/colonist.dm
  code/modules/halo/NPC/speech_response.dm
Labels: enhancement/QOL

#1428 Adds SoE Stuff, Adjusts Gadgets
  code/modules/halo/weapons/icons/URF gadgetry.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
Labels: enhancement/QOL, feature, needs changelog, spriting

#1427 Vehicle Additions
  baystation12.dme
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/explosion.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/pilot.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/sounds/scorp_cannon_fire.ogg
  code/modules/halo/sounds/scorp_machinegun_fire.ogg
  code/modules/halo/sounds/warthog_machinegun_fire.ogg
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/skirmisher_gauntlets.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/headrep_base.dmi
  code/modules/halo/vehicles/mongoose.dm
  code/modules/halo/vehicles/pelican.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/vehicles/warthog.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/projectiles/guns/launcher/rocket.dm
  html/changelogs/XO-11 - Vehicle Additions.yml
Labels: enhancement/QOL, feature

#1432 Adds the Covenant "Shadow"
  baystation12.dme
  code/modules/halo/clothing/odst.dm
  code/modules/halo/sounds/shadow_cannon_fire.ogg
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/shadow.dm
  code/modules/halo/vehicles/shadow.dmi
  code/modules/halo/vehicles/spirit.dmi
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
Labels: enhancement/QOL, feature

#1430 VT9 & KS7 map tweaks
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
Labels: enhancement/QOL, mapping

#1425 BR55 addition
  code/game/objects/items/stacks/medical.dm
  code/modules/halo/icons/attachments/attachments_general.dmi
  code/modules/halo/icons/attachments/barrel.dmi
  code/modules/halo/icons/attachments/sights.dmi
  code/modules/halo/icons/objs/halohumanmisc.dmi
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/launchers.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/attachments/barrel.dm
  code/modules/projectiles/attachments/general_attachments.dm
  code/modules/projectiles/attachments/sights.dm
Labels: enhancement/QOL, feature

#1435 potential vehicle-explode-into-nullspace fix
  code/modules/halo/sounds/ghost_move.ogg
  code/modules/halo/sounds/scorp_move.ogg
  code/modules/halo/sounds/warthog_move.ogg
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/vehicles/warthog.dm
  code/modules/mob/mob_movement.dm
Labels: bug

#1434 Adds Plasma Turret sprites
  code/modules/halo/weapons/turrets/deploy_kit_items.dmi
  code/modules/halo/weapons/turrets/turret_items.dmi
  code/modules/halo/weapons/turrets/turrets_covenant.dmi
Labels: enhancement/QOL, spriting

#1440 Small fixes
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/ammo.dm
Labels: enhancement/QOL, oversight

#1443 Sangheili heal nerf
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/weapons/covenant/ammo.dm
Labels: enhancement/QOL

#1446 Zeal & Colossus buff
  code/modules/halo/clothing/insurrectionists.dm
Labels: enhancement/QOL

#1449 More NPC lines
  code/modules/halo/NPC/NPC_types/colonist.dm
Labels: enhancement/QOL

#1451 Plasma torpedoes
  .travis.yml
  baystation12.dme
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/deck_missile_pod.dmi
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasma_torpedo.dmi
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/sounds/plasma_torpedoes_fire.ogg
  code/modules/halo/sounds/plasma_torpedoes_impact.ogg
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/turfs/covenant/materials.dm
  code/modules/halo/weapons/ammo.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/areas.dm
  maps/first_contact/maps/Covenant Corvette/overmap.dm
Labels: enhancement/QOL, feature

#1452 Adds Cobra Sprites (Deployed & Undeployed)
  code/modules/halo/vehicles/Cobra.dmi
Labels: enhancement/QOL, spriting

#1453 Flood Infestor Forms: Airlock Infestation
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/modules/halo/flood/flood.dm
  code/modules/mob/mob_movement.dm
Labels: enhancement/QOL, feature

#1454 rebalance spartan regen
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/spartan.dm
Labels: enhancement/QOL

#1455 Adds even more vehicles
  baystation12.dme
  code/_onclick/item_attack.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/sounds/ghost_move.ogg
  code/modules/halo/sounds/warthog_move.ogg
  code/modules/halo/sounds/wraith_cannon_fire.ogg
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/Bull.dmi
  code/modules/halo/vehicles/Cobra.dmi
  code/modules/halo/vehicles/Wraith.dmi
  code/modules/halo/vehicles/bull.dm
  code/modules/halo/vehicles/cobra.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/pelican.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/shadow.dm
  code/modules/halo/vehicles/spirit.dmi
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/vehicles/warthog.dm
  code/modules/halo/vehicles/wraith.dm
  code/modules/halo/weapons/rifles.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Gontars_Covenant_Ship_Fixes.yml
  html/changelogs/XO-11 - Ship Scanning Consoles.yml
  html/changelogs/XO-11 - Vehicle Additions.yml
  html/changelogs/xo-11 - flood_infestor_features.yml
Labels: enhancement/QOL, feature

#1460 Small Weapon Fixes
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/projectiles/beams.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, feature

#1462 Vehicle Repair System
  code/modules/halo/clothing/armor_repair/repair_bench.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/vehicles/Bull.dmi
  code/modules/halo/vehicles/Cobra.dmi
  code/modules/halo/vehicles/Scorpion.dmi
  code/modules/halo/vehicles/Wraith.dmi
  code/modules/halo/vehicles/cobra.dm
  code/modules/halo/vehicles/finalwarthog-chaingun.dmi
  code/modules/halo/vehicles/ghost.dm
  code/modules/halo/vehicles/ghost.dmi
  code/modules/halo/vehicles/mongoose.dmi
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/shadow.dm
  code/modules/halo/vehicles/shadow.dmi
  code/modules/halo/vehicles/spirit.dmi
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/vehicles/wraith.dm
  code/modules/halo/weapons/ammo.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: enhancement/QOL, feature

#1464 sprite fix
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/rifles.dm
Labels: enhancement/QOL

#1465 General Bugfixes
  baystation12.dme
  code/modules/halo/misc/co_ord_console.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/shuttles/pelican.dmi
  code/modules/halo/vehicles/cobra.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/wraith.dm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Icy/overmap.dm
Labels: bug, enhancement/QOL, feature

#1466 Destroyed Vehicles now automatically cause occupants to be hit by bullets
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: enhancement/QOL, feature

#1468 Drop pod beacon fix + other minor changes
  code/modules/halo/vehicles/cobra.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/vehicles/scorpion.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/weapons/drop_pod_beacon.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
Labels: bug, feature

#1469 Stingray's (not so) grand return
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/smg.dm
  code/modules/projectiles/gun.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-2.dmm
  maps/first_contact/maps/UNSC_Heaven_Above/unsc_frigate-4.dmm
  maps/first_contact/maps/odst_crew_jobs.dm
Labels: enhancement/QOL

#1470 KS7 & Thorn Update
  maps/first_contact/maps/Exoplanet Icy/KS7_535_1.dmm
  maps/first_contact/maps/Exoplanet Icy/KS7_535_2.dmm
  maps/first_contact/maps/Exoplanet Icy/spawns_jobs.dm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, mapping

#1472 Warthog Variants
  code/modules/halo/vehicles/warthog.dm
Labels: feature

#1476 New covenant ship map
  code/modules/halo/clothing/marine.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  maps/first_contact/maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/includes.dm
Labels: feature, mapping

#1477 Missing DAV lights
  maps/first_contact/maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
Labels: feature, mapping
