Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-08, with the labels that each got.

#1746 needler now respects armour and shield blocks
  code/modules/halo/weapons/covenant/ammo.dm
Labels: bug

#1600 [EXPERIMENT] Fix molar heat capacities in XGM Gases
  code/modules/xgm/gases.dm
Labels: Do Not Merge, bug

#1749 potential npc ship cross-faction pacifism fix
  code/modules/halo/overmap/combat_npc_ship.dm
Labels: bug

#1747 VT9 also has a geminus co-ord console
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/geminus_city/geminus_city_overmap.dm
Labels: enhancement/QOL

#1748 Admin Verb to spawn an "ERT Shuttle"
  baystation12.dme
  code/modules/halo/misc/admin_ert_ship_spawn.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/slipspace_engine.dm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/geminus_city/invasion_geminus.dm
  maps/npc_ships/CCV_Comet.dm
  maps/npc_ships/CCV_Comet.dmm
  maps/npc_ships/CCV_Deliverance.dm
  maps/npc_ships/CCV_Deliverance.dmm
  maps/npc_ships/CCV_Slow_But_Steady.dm
  maps/npc_ships/CCV_Slow_But_Steady.dmm
  maps/npc_ships/CCV_Star.dm
  maps/npc_ships/CCV_Star.dmm
  maps/npc_ships/CMV_Elivagar.dmm
  maps/npc_ships/Niflheim.dmm
  maps/npc_ships/UNSC_Corvette.dmm
  maps/npc_ships/_om_ship_areas_definition.dm
  maps/npc_ships/backup/CCV_Star.dmm
  maps/npc_ships/civ_crew_jobs.dm
  maps/npc_ships/civ_crew_spawns.dm
  maps/npc_ships/civhauler.dmm
  maps/npc_ships/deliverance.dmi
  maps/npc_ships/ert_ship_covenant.dmm
  maps/npc_ships/ert_ship_human.dmm
  maps/npc_ships/freighter.dmi
  maps/npc_ships/kigyar_missionary.dmm
  maps/npc_ships/medic_crew_jobs.dm
  maps/npc_ships/medic_crew_spawns.dm
  maps/npc_ships/nh_overmap.dm
  maps/npc_ships/om_ship_areas.dm
  maps/npc_ships/outfits.dm
  maps/npc_ships/slowbutsteady.dmi
Labels: bug, enhancement/QOL, feature

#1752 ERT ship req_access fixes
  maps/npc_ships/ert_ship_human.dmm
Labels: bug

#1753 vehicle proj-hit message
  code/modules/halo/vehicles/vehiclebase.dm
Labels: enhancement/QOL

#1762 npc combat ship null runtime fix
  code/modules/halo/overmap/combat_npc_ship.dm
Labels: bug

#1759 Fixes cables not connecting
  maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
Labels: enhancement/QOL, mapping, oversight

#1750 Update SOE
  code/modules/halo/clothing/head.dmi
  code/modules/halo/clothing/urc_commando_variants.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/clothing/urf_commando.dmi
  code/modules/halo/clothing/urf_commando_sets.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  maps/URF Commando Ship/jobs.dm
  maps/URF Commando Ship/outfits.dm
Labels: enhancement/QOL, feature, spriting

#1764 Kozi's autosurgeon sprite update
  code/modules/halo/machinery/autosurgeon/autosurgeon.dmi
Labels: enhancement/QOL, spriting

#1758 npc overmind comms messages
  code/modules/halo/NPC/npc_overmind.dm
Labels: enhancement/QOL

#1763 basic NPC fleet work
  baystation12.dme
  code/modules/halo/misc/admin_fleet_spawn.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_fleets.dm
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/overmap/ships/ship.dm
Labels: enhancement/QOL, feature

#1760 allows announcer-type radios to ignore the range check in recieve_range() proc
  code/game/objects/items/devices/radio/radio.dm
Labels: enhancement/QOL

#1765 NPC ship hotfix
  code/modules/halo/factions/_faction.dm
  code/modules/halo/overmap/base_npc_ships.dm
Labels: bug

#1761 capture node defenders
  baystation12.dme
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/misc/placeholder_capture_mobs.dm
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, feature

#1766 Adds simple mobs
  code/modules/halo/icons/mobs/defense_mobs.dmi
Labels: enhancement/QOL, feature

#1769 Faction defender mob update
  baystation12.dme
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/misc/capture_node_mobs.dm
  code/modules/halo/misc/placeholder_capture_mobs.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
Labels: enhancement/QOL, feature

#1770 Small Innie armor fixes
  code/modules/halo/clothing/inniearmor.dmi
Labels: enhancement/QOL

#1767 NPC fleet tweaks
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_fleets.dm
Labels: bug, enhancement/QOL

#1768 DAV Overmap Icons updated
  maps/Covenant Corvette/Corvette2.dmi
  maps/Covenant Corvette/SDV.dmi
Labels: enhancement/QOL

#1771 capture point defender hotfix
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/misc/capture_node_mobs.dm
Labels: bug, oversight

#1738 Autosurgeon fixes
  code/modules/halo/machinery/autosurgeon/firstaid.dm
  code/modules/halo/machinery/autosurgeon/surgery_external.dm
  code/modules/halo/machinery/autosurgeon/surgery_internal.dm
  code/modules/mob/mob.dm
  code/modules/organs/external/_external.dm
  maps/geminus_city/areas.dm
Labels: bug, enhancement/QOL

#1777 Adds a player hud for innies
  code/game/antagonist/antagonist_add.dm
  icons/mob/hud.dmi
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/innie_hud.dm
  maps/geminus_city/innie_jobs.dm
Labels: feature

#1778 Hostile Mobs target Vehicles
  code/_onclick/adjacent.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: enhancement/QOL

#1780 More incendiary weapon fixes
  baystation12.dme
  code/__defines/atmos.dm
  code/_helpers/unsorted.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/items/weapons/flamethrower.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/modules/ZAS/Fire.dm
  code/modules/ZAS/Fire_simple.dm
  code/modules/halo/NPC/NPC_types/colonist.dm
  code/modules/halo/NPC/npc.dm
  code/modules/halo/NPC/npc_damage.dm
  code/modules/halo/NPC/npc_interact.dm
  code/modules/halo/weapons/landmine_presets.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: bug, enhancement/QOL, feature

#1776 Riley Kitten Donor Arrives
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
Labels: enhancement/QOL
