Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-11, with the labels that each got.

#1866 plasrepeater ammo tweak
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/covenant/lmg.dm
Labels: enhancement/QOL, feature

#1867 Energy Projector Refactor
  code/modules/halo/overmap/weapons/Energy_projector.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/areas.dm
Labels: enhancement/QOL, feature

#1868 nerfs the effect of emp on doors
  code/game/machinery/doors/airlock.dm
Labels: enhancement/QOL

#1869 Laser designator tweaks
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/overmap/weapons/laser_designator.dm
  code/modules/halo/overmap/weapons/laser_designator.dmi
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/squads/waypoints.dmi
Labels: enhancement/QOL, feature

#1870 Tweaks to energy weapon stats
  code/modules/clothing/suits/armor.dm
  code/modules/organs/external/_external_damage.dm
Labels: enhancement/QOL

#1873 Fixes geminus failing to appear in co-ords lists.
  code/modules/halo/overmap/nav_data_computer.dm
Labels: bug, enhancement/QOL

#1872 Radio jammer implement
  baystation12.dme
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/telecomms_jammers.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/comms/commsitems.dm
  code/modules/halo/comms/jammers.dmi
  code/modules/halo/comms/telecomms_jammers.dm
  code/modules/halo/overmap/combat_npc_ship.dm
Labels: enhancement/QOL, feature

#1865 ODST MedHUD
  code/modules/halo/clothing/odst.dm
Labels: enhancement/QOL

#1874 Adds Radio Jammers to the maps.
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/geminus_city/geminus_innie_base.dmm
Labels: enhancement/QOL

#1875 walk sound tweaks
  code/modules/clothing/clothing.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/sounds/walk_sounds/generic_walk.ogg
  code/modules/halo/sounds/walk_sounds/marine_boots.ogg
Labels: enhancement/QOL, feature

#1878 elevation fixes
  code/game/machinery/OpTable.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/effects/chem/foam.dm
  code/game/objects/structures/alien/alien.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/ZAS/Atom.dm
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/structures/sandbag.dm
  code/modules/halo/structures/tanktrap.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/structures.dm
  code/modules/tables/interactions.dm
  maps/unsc_achlys/achlys_objects.dm
Labels: bug

#1877 New DMR +Attachments
  code/modules/halo/icons/attachments/attachments_general.dmi
  code/modules/halo/icons/attachments/barrel.dmi
  code/modules/halo/icons/attachments/sights.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/snipers.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/attachments/barrel.dm
  code/modules/projectiles/attachments/secondary_weapon.dm
  code/modules/projectiles/attachments/sights.dm
Labels: enhancement/QOL, feature

#1879 Various minor fixes
  code/game/objects/effects/bump_teleporter.dm
  maps/geminus_city/x52_outfits.dm
Labels: bug, enhancement/QOL

#1881 Brutes
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/halo/sounds/species_pain_screams/brutescream1.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream2.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream3.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream4.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream5.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream6.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream7.ogg
  code/modules/halo/sounds/species_pain_screams/brutescream8.ogg
  code/modules/halo/species/brutes.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/jiralhanae_outfit.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/projectiles/projectile.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/CRS_Unyielding_Transgression/spawns_jobs.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL, feature

#1884 Donator stuff
  code/modules/halo/clothing/ODSTDonorPackage.dmi
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL

#1883 Argentum Update
  code/modules/halo/weapons/snipers.dm
  code/modules/projectiles/attachment_profiles.dm
  maps/SOE_Argentum/argentum.dmm
Labels: bug, enhancement/QOL

#1882 Tweaks
  code/modules/halo/species_items/sangheili_outfits.dm
Labels: enhancement/QOL, feature

#1885 Pain mod move
  code/modules/halo/clothing/marine.dm
  code/modules/halo/covenant/ammo_belt.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/species/species.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/jobs.dm
Labels: bug, enhancement/QOL

#1886 updates the LB's map bounds
  maps/UNSC_Halberd_Class/overmap.dm
Labels: bug

#1888 Various fixes and additions
  code/game/objects/items.dm
  code/game/sound.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_fleets.dm
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/dual_wielding.dm
  code/modules/mob/inventory.dm
  code/modules/overmap/ships/ship.dm
Labels: bug, enhancement/QOL

#1889 More Attachments and various fixes to them.
  code/modules/halo/icons/attachments/attachments_general.dmi
  code/modules/halo/icons/attachments/barrel.dmi
  code/modules/halo/icons/attachments/sights.dmi
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/attachment_system.dm
  code/modules/projectiles/attachments/barrel.dm
  code/modules/projectiles/attachments/general_attachments.dm
  code/modules/projectiles/attachments/lights.dm
  code/modules/projectiles/attachments/secondary_weapon.dm
  code/modules/projectiles/attachments/sights.dm
  maps/SOE_Argentum/argentum.dmm
Labels: enhancement/QOL, feature

#1890 Npc ship combat tweaks
  code/modules/halo/icons/overmap/Cruiser.dmi
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_fleets.dm
  maps/_gamemodes/invasion/gamemode.dm
Labels: bug, enhancement/QOL

#1891 Argentum sprite fix + hullsegments
  maps/SOE_Argentum/argentum.dmi
  maps/SOE_Argentum/argentum.dmm
Labels: enhancement/QOL

#1892 makes the automac program use get_faction not .faction
  code/modules/halo/overmap/weapons/auto_mac_program.dm
Labels: bug

#1894 Covenant Tweaks
  code/modules/halo/covenant/backpack.dmi
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/species_items/sangheili.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL

#1895 Misc Fixes
  code/modules/halo/icons/attachments/attachments_general.dmi
  code/modules/halo/icons/attachments/sights.dmi
  code/modules/halo/machinery/boarding_beacon_launcher.dm
  code/modules/halo/misc/capture_node_mobs.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/attachments/sights.dm
Labels: enhancement/QOL

#1896 Minor huragok changes
  code/modules/halo/covenant/grav_bed.dmi
  code/modules/halo/covenant/huragok/huragok_items.dm
  code/modules/halo/covenant/huragok/huragok_modules.dm
  code/modules/halo/covenant/huragok/items.dmi
Labels: enhancement/QOL

#1897 Various changes and fixes
  code/modules/halo/overmap/shipyards.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/species_items/lekgolo.dm
  code/modules/halo/species_items/lekgolo_defence.dm
  code/modules/halo/weapons/launchers.dm
  code/modules/projectiles/gun.dm
Labels: bug, enhancement/QOL

#1899 Donator Edits
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL

#1902 Neural lace rejuv
  code/modules/mob/living/carbon/human/species/species.dm
Labels: bug

#1903 missile homing
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/weapons/covenant/ammo.dm
Labels: enhancement/QOL, feature

#1906 some minor changes
  code/game/objects/structures/girders.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: bug, enhancement/QOL

#1901 Unarmed changes
  baystation12.dme
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/orion.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/mob/living/carbon/human/unarmed_attack.dm
Labels: enhancement/QOL, feature

#1910 Fix a runtime caused by null variables in the attachment system
  code/modules/projectiles/attachment_system.dm
  code/modules/projectiles/gun.dm
Labels: bug

#1909 Spartans
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/comms/telecomms_jammers.dm
  code/modules/halo/overmap/shipyards.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/mob/living/say.dm
  maps/Exoplanet Research/overmap.dm
  maps/ONI_Prowler/Heavycorvette.dmi
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
  maps/ONI_Prowler/areas.dm
  maps/ONI_Prowler/backup/ONI_Prowler_Deck_1.dmm
  maps/ONI_Prowler/includes.dm
  maps/ONI_Prowler/jobs.dm
  maps/ONI_Prowler/outfits.dm
  maps/ONI_Prowler/overmap.dm
  maps/ONI_Prowler/prowl.dmi
  maps/ONI_Prowler/ship implementation documentation.dm
  maps/ONI_Prowler/spawns_jobs.dm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL, feature

#1912 Minor changes
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  maps/Exoplanet Research/overmap.dm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
Labels: enhancement/QOL

#1911 Wielded Sprites for Humans and Covenant++
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/rifles.dm
Labels: enhancement/QOL

#1913 Marine armor
  code/modules/halo/clothing/item_oni.dmi
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/oni_guard.dmi
  code/modules/halo/structures/gunvendors.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
Labels: enhancement/QOL, feature

#1905 Little things PR.
  code/modules/halo/structures/gunvendors.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression_Floors.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression_Walls.dmm
  maps/CRS_Unyielding_Transgression/spawns_jobs.dm
  maps/Crows Nest/Crows nest.dmm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
  maps/UNSC_Bertels/outfits.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/areas.dm
  maps/UNSC_Halberd_Class/overmap.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/odst_training/maps/UNSC_Bertels/outfits.dm
  maps/operation_trebuchet/UNSC_Yolotanker/outfits.dm
Labels: enhancement/QOL, mapping

#1915 various fixes
  code/modules/clothing/suits/armor.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/projectile.dm
  maps/ONI_Prowler/areas.dm
  maps/ONI_Prowler/jobs.dm
Labels: bug

#1916 Melee changes
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/melee.dm
Labels: enhancement/QOL

#1917 Marine armor
  code/modules/halo/structures/gunvendors.dm
Labels: enhancement/QOL

#1918 spartan poplock changes
  maps/ONI_Prowler/jobs.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: bug, enhancement/QOL

#1919 UNSC Weapon Sounds and UNSC/Oni Armor Fixes
  code/modules/halo/clothing/item_oni.dmi
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/sounds/Assault_Rifle_Fire_New.wav
  code/modules/halo/sounds/Assault_Rifle_Flashlight.wav
  code/modules/halo/sounds/Assault_Rifle_Reload_New.wav
  code/modules/halo/sounds/Battle_Rifle_Fire_New.wav
  code/modules/halo/sounds/Battle_Rifle_Reload_New.wav
  code/modules/halo/sounds/DMR_Fire_New.wav
  code/modules/halo/sounds/DMR_Reload_New.wav
  code/modules/halo/sounds/MA37_Fire_New.wav
  code/modules/halo/sounds/MA37_Reload_New.wav
  code/modules/halo/sounds/Magnum_Fire_New.wav
  code/modules/halo/sounds/Magnum_Reload_New.wav
  code/modules/halo/sounds/Rocket_Launcher_Fire_New.wav
  code/modules/halo/sounds/SMG_Reload_New.wav
  code/modules/halo/sounds/Shotgun_Fire_New.wav
  code/modules/halo/sounds/Shotgun_Reload_New.wav
  code/modules/halo/sounds/Sniper_Fire_New.wav
  code/modules/halo/sounds/Sniper_Reload_New.wav
  code/modules/halo/weapons/launchers.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/halo/weapons/smg.dm
  code/modules/halo/weapons/snipers.dm
Labels: enhancement/QOL, feature

#1920 Multiple Tweaks
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/structures/gunvendors.dm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
Labels: enhancement/QOL, feature

#1925 Fix runtime causing Travis failure on Geminus
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
Labels: bug, mapping

#1921 Hotfix to Marine Armor/Casing Removal
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/snipers.dm
Labels: enhancement/QOL

#1923 GC Wall hotfix + other tweaks
  code/modules/halo/weapons/covenant/grenades.dm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
  maps/ONI_Prowler/overmap.dm
  maps/geminus_city/geminuscity_1.dmm
Labels: enhancement/QOL

#1928 Grenade tweaks
  code/__defines/species_lists.dm
  code/modules/halo/weapons/covenant/grenades.dm
Labels: enhancement/QOL

#1929 spartan self destruct
  baystation12.dme
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/misc/armourspecials/self_destruct.dm
Labels: enhancement/QOL, feature

#1914 Police outfits & M6B
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/halo/clothing/civilian.dm
  code/modules/halo/clothing/gcpd.dmi
  code/modules/halo/clothing/gcpd_leftinhands.dmi
  code/modules/halo/clothing/gcpd_rightinhands.dmi
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/pistols.dm
  icons/mob/eyes.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  maps/geminus_city/geminus_city_outfits.dm
Labels: enhancement/QOL, feature, priority/low, spriting

#1927 Atom despawner implement
  baystation12.dme
  code/modules/halo/misc/atom_despawner.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/projectiles/guns/projectile.dm
  maps/_gamemodes/stranded/_all_includes.dm
  test/run-test.sh
Labels: enhancement/QOL

#1926 Armor Names/Caseless Tweaks
  code/modules/halo/clothing/marine.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/snipers.dm
Labels: enhancement/QOL

#1931 foot / hand armor thickness
  code/modules/clothing/clothing.dm
Labels: enhancement/QOL

#1935 Self destruct changes + small fixes
  code/controllers/ProcessScheduler/core/processScheduler.dm
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: bug, enhancement/QOL

#1939 Inhands Fix
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL

#1938 Multiple Misc Changes
  code/modules/halo/covenant/ammo_belt.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/weapons/covenant/grenades.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
  maps/ONI_Prowler/jobs.dm
  maps/ONI_Prowler/outfits.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL

#1937 shieldmeme
  code/modules/research/designs.dm
Labels: enhancement/QOL

#1942 stop controller crash messages
  code/controllers/ProcessScheduler/core/process.dm
  code/modules/admin/admin.dm
  code/modules/client/preference_setup/global/preference_datums.dm
Labels: bug

#1941 Martial belt Changes
  code/modules/halo/covenant/ammo_belt.dm
Labels: bug, enhancement/QOL

#1943 Spartan Nerf
  code/modules/halo/species/spartan.dm
Labels: enhancement/QOL

#1944 expands crashlog ignore functionality
  code/controllers/ProcessScheduler/core/process.dm
  code/controllers/ProcessScheduler/core/processScheduler.dm
Labels: bug, enhancement/QOL

#1947 Skirmisher buff
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species_items/skirmisher_armour.dm
  code/modules/halo/species_items/skirmisher_gauntlets.dm
  code/modules/halo/weapons/covenant/handheld_shields.dm
  maps/Covenant Corvette/jobs.dm
Labels: enhancement/QOL, feature

#1951 Armor thickness changes
  code/game/objects/items.dm
Labels: enhancement/QOL

#1953 Covenant Medical + Misc
  code/game/objects/items/bodybag.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/covenant/medical.dm
  code/modules/halo/covenant/medical.dmi
  code/modules/halo/species/spartan.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
Labels: enhancement/QOL

#1954 self destruct buff
  code/modules/halo/clothing/special_armour_procs.dm
Labels: enhancement/QOL

#1952 human ex_act changes
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: enhancement/QOL

#1949 Bugfix, Tweak, and Boxes
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL, feature

#1955 comms rank indicators
  code/game/machinery/telecomms/broadcaster.dm
Labels: enhancement/QOL, feature

#1956 Marine Ranks, ONI stuff, etc
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/structures/gunvendors.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/outfits.dm
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Bertels/outfits.dm
Labels: enhancement/QOL

#1957 More ex_act changes
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
Labels: enhancement/QOL

#1960 BR Firerate
  code/modules/halo/weapons/rifles.dm
Labels: enhancement/QOL

#1958 Slipspace equality
  code/modules/halo/overmap/slipspace_engine.dm
Labels: enhancement/QOL

#1959 removes bugged "capture innies" objective
  code/modules/halo/factions/objectives/objectives_unsc.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
Labels: bug

#1940 Update CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: enhancement/QOL, mapping

#1962 squad manager force allow pocket
  code/modules/halo/squads/squad-waypoint-manager.dm
Labels: enhancement/QOL

#1964 Spartan stuff
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/structures/gunvendors.dm
  maps/ONI_Prowler/jobs.dm
Labels: bug, enhancement/QOL, feature

#1966 Adds new UNSC crew clothes
  code/modules/halo/clothing/item_jumpsuit_ship.dmi
  code/modules/halo/clothing/jumpsuits.dm
  code/modules/halo/clothing/mob_jumpsuit_ship.dmi
  code/modules/halo/clothing/pilot.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/icons/Belt_Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/halo/weapons/smg.dm
  code/modules/halo/weapons/snipers.dm
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Bertels/outfits.dm
Labels: enhancement/QOL, feature

#1967 minor glassing effect on projector ship hit
  code/modules/halo/overmap/weapons/Energy_projector.dm
Labels: enhancement/QOL

#1970 Simple mob commands
  code/modules/halo/NPC/npc.dm
  code/modules/halo/misc/capture_node_mobs.dm
  code/modules/halo/species_items/lekgolo.dm
  code/modules/halo/vehicles/mongoose.dm
  code/modules/mob/living/simple_animal/familiars/familiars.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: enhancement/QOL, feature

#1971 spartan laser fix
  code/modules/projectiles/gun.dm
Labels: bug

#1965 URF fixes
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/innie_jobs.dm
Labels: enhancement/QOL, oversight

#1972 NCO role hotfix
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Bertels/spawns_jobs.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL

#1973 Door forcing
  code/__defines/species_lists.dm
  code/game/machinery/doors/airlock.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/mob/living/carbon/human/species/species.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
Labels: enhancement/QOL, feature

#1976 Unsc weapon changes
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/snipers.dm
  maps/ONI_Prowler/jobs.dm
Labels: enhancement/QOL, feature

#1980 'nade changes
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/species_items/grunt_outfits.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/grenades.dm
Labels: enhancement/QOL

#1981 Spartan Edits
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/structures/gunvendors.dm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
Labels: enhancement/QOL

#1983 Brute Softsuits
  code/modules/halo/icons/species/jiralhanae_gear.dmi
  code/modules/halo/icons/species/jiralhanae_obj.dmi
  code/modules/halo/species_items/jiralhanae.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: feature

#1984 Weapon locks + Brute Prifle
  code/modules/halo/species/grunts.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/projectiles/gun.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, feature

#1986 HEDP grenade explosion fix
  code/modules/halo/weapons/grenades.dm
Labels: bug

#1985 Minor Fixes
  code/modules/halo/clothing/marine.dm
  maps/Exoplanet Research/jobs.dm
  maps/Exoplanet Research/outfits.dm
Labels: enhancement/QOL

#1987 Additional Weapons for URF + Nade changes
  code/modules/halo/trade/trade_items/weapon_unsc.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/grenades.dm
Labels: enhancement/QOL

#1990 Adds Furry EVA suits + Ends the Polyacid reign of terror
  baystation12.dme
  code/modules/halo/clothing/civilian.dm
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/ranger_tvoan.dmi
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/tvoan_ranger.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/icons/species/skirm_clothing.dmi
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/skirmisher_helmet.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, feature

#1991 New Donor Items, minor tweaks.
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/head.dmi
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/clothing/urf_commando.dmi
  code/modules/halo/sounds/Magnum_Reach_Fire.wav
  code/modules/halo/sounds/Magnum_Reach_Reload.wav
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL

#1992 Female Fit Option + Misc UNSC uniforms
  code/modules/clothing/clothing.dm
  code/modules/halo/clothing/item_jumpsuit_ship.dmi
  code/modules/halo/clothing/jumpsuits.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/mob_jumpsuit_ship.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/pilot.dm
  code/modules/halo/clothing/urf_commando.dmi
  icons/mob/human_races/r_human.dmi
  maps/SOE_Argentum/argentum.dmm
Labels: enhancement/QOL, feature

#1993 Fixes Donors DMIs
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/urf_commando.dmi
Labels: enhancement/QOL, oversight

#1997 Magnum Sprite Fix, Donor Item Tweaks
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
Labels: enhancement/QOL

#1994 Adds a new ONI planet: Northwind.
  README.md
  maps/Exoplanet Research/Exoplanet Research Ice/Cro1.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro2.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/areas.dm
  maps/Exoplanet Research/Exoplanet Research Ice/includes.dm
  maps/Exoplanet Research/Exoplanet Research Ice/jobs.dm
  maps/Exoplanet Research/Exoplanet Research Ice/ks7.png
  maps/Exoplanet Research/Exoplanet Research Ice/ks7_sector_icon.dmi
  maps/Exoplanet Research/Exoplanet Research Ice/outfits.dm
  maps/Exoplanet Research/Exoplanet Research Ice/overmap.dm
  maps/Exoplanet Research/Exoplanet Research Ice/spawns.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/invasion_geminus.dm
Labels: enhancement/QOL, mapping

#1999 Increase build timeout
  .travis.yml
Labels: priority/high

#1998 Forerunner Artifact/nav chips
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/xenoarcheaology/artifacts/artifact.dm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro2.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/jobs.dm
  maps/Exoplanet Research/Exoplanet Research Ice/overmap.dm
Labels: enhancement/QOL

#2000 Spirit Dropship and SMG Tweaks
  code/modules/halo/vehicles/spirit_dropship.dm
  code/modules/halo/weapons/smg.dm
Labels: enhancement/QOL

#2001 Partial Revert of #1994
  README.md
Labels: oversight

#2002 M7 SMG Sprite Fix
  code/modules/halo/clothing/doneritems.dm
Labels: enhancement/QOL

#2003 Map fixes.
  code/modules/halo/structures/gunvendors.dm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro1.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro2.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/areas.dm
  maps/Exoplanet Research/Exoplanet Research Ice/jobs.dm
Labels: enhancement/QOL, mapping
