Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-07, with the labels that each got.

#1665 makes a majority of vehicle guns disabled upon death
  code/modules/halo/vehicles/bull.dm
  code/modules/halo/vehicles/shadow.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/warthog.dm
Labels: enhancement/QOL

#1668 wraith cannon projectile changes
  code/modules/halo/vehicles/wraith.dm
Labels: enhancement/QOL

#1667 shield input charge cap lowered
  code/modules/shield_generators/shield_generator.dm
Labels: enhancement/QOL

#1670 Updates the PR template to autogenerate changelogs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement/QOL

#1673 lowers ghost move delay
  code/modules/halo/vehicles/ghost.dm
Labels: needs changelog

#1672 changes the allowed slots for M41/fuel rod
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/launchers.dm
Labels: needs changelog

#1677 Spawns tweaks and fixes
  code/_helpers/turfs.dm
  code/game/jobs/job_controller.dm
  code/modules/atmospherics/atmos_primitives.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/halo/species_items/skirmisher_gauntlets.dm
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/ccs_battlecruiser/planet_staging.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/jobs.dm
  maps/operation_trebuchet/insurrection_jobs.dm
Labels: bug, enhancement/QOL, spawns

#1678 Updates the SoE Osprey
  maps/URF Commando Ship/first_deck.dmm
Labels: enhancement/QOL, mapping

#1680 adds projectile collision bounds to cassius
  maps/faction_bases/Cassius_Station/Cassius_Station.dm
  maps/faction_bases/Cassius_Station/Cassius_Station_1.dmm
Labels: enhancement/QOL

#1683 Misc bugfixes and tweaks
  baystation12.dme
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/halo/Forerunner/Sentinel.dmi
  code/modules/halo/Forerunner/monitor.dm
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/Forerunner/sentinel_spawner.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/misc/simple_mob_ai.dm
  maps/Exoplanet Research/spawn_jobs.dm
  maps/geminus_city/bumpstairs.dm
  maps/geminus_city/fakewall.dm
  maps/geminus_city/geminuscity_1.dmm
Labels: bug, feature

#1684 Covenant minor features
  baystation12.dme
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  code/modules/halo/covenant/Wallocker.dmi
  code/modules/halo/covenant/first_aid.dm
  code/modules/halo/covenant/medical.dmi
  code/modules/halo/covenant/tank.dm
  code/modules/halo/covenant/tools.dm
  code/modules/halo/covenant/tools.dmi
  code/modules/halo/covenant/wall_locker.dm
Labels: feature, spriting

#1681 plaspistol and general energy weapon changes
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/projectiles/guns/energy.dm
Labels: enhancement/QOL

#1676 Adds low pop gamemode variants
  baystation12.dme
  code/controllers/configuration.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/game_mode_latespawn.dm
  code/game/jobs/job/job.dm
  code/game/turfs/simulated/walls.dm
  code/modules/halo/covenant/crate.dm
  code/modules/halo/covenant/crate.dmi
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/faction_objectives.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/insurrection/innie_factions_controller.dm
  code/modules/halo/misc/oni_cryopod.dm
  code/modules/halo/misc/payload.dm
  code/modules/overmap/sectors.dm
  code/stylesheet.dm
  maps/Exoplanet Research/spawn_jobs.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/_gamemodes/invasion/objectives.dm
  maps/_gamemodes/invasion/objectives_cov.dm
  maps/_gamemodes/invasion/objectives_unsc.dm
  maps/_gamemodes/invasion/odst_crew_jobs.dm
  maps/_gamemodes/slayer.dm
  maps/civ_ships/outfits.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus.dm
  maps/odst_prowler/outfits.dm
Labels: enhancement/QOL, feature

#1687 fixes the auto-end on insurrection
  maps/operation_trebuchet/mapdef.dm
Labels: bug

#1688 Misc bugfixes and tweaks
  baystation12.dme
  code/modules/halo/covenant/energybarricade.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/vehicles/boarding_pod.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/geminus_city/fakewall.dm
Labels: bug, enhancement/QOL, feature

#1689 Misc bugfixes
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  maps/Asteroid Listening Post/overmap.dm
  maps/Exoplanet Research/overmap.dm
  maps/_gamemodes/invasion/_includes_geminus_city.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/invasion_geminus.dm
Labels: bug, enhancement/QOL

#1691 Misc bugfixes
  code/controllers/voting/vote_types.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
Labels: bug, enhancement/QOL

#1692 General fixes
  code/modules/halo/flood/ghost_role.dm
  code/modules/halo/overmap/weapons/overmap_projectile.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/shield_generators/shield_generator.dm
Labels: enhancement/QOL

#1693 Disable The Achyls Test
  .travis.yml
  scripts/validateTravisContainsAllMaps.sh
Labels: mapping

#1694 Achlys fixes
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_spawn.dm
  code/modules/halo/flood/flood_spawn_bio.dm
  maps/unsc_achlys/achlys_gm.dm
  maps/unsc_achlys/unsc_achlys_Z1.dmm
  maps/unsc_achlys/unsc_dante_Z1.dmm
  maps/unsc_achlys/unsc_dante_Z2.dmm
Labels: ackchyually, bug, enhancement/QOL, feature

#1703 Another innie base update
  maps/geminus_city/geminus_innie_base.dmm
Labels: enhancement/QOL, mapping

#1704 drop pod exposed postitions
  code/modules/halo/vehicles/drop_pod.dm
Labels: bug

#1705 adds a better flood infection chemical container
  code/modules/halo/flood/flood_infection_chem.dm
Labels: enhancement/QOL

#1695 NPC overmind controller
  baystation12.dme
  code/_helpers/global_access.dm
  code/modules/halo/NPC/npc_overmind.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/misc/simple_mob_ai.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  test/run-test.sh
Labels: enhancement/QOL, feature

#1706 Tweaks the Bertels and Cassius Station map a bit
  maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/faction_bases/Cassius_Station/Cassius_Station_1.dmm
Labels: enhancement/QOL, mapping

#1707 Adds colony capture mechanics and objectives
  baystation12.dme
  code/_helpers/type2type.dm
  code/controllers/ProcessScheduler/core/process.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/misc/capture_node.dmi
  code/modules/halo/overmap/weapons/auto_mac_program.dm
  icons/mob/screen1.dmi
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/innie_outfits.dm
Labels: enhancement/QOL, feature

#1708 Wort wort wort
  code/modules/clothing/clothing.dm
  code/modules/emotes/definitions/_mob.dm
  code/modules/emotes/definitions/audible.dm
  code/modules/halo/sounds/worting.ogg
Labels: enhancement/QOL, feature

#1709 Overmind and hostile mob tweaks
  code/modules/halo/NPC/npc_overmind.dm
  code/modules/halo/flood/flood.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: enhancement/QOL

#1710 Colony capture fixes and tweaks
  code/modules/halo/misc/capture_node.dm
  code/stylesheet.dm
  maps/geminus_city/innie_supply/program.dm
  nano/templates/supply_innie.tmpl
Labels: bug, enhancement/QOL, feature

#1712 Capture node and slipspace bugfixes
  baystation12.dme
  code/game/turfs/biome.dm
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/slipspace_engine_longrange.dm
  code/modules/halo/overmap/slipspace_gen.dm
  code/modules/overmap/sectors.dm
  maps/Admin Planet/areas.dm
  maps/Admin Planet/surface.dmm
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/_gamemodes/invasion/gamemode.dm
Labels: bug, enhancement/QOL

#1715 NPC features and improvements
  baystation12.dme
  code/datums/supplypacks/security.dm
  code/game/objects/objs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/halo/NPC/NPC_types/colonist.dm
  code/modules/halo/NPC/NPC_types/crop_trader.dm
  code/modules/halo/NPC/NPC_types/kig_yar.dm
  code/modules/halo/NPC/NPC_types/medical.dm
  code/modules/halo/NPC/NPC_types/mineral_trader.dm
  code/modules/halo/NPC/NPC_types/weapon_smuggler.dm
  code/modules/halo/NPC/npc.dm
  code/modules/halo/NPC/npc_interact.dm
  code/modules/halo/NPC/npc_listen.dm
  code/modules/halo/NPC/npc_new.dm
  code/modules/halo/NPC/speech_response.dm
  code/modules/halo/machinery/autosurgeon/_defines.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon_firstaid.dm
  code/modules/halo/machinery/autosurgeon/firstaid.dm
  code/modules/halo/machinery/autosurgeon/interact_hand.dm
  code/modules/halo/machinery/autosurgeon/interact_item.dm
  code/modules/halo/machinery/autosurgeon/interact_ui.dm
  code/modules/halo/machinery/autosurgeon/process.dm
  code/modules/halo/machinery/autosurgeon/surgery_external.dm
  code/modules/halo/machinery/autosurgeon/surgery_internal.dm
  code/modules/halo/machinery/autosurgeon/topic.dm
  code/modules/halo/machinery/autosurgeon/~autosurgeon.dm
  code/modules/halo/trade/trade_category.dm
  code/modules/halo/trade/trade_items/organs.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/organs/external/wounds/wound.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/innie_supply/program.dm
  nano/templates/npc.tmpl
Labels: enhancement/QOL, feature

#1716 Outer colonies bugfixes
  code/modules/halo/covenant/tools.dm
  code/modules/halo/covenant/tools.dmi
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/faction_objectives.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/slipspace_engine_longrange.dm
  icons/turf/areas.dmi
  maps/Covenant Corvette/areas.dm
  maps/Covenant Corvette/jobs.dm
  maps/Exoplanet Research/includes.dm
  maps/Exoplanet Research/jobs.dm
  maps/Exoplanet Research/outfits.dm
  maps/Exoplanet Research/spawns.dm
  maps/UNSC_Bertels/jobs.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: bug, enhancement/QOL

#1723 Rebalances objective point rewards, fix assassinate UNSC leader objective for covvies
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
Labels: bug, enhancement/QOL

#1724 Overmap ship work (and a slipspace drive buff
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/weapons/flood/flood_projectiles.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
Labels: enhancement/QOL, feature

#1725 UNSC Field Medical Kits
  baystation12.dme
  code/modules/halo/medicine/combat.dm
  code/modules/halo/medicine/firstaid.dm
  code/modules/halo/misc/tools_items_gear.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/syringe.dmi
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: enhancement/QOL, mapping

#1726 NPC ship cleanups
  code/modules/halo/factions/_faction.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
  maps/_gamemodes/invasion/gamemode.dm
Labels: bug, enhancement/QOL

#1729 Lowers Marine Boot Walk Voume
  code/modules/clothing/clothing.dm
Labels: enhancement/QOL

#1731 shuttle icon pick fix
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/player_shuttles.dm
  code/modules/halo/overmap/slipspace_engine.dm
Labels: bug

#1734 Enables loadouts for humans on outer colonies
  maps/Exoplanet Research/jobs.dm
  maps/UNSC_Bertels/jobs.dm
  maps/desert_outpost/jobs.dm
  maps/geminus_city/geminus_city_jobs.dm
  maps/geminus_city/geminus_city_spawns.dm
  maps/geminus_city/innie_jobs.dm
Labels: enhancement/QOL

#1735 Hull segment placement modification
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
Labels: feature

#1728 x52, here it comes
  code/modules/halo/insurrection/access_ids.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/geminus_city/x52_jobs.dm
  maps/geminus_city/x52_outfits.dm
  maps/geminus_city/x52_spawns.dm
Labels: enhancement/QOL, feature, mapping

#1741 Add various things to the x52 base
  maps/geminus_city/geminuscity_1.dmm
Labels: enhancement/QOL, mapping

#1743 Unfucks Casings
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: enhancement/QOL, not a bug, priority/high

#1745 Limit user text input for memories
  code/datums/mind.dm
Labels: oversight, priority/critical
