Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-10, with the labels that each got.

#1787 Blox base destruction refactor
  baystation12.dme
  code/game/area/areas.dm
  code/game/gamemodes/nuclear/pinpointer.dm
  code/game/objects/effects/effect_system.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/walls.dm
  code/modules/halo/demolitions/demolition_manager.dm
  code/modules/halo/demolitions/pinpointer.dm
  code/modules/halo/demolitions/structural_turf.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/overmap/sectors.dm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_1.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/UNSC_Bertels/UNSC_Bertels_Deck_3.dmm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminus_innie_base.dmm
  maps/geminus_city/innie_hud.dm
  maps/geminus_city/innie_overmap.dm
  maps/geminus_city/invasion_geminus.dm
  maps/geminus_city/sector_icon.dmi
Labels: Head developer approved self-merge, Zlevels, bug, enhancement/QOL, feature, overmap

#1791 Tweakfixes from the test
  baystation12.dme
  code/hub.dm
  code/modules/halo/factions/quest/_quest.dm
  code/modules/halo/factions/quest/quest_finish.dm
  code/modules/halo/misc/capture_node_mobs.dm
  maps/geminus_city/innie_quest/program_comms.dm
  maps/geminus_city/innie_quest/program_shuttle.dm
Labels: Head developer approved self-merge, bug, enhancement/QOL

#1798 UNSC Iron Will Implement
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/structures/supersmes.dm
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/UNSC_Bertels/areas.dm
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Bertels/outfits.dm
  maps/UNSC_Bertels/overmap.dm
  maps/UNSC_Bertels/spawns_jobs.dm
  maps/UNSC_Iron_Will/Heavycorvette.dmi
  maps/UNSC_Iron_Will/UNSC_Iron_Will.dmm
  maps/UNSC_Iron_Will/areas.dm
  maps/UNSC_Iron_Will/includes.dm
  maps/UNSC_Iron_Will/overmap.dm
  maps/faction_bases/Cassius_Station/Cassius_Station.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus.dm
  maps/odst_training/overall_jobdefs.dm
Labels: enhancement/QOL, feature, mapping

#1799 track bound vehicle
  baystation12.dme
  code/modules/halo/vehicles/track.dmi
  code/modules/halo/vehicles/track_bound.dm
  code/modules/halo/vehicles/track_vehicle.dmi
Labels: feature

#1800 Kig-Yar hud-glasses changes
  code/modules/halo/species_items/kig-yar.dm
Labels: feature

#1801 overloaded slipspace drive density change
  code/modules/halo/overmap/slipspace_engine.dm
Labels: enhancement/QOL

#1793 Fixed Chair
  code/modules/halo/covenant/chair.dm
  code/modules/halo/covenant/chair.dmi
Labels: enhancement/QOL, priority/low, spriting

#1805 Mech fixes
  code/game/mecha/combat/Hrunting.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: enhancement/QOL, feature

#1804 unsc iron will fixes
  maps/UNSC_Iron_Will/UNSC_Iron_Will.dmm
Labels: bug, enhancement/QOL

#1803 Adds Ashvors Marine Donor Armor and Sleepy's ODST donor armor
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL

#1806 Changes Cassius Station to ODP Cassius
  maps/Exoplanet Research/overmap.dm
  maps/faction_bases/Cassius_Station/Cassius_Station.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/areas.dm
  maps/faction_bases/ODP_Cassius/backup/ODP_Cassius_1.dmm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/invasion_geminus.dm
Labels: enhancement/QOL, feature

#1811 minor issue fixes on the IW
  maps/UNSC_Iron_Will/UNSC_Iron_Will.dmm
Labels: bug, enhancement/QOL

#1814 Minor tweaks to ODP Cassius.
  maps/UNSC_Prowler/overmap.dm
  maps/faction_bases/Cassius_Station/backup/Cassius_Station_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/backup/ODP_Cassius_1.dmm
Labels: enhancement/QOL, oversight

#1808 Add a better version, somewhat playable huragok to the game
  baystation12.dme
  code/datums/ai_law_sets.dm
  code/game/objects/items/stacks/matter_synth.dm
  code/modules/halo/covenant/huragok/huragok.dm
  code/modules/halo/covenant/huragok/huragok_items.dm
  code/modules/halo/covenant/huragok/huragok_modules.dm
  code/modules/materials/material_synth.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/screen1_robot.dmi
Labels: feature

#1816 covvie medkits
  baystation12.dme
  code/modules/halo/covenant/medical.dm
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
Labels: enhancement/QOL, feature

#1817 Add a special gripper for huragoks and fix a bunch of things
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/halo/covenant/huragok/huragok.dm
  code/modules/halo/covenant/huragok/huragok_items.dm
  code/modules/halo/covenant/huragok/huragok_modules.dm
  code/modules/halo/covenant/huragok/items.dmi
Labels: enhancement/QOL, feature

#1820 Socks/Eonoc Donator Stuff
  code/modules/halo/clothing/ODSTDonorPackage.dmi
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/icons/species/Sangheili_Combat_Harness.dmi
Labels: enhancement/QOL

#1821 New Ship: UNSC Light Brigade.
  maps/UNSC_Bertels/overmap.dm
  maps/UNSC_Halberd_Class/Heavycorvette.dmi
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/areas.dm
  maps/UNSC_Halberd_Class/includes.dm
  maps/UNSC_Halberd_Class/overmap.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: enhancement/QOL, mapping

#1822 overall capship weapon nerfs
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/MAC.dm
Labels: enhancement/QOL

#1826 Rounds should again end properly
  maps/_gamemodes/invasion/gamemode.dm
Labels: Head developer approved self-merge, bug

#1832 Update SOE Gear
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/clothing/urf_commando.dmi
Labels: enhancement/QOL, spriting

#1829 Update ODP_Cassius_1.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/overmap.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
Labels: enhancement/QOL, mapping

#1835 New Covenant Ship.
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/CRSlightcruiser.dmi
  maps/CRS_Unyielding_Transgression/areas.dm
  maps/CRS_Unyielding_Transgression/includes.dm
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/CRS_Unyielding_Transgression/outfits.dm
  maps/CRS_Unyielding_Transgression/overmap.dm
  maps/CRS_Unyielding_Transgression/spawns_jobs.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/geminus_city/invasion_geminus.dm
Labels: enhancement/QOL, mapping

#1834 Donator Armor, Helmet, and Weapon Fixes
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/rifles.dm
Labels: enhancement/QOL, spriting

#1837 Misc tweaks and fixes
  code/modules/halo/NPC/npc_trade.dm
  code/modules/halo/factions/_faction.dm
  maps/Exoplanet Research/overmap.dm
  maps/URF Commando Ship/jobs.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/x52_jobs.dm
Labels: bug, enhancement/QOL

#1836 Ports pixel based movement and rotation for ships from old code
  baystation12.dme
  code/modules/overmap/helpers.dm
  code/modules/overmap/observe.dm
  code/modules/overmap/pixel_transform/_pixel_transform.dm
  code/modules/overmap/pixel_transform/turn.dm
  code/modules/overmap/pixel_transform/update.dm
  code/modules/overmap/pixel_transform/update_x.dm
  code/modules/overmap/pixel_transform/update_y.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/ship.dm
  nano/templates/helm.tmpl
Labels: feature

#1833 Shipyards
  baystation12.dme
  code/game/objects/items/devices/radio/radio.dm
  code/game/turfs/space/space.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/halo/overmap/shipyards.dm
  code/modules/maps/reader.dm
  maps/Covenant Corvette/DAV_Vindicative_Infraction.dmm
  maps/Covenant Corvette/DAV_Vindicative_Infraction_Floors.dmm
  maps/Covenant Corvette/DAV_Vindicative_Infraction_Walls.dmm
  maps/Covenant Corvette/overmap.dm
  maps/Exoplanet Research/overmap.dm
  maps/UNSC_Iron_Will/UNSC_Iron_Will_Floors.dmm
  maps/UNSC_Iron_Will/UNSC_Iron_Will_Walls.dmm
  maps/geminus_city/geminus_city_overmap.dm
Labels: enhancement/QOL, feature

#1840 iron will droppods and pelican fix
  code/modules/halo/covenant/weapon_rack.dm
  maps/UNSC_Iron_Will/UNSC_Iron_Will.dmm
Labels: bug

#1842 Various minor modifications to existing maps.
  code/modules/halo/covenant/chair.dmi
  code/modules/halo/icons/machinery/reactor2.dmi
  code/modules/halo/icons/overmap/faction_misc.dmi
  code/modules/halo/overmap/weapons/auto_mac_console.dm
  code/modules/halo/structures/AI Stuff.dmi
  code/modules/halo/structures/cryopod.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
Labels: enhancement/QOL

#1845 Small tweaks based on map feedback.
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: enhancement/QOL, mapping

#1846 Switches out UNSC Iron Will for UNSC Light Brigade.
  code/modules/halo/icons/machinery/computer.dmi
  code/modules/halo/overmap/shipyards.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/faction_bases/Cassius_Station/Cassius_Station.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/invasion_geminus.dm
Labels: enhancement/QOL, feature, mapping

#1848 General UNSC QOL
  code/game/machinery/doors/multi_tile.dm
  code/modules/halo/doors/3xblastdoorsns.dmi
  code/modules/halo/doors/4xblastdoorns.dmi
  code/modules/halo/doors/Longer Blastdoor.dmi
  code/modules/halo/doors/blastdoor.dmi
  code/modules/halo/doors/halo_doors.dm
  maps/Crows Nest/Crows nest.dmm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/ExoResearch_3.dmm
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/odst_training/maps/UNSC_Bertels/jobs.dm
Labels: enhancement/QOL, in-progress, mapping

#1847 SOE Argentum, misc Fixes
  code/modules/halo/structures/gunvendors.dm
  maps/Asteroid Listening Post/overmap.dm
  maps/SOE_Argentum/areas.dm
  maps/SOE_Argentum/argentum.dmi
  maps/SOE_Argentum/argentum.dmm
  maps/SOE_Argentum/includes.dm
  maps/SOE_Argentum/jobs.dm
  maps/SOE_Argentum/outfits.dm
  maps/SOE_Argentum/overmap.dm
  maps/SOE_Argentum/prowler.dmi
  maps/SOE_Argentum/spawns.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/invasion_geminus.dm
Labels: enhancement/QOL, feature, mapping

#1849 Fixed flashlight attachment, for UNSC.
  code/modules/halo/weapons/rifles.dm
  code/modules/projectiles/attachments/lights.dm
Labels: bug, enhancement/QOL, oversight

#1851 Halberd class ship icon.
  code/game/objects/items/weapons/tanks/tank_types.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/Halberdclass.dmi
  maps/UNSC_Halberd_Class/Heavycorvette.dmi
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/overmap.dm
Labels: enhancement/QOL

#1852 Orion balance
  code/modules/halo/misc/Orion Project.dm
Labels: enhancement/QOL

#1853 Covenant shipyard reports location
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/halo/overmap/shipyards.dm
Labels: enhancement/QOL, feature

#1854 Update UNSC_Light_Brigade.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
Labels: enhancement/QOL, mapping

#1856 Adds some covenant stuff
  baystation12.dme
  code/modules/halo/covenant/tools.dm
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/lmg.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, feature

#1857 Neural lace ids
  code/game/jobs/access.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/modules/organs/internal/stack.dm
  maps/Exoplanet Research/jobs.dm
  maps/UNSC_Bertels/jobs.dm
Labels: enhancement/QOL, feature

#1858 Minor Donator updates
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/icons/species/jiralhanae_gear.dmi
  code/modules/halo/icons/species/jiralhanae_obj_large.dmi
Labels: enhancement/QOL

#1860 plasrepeater value tweak
  code/modules/halo/weapons/covenant/lmg.dm
Labels: enhancement/QOL

#1861 HRUNTING Rebalance & Pelican Fix
  code/game/mecha/combat/Hrunting.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/halo/vehicles/pelican.dm
  code/modules/halo/weapons/launchers.dm
  maps/ccs_battlecruiser/planet_staging.dmm
  maps/desert_outpost/desert_outpost.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
Labels: enhancement/QOL

#1863 simplemob firedelays
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: enhancement/QOL
