Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-01, with the labels that each got.

#1027 URFC tweak
  code/modules/halo/clothing/urf_commando.dm
Labels: enhancement/QOL

#1022 Adds glassing cannon
  baystation12.dme
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/machinery/overmap_weapon_ammo.dm
  code/modules/halo/machinery/plasma_cannon.dmi
  code/modules/halo/machinery/pulse_turret_tracers.dmi
  code/modules/overmap/sectors.dm
  html/changelogs/erty80s-1.3.2019.yml
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
Labels: enhancement/QOL, feature

#1030 Add in-hands for the energy stave
  baystation12.dme
  code/modules/halo/misc/SyetenArbiter/SyetenArbiter.dm
  code/modules/halo/misc/SyetenArbiter/inhands_left.dmi
  code/modules/halo/misc/SyetenArbiter/inhands_right.dmi
Labels: enhancement/QOL, spriting

#1040 Overmap Combat : Projectile Tracking
  baystation12.dme
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/overmap_weapon.dm
  code/modules/halo/machinery/proj_deck_gun.dm
Labels: enhancement/QOL, feature, in-progress

#1042 Stingray - Multiple Changes
  code/game/jobs/job/job.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/mob/living/carbon/human/species/station/orion.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/Desolane-balancingadjusting.yml
  maps/ccs_battlecruiser/jobs/elite.dm
  maps/first_contact/maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/first_contact/maps/Covenant Corvette/jobs.dm
  maps/first_contact/maps/Covenant Corvette/spawns_jobs.dm
  maps/first_contact/overall_jobdefs.dm
Labels: enhancement/QOL, feature

#1041 modifies dual wielding code
  code/modules/halo/weapons/dual_wielding.dm
Labels: enhancement/QOL

#1043 Probably fixes mongoose speedup issue
  code/modules/halo/vehicles/mongoose.dm
Labels: bug

#1045 enables energy weapon throatslit
  code/modules/mob/grab/normal/grab_normal.dm
Labels: enhancement/QOL

#1046 thorin alarm + captain's office safe of goodies
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, mapping

#1047 Missile changes
  code/modules/halo/machinery/missile_pods.dm
  code/modules/halo/machinery/overmap_projectile.dm
Labels: bug, enhancement/QOL

#1048 replaces incorrect ammo-type in thorin safe
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL

#1050 Flood Biomass spawning re-enabled
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_spawn.dm
Labels: enhancement/QOL

#1052 Fixes a bug in turret/vehicle interaction
  code/modules/halo/weapons/turrets/turret.dm
Labels: bug

#1051 Adds an EVA mode to shields
  baystation12.dme
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/living/carbon/human/life.dm
  html/changelogs/XO11 - Shield EVA Mode.yml
Labels: enhancement/QOL, feature

#1053 Armour Repair System
  baystation12.dme
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/clothing/armor_repair/armor_repair_sprites.dmi
  code/modules/halo/clothing/armor_repair/repair_bench.dm
  code/modules/halo/structures/gunvendors.dm
  html/changelogs/XO11 - Armour Repair System.yml
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, feature

#1054 Adds armour repair patches and benches to FC maps
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/clothing/armor_repair/repair_bench.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
  maps/first_contact/maps/UNSC_Prowler/UNSC_Prowler_Deck_1.dmm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
Labels: enhancement/QOL, feature, mapping

#1061 Shield code changes
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/proj_deck_gun.dm
  code/modules/shield_generators/shield.dm
Labels: enhancement/QOL, feature

#1056 Fixes some issues with vote controller, unincludes unneeded file from DME
  baystation12.dme
  code/_helpers/global_access.dm
  code/controllers/voting.dm
  code/controllers/voting/Topic.dm
  code/controllers/voting/_vote.dm
  code/controllers/voting/interface.dm
  code/controllers/voting/process.dm
  code/controllers/voting/vote_types.dm
  test/run-test.sh
Labels: bug

#1064 Overmap projectile ship impact sounds
  code/game/sound.dm
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/machinery/MAC.dm
  code/modules/halo/machinery/covie_pulse_turret.dm
  code/modules/halo/machinery/missile_pods.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/machinery/proj_deck_gun.dm
  code/modules/halo/sounds/om_proj_hitsounds/deck_gun_impact.wav
  code/modules/halo/sounds/om_proj_hitsounds/eprojector_hit_sound.wav
  code/modules/halo/sounds/om_proj_hitsounds/mac_cannon_impact.wav
  code/modules/halo/sounds/om_proj_hitsounds/plaser_hit_sound.wav
  code/modules/halo/sounds/om_proj_hitsounds/rocketpod_missile_impact.wav
  code/modules/halo/sounds/pulse_turret_fire.ogg
Labels: enhancement/QOL, feature

#1066 Overmap Weapons Fix : Energy Beam Penetration
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/machinery/covie_pulse_turret.dm
Labels: bug

#1076 ODST training hotfix
  maps/odst_training/overall_overmap.dm
Labels: oversight

#1080 Eva shieldmode bugfix
  code/modules/halo/misc/armourspecials/shields.dm
Labels: enhancement/QOL, feature

#1082 Missing Overmap Hotfix
  code/modules/overmap/sectors.dm
Labels: bug

#1083 hotfix for recent z-level linking issue
  code/modules/overmap/sectors.dm
Labels: bug

#1084 Drop pod beacons
  baystation12.dme
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/drop_pod.dm
  code/modules/halo/weapons/drop_pod_beacon.dm
  code/modules/halo/weapons/dual_wielding.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
Labels: feature

#1086 adds a map_data marker missed in #1085
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
Labels: bug

#1088 adds excavation tools, xenoarch stuff and a smelter to vt9
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
Labels: enhancement/QOL, feature

#1089 Misc bug fixes
  code/_helpers/global_access.dm
  code/controllers/voting/vote_types.dm
  code/modules/events/electrical_storm.dm
  code/modules/halo/comms/channel_keys.dm
  code/modules/halo/comms/commsitems.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/machinery/overmap_projectile.dm
  code/modules/halo/misc/gas_geyser.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/mob/living/say.dm
  code/modules/multiz/structures.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/first_contact/maps/Exoplanet Research/ExoResearch_0.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_2.dmm
  maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
Labels: bug

#1091 makes the vt9 mining-stairs actually climbable
  maps/first_contact/maps/Exoplanet Research/ExoResearch_1.dmm
Labels: bug

#1092 makes drop pods not land inside rock walls
  code/modules/halo/vehicles/drop_pod.dm
Labels: bug

#1094 armour patches and repair bench now update armour description
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/clothing/armor_repair/repair_bench.dm
Labels: enhancement/QOL

#1095 Re-enables xenoarch find and artifact generation
  code/controllers/master_controller.dm
Labels: feature, needs changelog

#1098 Aim mode changes
  code/modules/projectiles/gun.dm
  code/modules/projectiles/targeting/targeting_triggers.dm
Labels: enhancement/QOL, feature, needs changelog

#1099 In an ideal world, this would fix the overmap-weapon zoom exploit
  code/modules/halo/species_items/species_abilities.dm
  code/modules/projectiles/gun.dm
Labels: bug

#1100 Payload self-delete fix
  code/modules/halo/misc/payload.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: bug

#1101 Fixes Wehraboo's ODST Donator Armour
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL

#1103 Removes ship-shield "adaptive" mode
  code/modules/shield_generators/modes.dm
Labels: feature

#1104 various fixes
  code/modules/overmap/sectors.dm
  maps/first_contact/maps/Covenant Corvette/SDV_Vindicative_Infraction.dmm
Labels: bug, feature

#1110 ODST/Commando Slot Tweaks
  maps/first_contact/maps/UNSC_Bertels/jobs.dm
  maps/first_contact/maps/URF Commando Ship/jobs.dm
Labels: enhancement/QOL

#1111 adds a null-console check
  code/modules/halo/machinery/overmap_projectile.dm
Labels: bug

#1118 Makes energy sword lunges respect the presence of matter
  code/modules/halo/weapons/covenant/melee.dm
Labels: bug, feature

#1114 makes overmap weapons check for power
  code/modules/halo/machinery/overmap_weapon.dm
Labels: feature

#1109 Voteable mapswitcher
  baystation12.dme
  code/controllers/voting.dm
  code/controllers/voting/process.dm
  code/controllers/voting/vote_types.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapswitch.dm
  generate_switchable_maps.sh
  html/changelog.html
  html/changelogs/.all_changelog.yml
  maps/~mapsystem/switch_maps.dm
Labels: enhancement/QOL, feature

#1127 Sprite fix
  code/modules/halo/vehicles/Scorpion.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: bug, enhancement/QOL

#1128 null hotfix
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: feature

#1130 bertels attachment vendor access remove
  code/modules/projectiles/gun.dm
  maps/first_contact/maps/UNSC_Bertels/UNSC_Bertels_Deck_2.dmm
Labels: bug

#1131 fixes pain scream cooldown
  code/modules/emotes/definitions/audible.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: bug

#1132 SDV cloak changes
  maps/first_contact/maps/Covenant Corvette/overmap.dm
Labels: enhancement/QOL

#1135 DMR ammunition fix
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/snipers.dm
Labels: bug

#1136 DMR magazine caliber fix
  code/modules/halo/weapons/ammo.dm
Labels: bug

#1137 removes the *painscream pitch-varying
  code/modules/emotes/definitions/audible.dm
  code/modules/halo/species/kig-yar.dm
Labels: enhancement/QOL

#1126 Sonic Disruption Sniper Rifle
  code/modules/halo/sounds/sound_rifle_firesound.ogg
  code/modules/halo/sounds/unggoy_grenade_throw.ogg
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/snipers.dm
  maps/first_contact/maps/UNSC_Thorin/UNSC_Thorin_Deck_1.dmm
  maps/first_contact/maps/URF Commando Ship/first_deck.dmm
Labels: feature

#1144 Glassing bug fix
  code/modules/halo/machinery/Energy_projector.dm
  code/modules/halo/machinery/overmap_projectile.dm
Labels: bug, oversight

#1149 Automated Overmap Defenses + Nav computers
  baystation12.dme
  code/modules/halo/machinery/boarding_beacon_launcher.dm
  code/modules/halo/overmap/automated_defense.dm
  code/modules/halo/overmap/nav_computer.dmi
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/halo/overmap/npc_ships.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL, feature

#1151 SDSR no respect armour
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/snipers.dm
Labels: bug

#1154 EVA for the UNSC
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
Labels: enhancement/QOL, feature

#1159 drop pod beacon actually activates
  code/modules/halo/weapons/drop_pod_beacon.dm
Labels: bug

#1157 Potential hunter immortality fix
  code/modules/halo/species_items/lekgolo.dm
Labels: bug

#1166 removes the human-blocker shieldmode
  code/modules/shield_generators/modes.dm
Labels: enhancement/QOL

#1162 covvie self-glass fix
  code/modules/halo/machinery/overmap_weapon.dm
Labels: bug

#1147 Mid round gamemode votes will no longer restart the server
  code/controllers/voting/vote_types.dm
Labels: enhancement/QOL

#1163 Makes the Xenoarch setup not throw an error
  code/modules/xenoarcheaology/master_controller.dm
Labels: bug

#1165 makes turf-penetration do more damage
  code/modules/projectiles/projectile.dm
Labels: feature

#1169 Update marine_items.dmi for EVA
  code/modules/halo/clothing/marine_items.dmi
Labels: oversight

#1179 Some mapswitcher stuff
  code/modules/halo/species_items/spartan.dm
  maps/_gamemodes/slayer.dm
  maps/_gamemodes/teamslayer.dm
  maps/_gamemodes/teamslayer_covenantvspartan.dm
  maps/ccs_battlecruiser/mapdef.dm
  maps/first_contact/mapdef.dm
  maps/insurrection/mapdef.dm
  maps/slayer/death_asteroid_areas.dm
  maps/slayer/death_asteroid_map.dm
  maps/slayer/slayer_hud_icons.dmi
  maps/slayer/slayer_jobs.dm
  maps/slayer/slayer_outfits.dm
  maps/~mapsystem/switch_maps.dm
Labels: enhancement/QOL, feature

#1183 Faction Base groundwork
  baystation12.dme
  code/modules/halo/overmap/automated_defense.dm
  code/modules/halo/overmap/faction_base.dm
  code/modules/overmap/sectors.dm
Labels: feature

#1184 Adds names for the automated defense platforms
  code/modules/halo/overmap/automated_defense.dm
  code/modules/halo/overmap/npc_ships.dm
Labels: enhancement/QOL

#1189 Various Fixes
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/weapons/covenant/ammo.dm
Labels: feature
