Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2019-12, with the labels that each got.

#2007 null check fix
  code/game/jobs/job_controller.dm
Labels: bug

#2010 Various mapfixes.
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro1.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro2.dmm
  maps/ONI_Prowler/ONI_Prowler_Deck_1.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade_Floors.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade_Walls.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, mapping

#2008 drm overperformance + sniper nerfs
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL

#2011 hologram sprite update
  code/modules/halo/icons/ai_holograms/holograms.dmi
  code/modules/halo/structures/gunvendors.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL

#2012 pinning fix
  code/__defines/process_scheduler.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/briefcase.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/mob/living/living_defense.dm
Labels: bug

#2013 Mapfixes.
  code/modules/halo/structures/gunvendors.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression_Floors.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression_Walls.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro2.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/areas.dm
Labels: enhancement/QOL, mapping

#2014 Dodge Roll
  baystation12.dme
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/dodge_roll.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/living_defines.dm
Labels: enhancement/QOL, feature

#2015 Light strip
  maps/Exoplanet Research/Exoplanet Research Ice/Cro1.dmm
  maps/Exoplanet Research/Exoplanet Research Ice/Cro2.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL

#2016 Slispace link
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/overmap/sectors.dm
Labels: enhancement/QOL, feature

#2019 stops grand theft shipyard
  code/modules/halo/overmap/automated_defense.dm
  code/modules/halo/overmap/shipyards.dm
  code/modules/halo/overmap/slipspace_engine.dm
  maps/faction_bases/Cassius_Station/Cassius_Station.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/faction_base.dm
Labels: bug

#2021 mini covenant updates
  code/modules/paperwork/pen.dm
  icons/obj/crayons.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping

#2025 fixes apc interaction
  code/modules/power/apc.dm
Labels: bug

#2027 combat form resistance
  code/modules/halo/flood/flood.dm
Labels: enhancement/QOL

#2026 Huragok implement
  code/__defines/species_lists.dm
  code/modules/halo/covenant/huragok/huragok.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/CRS_Unyielding_Transgression/outfits.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL, feature

#2028 Misc fixes to dogs
  code/modules/halo/misc/animals/dogs.dm
  code/modules/halo/misc/animals/dogs.dmi
Labels: enhancement/QOL

#2029 Drone implement
  baystation12.dme
  code/__defines/species_lists.dm
  code/game/atoms.dm
  code/game/gamemodes/extended/extended.dm
  code/game/objects/items.dm
  code/game/objects/structures/window.dm
  code/modules/client/preferences.dm
  code/modules/clothing/clothing.dm
  code/modules/halo/icons/species/Jiralhanae_mob.dmi
  code/modules/halo/icons/species/jiralhanae_fullsprite.dmi
  code/modules/halo/icons/species/r_yanmee.dmi
  code/modules/halo/icons/species/yanmee_fullsprite.dmi
  code/modules/halo/icons/species/yanmee_gear.dmi
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species/yanmee.dm
  code/modules/halo/species_items/species_abilities.dm
  code/modules/halo/species_items/yanmee.dm
  code/modules/halo/species_items/yanmee_nicknames.txt
  code/modules/halo/species_items/yanmee_outfits.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/dual_wielding.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/life.dm
  code/modules/mob/update_icons.dm
  code/modules/projectiles/gun.dm
  code/unit_tests/unit_test.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: bug, enhancement/QOL, feature

#2030 windows should contain air now
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/window.dm
  code/modules/halo/covenant/tools.dm
  code/modules/halo/species_items/yanmee.dm
  code/modules/halo/species_items/yanmee_outfits.dm
Labels: bug

#2032 minor Yanmee tweaks
  code/game/machinery/doors/door.dm
  code/modules/halo/covenant/huragok/huragok_modules.dm
  code/modules/halo/covenant/tools.dm
  code/modules/halo/vehicles/spirit_dropship.dm
Labels: enhancement/QOL

#2041 window pass flight removal
  code/game/objects/structures/window.dm
  code/modules/halo/icons/species/yanmee_gear.dmi
Labels: bug

#2044 autoheal no cutoff
  code/modules/halo/clothing/marine.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/yanmee.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/organs/external/wounds/wound.dm
  code/modules/organs/external/wounds/wound_types.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, feature

#2048 bound fix
  code/modules/halo/overmap/weapons/Energy_projector.dm
  maps/UNSC_Halberd_Class/overmap.dm
Labels: bug

#2052 Yanme'e Balancing Pass
  code/game/objects/items.dm
  code/game/objects/structures/girders.dm
  code/modules/halo/species/yanmee.dm
  code/modules/halo/species_items/species_abilities.dm
  code/modules/halo/species_items/yanmee.dm
Labels: bug

#2057 huragok changes
  code/modules/halo/covenant/huragok/huragok.dm
  code/modules/halo/covenant/huragok/huragok_items.dm
Labels: enhancement/QOL

#2058 mech fixes
  code/game/mecha/combat/durand.dm
  code/game/mecha/mecha.dm
Labels: bug

#2067 Various changes
  code/game/machinery/vending.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/weapons.dm
  code/modules/halo/icons/species/grunt_gear.dmi
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/species/yanmee.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/grunt_outfits.dm
  code/modules/halo/species_items/kig-yar_outfits.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/halo/species_items/skirmisher_outfits.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/blamite.dmi
  code/modules/halo/weapons/icons/machete.dmi
  code/modules/halo/weapons/melee.dm
  code/modules/halo/weapons/pistols.dm
  maps/CRS_Unyielding_Transgression/outfits.dm
  maps/SOE_Argentum/outfits.dm
  maps/UNSC_Bertels/outfits.dm
Labels: bug, enhancement/QOL, feature

#2077 sword obj update
  code/modules/halo/weapons/icons/machete.dmi
Labels: enhancement/QOL

#2076 Add medicine for ear damage
  code/modules/halo/medicine/combat.dm
  code/modules/halo/medicine/firstaid.dm
  code/modules/mob/living/life.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: enhancement/QOL, oversight

#2079 Decouples MAC/Projector from the energy grid
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/pistols.dm
Labels: enhancement/QOL

#2080 Add ODST Dogs
  code/modules/halo/misc/animals/combatdogs.dm
  code/modules/halo/misc/animals/dogs.dm
  code/modules/halo/misc/animals/dogs.dmi
Labels: enhancement/QOL

#2081 Yanme'e Balance Pass
  code/game/machinery/vending.dm
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/halo/species/yanmee.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  maps/Exoplanet Research/jobs.dm
Labels: enhancement/QOL

#2083 Argentum QoL
  maps/SOE_Argentum/argentum.dmm
Labels: enhancement/QOL, mapping
