Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-12, with the labels that each got.

#2866 Fixes grunt grenade sound
  code/modules/halo/weapons/covenant/grenades.dm
Labels: Bugfix

#2862 Rework shield sounds
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/sanshyuum/clothing.dm
  code/modules/halo/covenant/species/yanmee/clothing.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/sounds/Shields_Gone.ogg
  code/modules/halo/sounds/Shields_Recharge.ogg
  code/modules/halo/sounds/shields/EliteDown.ogg
  code/modules/halo/sounds/shields/EliteLow.ogg
  code/modules/halo/sounds/shields/EliteRecharge.ogg
  code/modules/halo/sounds/shields/SpartanDown.ogg
  code/modules/halo/sounds/shields/SpartanLow.ogg
  code/modules/halo/sounds/shields/SpartanRecharge.ogg
Labels: enhancement/QOL

#2875 Make global variable generation robust against line ending differences
  tools/GenerateGlobalVarAccess/gen_globals.py
Labels: oversight

#2881 Implements QOL and balance tweaks from recent playtest data
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/covenant/structures_machines/energybarricade.dm
  code/modules/halo/structures/tanktrap.dm
  code/modules/halo/vehicles/__defs.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/weapons/SDSR10.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/shield_generators/modes.dm
  maps/_gamemodes/_popbalance.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/base_assault/base_assault_gm.dm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL

#2874 Remove vestigial UI elements from character setup/lobby
  code/_helpers/global_access.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preference_setup/antagonism/02_setup.dm
  code/modules/client/preference_setup/general/05_background.dm
  code/modules/client/preference_setup/matchmaking/matchmaking.dm
  code/modules/client/preference_setup/matchmaking/relations.dm
  code/modules/client/preference_setup/matchmaking/relations_types.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preference_setup/skills/skills.dm
  code/modules/client/preferences.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/skill.dm
  code/world.dm
  test/run-test.sh
Labels: enhancement/QOL

#2883 Makes lane selection on base assault randomise through all 3 lanes
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/multi_tile.dm
  code/modules/halo/misc/executions.dm
  code/modules/halo/structures/barbedwire.dm
  code/modules/halo/weapons/ammo_12-7mm.dm
  code/modules/mob/living/carbon/human/species/species.dm
  maps/base_assault/base_assault.dm
  maps/base_assault/base_assault_gm.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
  maps/faction_bases/CassiusMoonStation/presets.dm
Labels: Balancing, Bugfix, mapping, spawns

#2885 better defenses for moonbase
  code/modules/halo/structures/tanktrap.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
Labels: mapping

#2886 Makes explosions create cover-debris on some tiles
  baystation12.dme
  code/modules/halo/icons/explosion_debris.dmi
  code/modules/halo/misc/custom_explosion.dm
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/storage/pocketstorage.dm
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/structures/sandbag.dm
  code/modules/halo/structures/tanktrap.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/mining/mine_turfs.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
Labels: enhancement/QOL
