Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-02, with the labels that each got.

#2162 Donor Armor, Bug Fix, and Quality of Life changes.
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/sounds/Assault_Rifle_Short_Burst_New.wav
  code/modules/halo/structures/barbedwire.dm
  code/modules/halo/structures/tanktrap.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Bugfix, enhancement/QOL

#2164 Adds Foot Coverage to Elites
  code/modules/halo/species_items/sangheili.dm
Labels: oversight

#2166 explosive weapon changes
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/launchers.dm
Labels: enhancement/QOL

#2168 Minor Changes for LB
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
Labels: enhancement/QOL, mapping

#2160 Achlys Hotfix2
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_spawn_bio.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  maps/unsc_achlys/achlys_gm.dm
  maps/unsc_achlys/achlys_jobs.dm
  maps/unsc_achlys/achlys_objects.dm
  maps/unsc_achlys/mapdef.dm
  maps/unsc_achlys/unsc_achlys_Z3.dmm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
  maps/unsc_achlys/unsc_dante_Z2.dmm
Labels: Bugfix, enhancement/QOL, oversight

#2171 Changes and Additions to the CRS
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping

#2172 Kig-Yar Armor Oversight/bug Fixes
  code/modules/halo/clothing/kigyar_ranger.dm
  code/modules/halo/species_items/kig-yar.dm
Labels: enhancement/QOL, oversight

#2175 Achlys Hotfix3
  maps/unsc_achlys/achlys_gm.dm
  maps/unsc_achlys/achlys_objects.dm
  maps/unsc_achlys/unsc_achlys_Z1.dmm
  maps/unsc_achlys/unsc_achlys_Z3.dmm
  maps/unsc_achlys/unsc_dante_Z1.dmm
  maps/unsc_achlys/unsc_dante_Z2.dmm
Labels: Balancing, enhancement/QOL, oversight

#2176 closes the gap in damage between pulse lasers and deck guns
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
Labels: bug

#2177 Small LB Changes
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
Labels: enhancement/QOL, mapping

#2181 General Changes + Achlys stuff
  code/_onclick/other_mobs.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/turrets/deploy_kits.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  maps/unsc_achlys/achlys_gm.dm
Labels: enhancement/QOL, feature

#2183 General fixes
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: bug

#2189 Update oni_guard.dm
  code/modules/halo/clothing/oni_guard.dm
Labels: enhancement/QOL, oversight

#2190 Adds sprites for covenant APC, SMES, and power cells.
  code/modules/halo/covenant/power.dmi
Labels: enhancement/QOL, spriting

#2165 Experimental Gunplay Change
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/pulse.dm
Labels: Controversial, feature

#2191 General fixes
  code/game/jobs/job_controller.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/halo/machinery/telecomms_relays.dm
  code/modules/halo/overmap/weapons/laser_designator.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/rifles.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/backup/UNSC_Light_Brigade.dmm
  maps/urf_flagship/first_deck.dmm
Labels: Balancing, Bugfix

#2193 Covenant unused sprites
  code/modules/halo/covenant/medical.dm
  code/modules/halo/covenant/medical.dmi
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/storage.dmi
  icons/obj/syringe.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL

#2192 Fixes some bugs with vehicle loading
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/vehicle_cargo.dm
Labels: bug

#2195 storage item slowdown fix
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/halo/clothing/odst.dm
Labels: Bugfix

#2194 Migrate DB tables to UTF-8 for 513 support
  sql/migrate/V005_Update_Charset.sql
Labels: enhancement/QOL, not a bug, priority/med

#2199 co-ord console
  maps/Exoplanet Research/ExoResearch_2.dmm
Labels: enhancement/QOL, feature

#2210 A variety of VT92.0 related changes and fixes
  baystation12.dme
  code/__defines/mobs.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/modules/halo/Forerunner/forerunner_weapons.dmi
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/Forerunner/sentinel_kit.dm
  code/modules/halo/Forerunner/sentinel_kit.dmi
  code/modules/halo/flood/flood.dm
  code/modules/halo/sounds/forerunner/sentDeath1.ogg
  code/modules/halo/sounds/forerunner/sentDeath2.ogg
  code/modules/halo/sounds/forerunner/sentDeath3.ogg
  code/modules/halo/sounds/forerunner/sentDeath4.ogg
  code/modules/halo/sounds/forerunner/sentFire.ogg
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/weapons/charged.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/dual_wielding.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/plas_turret.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/gun.dm
  code/modules/xenoarcheaology/effects/teleport.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/overmap.dm
Labels: enhancement/QOL, feature

#2214 Update CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping

#2225 Various Fixes and changes
  code/game/objects/items/devices/flash.dm
  code/modules/emotes/definitions/_mob.dm
  code/modules/emotes/definitions/audible.dm
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/Forerunner/sentinel_kit.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/misc/capture_node_mobs.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
Labels: Balancing, Bugfix

#2226 Active Covie Darkmode
  code/modules/halo/icons/species/Sangheili_Combat_Harness.dmi
  code/modules/halo/icons/species/grunt_gear.dmi
  code/modules/halo/turfs/covenant/Covvie_newwalls (1).dmi
  code/modules/halo/turfs/covenant/Covvie_newwalls.dmi
  maps/UNSC_Halberd_Class/areas.dm
Labels: enhancement/QOL, spriting

#2230 Small Balancing Changes
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/lmg.dm
Labels: Balancing

#2232 Minor Balancing and fixes
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: Balancing, Bugfix

#2234 brute armour kits
  code/modules/halo/structures/covvendors.dm
Labels: Bugfix, oversight

#2240 An array of balancing and bugfixes
  code/game/jobs/job_controller.dm
  code/modules/halo/covenant/plasma_drill.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/turfs/covenant/materials.dm
  code/modules/halo/weapons/ammo_boxes.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/smg.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/projectile/special.dm
Labels: Balancing, Bugfix

#2220 Donator Sprite Edits
  code/modules/halo/clothing/doneritems.dm
Labels: enhancement/QOL, merge conflicts

#2236 Verb Perm Fix
  code/modules/admin/verbs/grief_fixers.dm
Labels: ZAS, oversight, priority/med

#2243 middle mouse exploit
  code/_onclick/click.dm
  code/controllers/configuration.dm
  code/modules/client/client_procs.dm
  config/example/config.txt
Labels: Bugfix

#2245 Wow more fixes
  code/game/jobs/job_controller.dm
  code/game/objects/weapons.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/flood_infection_chem.dm
  code/modules/halo/misc/artifact_pinpointer.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Bugfix

#2249 Builder mobs
  baystation12.dme
  code/game/jobs/job_controller.dm
  code/modules/halo/mobs/builder.dm
  code/modules/halo/mobs/converter.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: feature

#2251 Achlys Lighting Fix
  maps/unsc_achlys/achlys_objects.dm
  maps/unsc_achlys/unsc_achlys_Z1.dmm
  maps/unsc_achlys/unsc_achlys_Z2.dmm
  maps/unsc_achlys/unsc_achlys_Z3.dmm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
Labels: Bugfix, priority/low

#2252 X-52 Sprite Fix
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/clothing/insurrectionists.dm
  maps/geminus_city/x52_outfits.dm
  maps/urf_flagship/first_deck.dmm
Labels: Bugfix, spriting

#2256 New 2.5D Walls
  code/modules/materials/materials.dm
  icons/turf/wall_masks.dmi
Labels: enhancement/QOL, feature, spriting

#2254 URF Defector orion sprites
  code/modules/halo/misc/Orion Project.dm
  code/modules/halo/species/orion.dm
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/innie_outfits.dm
Labels: enhancement/QOL

#2255 Species Language Colors
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/lekgolo_language.dm
  code/modules/halo/species_items/sanshyuum.dm
  code/stylesheet.dm
Labels: enhancement/QOL

#2262 Achlys & Flood Changes
  code/modules/halo/flood/flood.dm
  maps/unsc_achlys/achlys_areas.dm
  maps/unsc_achlys/achlys_gm.dm
  maps/unsc_achlys/achlys_objects.dm
  maps/unsc_achlys/unsc_achlys_Z3.dmm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
  sound/flood/infector_die1.ogg
  sound/flood/infector_die2.ogg
  sound/flood/infector_die3.ogg
Labels: Ready, enhancement/QOL, priority/low, spawns

#2264 Mobile spawns
  baystation12.dme
  code/__defines/build_marker_types.dm
  code/__defines/items_clothing.dm
  code/_helpers/global_access.dm
  code/modules/clothing/suits/armor.dm
  code/modules/halo/NPC/npc_overmind.dm
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/covenant/ammo_belt.dm
  code/modules/halo/custom_ai_objects/custom_ai_type.dm
  code/modules/halo/custom_ai_objects/cyberwarfare_commands.dm
  code/modules/halo/factions/npc_factions/flp_supply.dm
  code/modules/halo/factions/npc_factions/gao_supply.dm
  code/modules/halo/factions/npc_factions/khoros_supply.dm
  code/modules/halo/factions/npc_factions/olympus_supply.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/misc/Orion Project.dm
  code/modules/halo/mobs/builder.dm
  code/modules/halo/mobs/faction_builders.dm
  code/modules/halo/outfits/mobile_spawn_outfits.dm
  code/modules/halo/shuttles/pelican.dmi
  code/modules/halo/sounds/rafaj_donor/music_2.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_1.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_2.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_3.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_4.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_5.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_6.ogg
  code/modules/halo/sounds/rafaj_donor/voiceline_7.ogg
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/orion.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/squads/squad_camera_console.dm
  code/modules/halo/vehicles/mobile_spawn_datums.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/spirit.dmi
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/weapons/dual_wielding.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/reagents/dispenser/appearance.dm
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/Exoplanet Research/backup/ExoResearch_2.dmm
  maps/geminus_city/innie_outfits.dm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
  maps/urf_flagship/backup/first_deck.dmm
  maps/urf_flagship/first_deck.dmm
  test/run-test.sh
Labels: Bugfix, Ready, feature

#2273 Grunt movespeed changes
  code/modules/halo/species/grunts.dm
Labels: Balancing, enhancement/QOL

#2274 achlys no mobile respawn
  code/modules/halo/outfits/mobile_spawn_outfits.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/vehicles/mobile_spawn_datums.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/weapons/covenant/lmg.dm
  maps/CRS_Unyielding_Transgression/jobs.dm
  maps/unsc_achlys/achlys_gm.dm
Labels: Bugfix
