Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-09, with the labels that each got.

#2781 Teamwork update: suit sensors and new helmet camera system
  baystation12.dme
  code/__defines/items_clothing.dm
  code/datums/repositories/crew/crew.dm
  code/datums/repositories/crew/general.dm
  code/modules/clothing/clothing.dm
  code/modules/halo/covenant/structures_machines/crew_monitor.dm
  code/modules/halo/covenant/structures_machines/modular_computer.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/icons/machinery/computer_multi.dmi
  code/modules/halo/icons/machinery/holotable.dmi
  code/modules/halo/icons/machinery/modular_computer.dmi
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/supply/oni.dm
  code/modules/halo/supply/program/_program.dm
  code/modules/halo/supply/unsc.dm
  code/modules/halo/unsc/crew_monitor.dm
  code/modules/halo/unsc/modular_computer.dm
  code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
  code/modules/modular_computers/file_system/programs/medical/view_camera.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
  maps/npc_ships/req_console_ships/cov_tender.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_cheap.dmm
  maps/npc_ships/req_console_ships/unsc_heavyarmed.dmm
  maps/npc_ships/req_console_ships/unsc_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/unsc_podcarrier.dmm
  maps/npc_ships/req_console_ships/unsc_tender.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  nano/templates/crew_monitor.tmpl
Labels: feature

#2792 m7 fix
  code/modules/halo/machinery/gunvendors.dm
Labels: enhancement/QOL

#2795 Hellbringers - Part 1
  baystation12.dme
  code/modules/halo/icons/hell.dmi
  code/modules/halo/unsc/hellbringers.dm
  code/modules/halo/unsc/jobs/marines.dm
  code/modules/halo/unsc/jobs/marines_outfits.dm
  code/modules/halo/weapons/flamethrowers.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/ks7_elmsville/hud_icons.dmi
  maps/ks7_elmsville/jobdefs.dm
Labels: Ready, enhancement/QOL, feature, spriting

#2802 various general and moonbase related hotfixes
  .travis.yml
  baystation12.dme
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/halo/difficulty_setting.dm
  code/modules/halo/factions/quest/innie/transport_shuttle.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/machinery/pointbased_vendor.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/outfits/mobile_spawn_outfits.dm
  code/modules/halo/storage/pocketstorage.dm
  code/modules/halo/unsc/hellbringers.dm
  code/modules/halo/unsc/jobs/marines.dm
  code/modules/halo/weapons/M7.dm
  code/modules/halo/weapons/MA3.dm
  code/modules/halo/weapons/MA37.dm
  code/modules/halo/weapons/_guns.dm
  code/modules/halo/weapons/ammo_7-62mm.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/flamethrowers.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/overmap/sectors.dm
  maps/CRS_Unyielding_Transgression/overmap.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/base_assault/base_assault.dm
  maps/base_assault/unit_tests.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
  maps/faction_bases/CassiusMoonStation/cassiusmoon.dm
  maps/faction_bases/CassiusMoonStation/destroy_effects.dm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/jobdefs.dm
  maps/ks7_elmsville/ks7_elmsville.dm
  maps/ks7_elmsville/presets.dm
Labels: Balancing, enhancement/QOL, overmap

#2811 Post update fixes
  code/modules/halo/storage/pocketstorage.dm
  code/modules/halo/weapons/M7.dm
  code/modules/halo/weapons/flamethrowers.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
Labels: enhancement/QOL

#2813 unsc spawn relocate
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
  maps/faction_bases/CassiusMoonStation/areas.dm
Labels: Balancing

#2814 unsc spawn is no longer gay baby jail
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
Labels: Bugfix, ackchyually, priority/critical
