Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-04, with the labels that each got.

#2362 Innie fixes and tweaks
  code/modules/halo/factions/quest/_quest.dm
  code/modules/halo/factions/quest/quest_generate.dm
  maps/geminus_city/innie_quest/program_comms.dm
  maps/geminus_city/innie_quest/program_shuttle.dm
  maps/geminus_city/innie_quest/transport_shuttle.dm
Labels: Bugfix, enhancement/QOL

#2357 Minor fixes
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/storage/wallets.dm
  code/modules/halo/clothing/civilian.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/machinery/scanning_console.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/weapons/overmap_projectile.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/skirmisher_greaves.dm
  code/modules/halo/structures/covvendors.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/overmap/ships/ship.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/areas.dm
  maps/UNSC_Halberd_Class/halberdclass_new.dmi
  maps/_gamemodes/invasion/gamemode.dm
Labels: Bugfix

#2366 Nothing special I promise
  code/modules/halo/icons/species/grunt_gear.dmi
  code/modules/halo/icons/species/r_unggoy.dmi
Labels: ackchyually, feature

#2369 dual wield firing fix
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/dual_wielding.dm
  maps/_gamemodes/invasion/gamemode.dm
Labels: Bugfix

#2376 Covenant IDs
  baystation12.dme
  code/modules/halo/covenant/Cards.dmi
  code/modules/halo/covenant/cards.dm
  code/modules/halo/species_items/grunt_outfits.dm
  code/modules/halo/species_items/jiralhanae_outfit.dm
  code/modules/halo/species_items/kig-yar_outfits.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/halo/species_items/sanshyuum.dm
  code/modules/halo/species_items/skirmisher_outfits.dm
Labels: feature, priority/med

#2378 Insurrection missions fixes and improvements
  baystation12.dme
  code/controllers/Processes/obj.dm
  code/game/supplyshuttle.dm
  code/game/turfs/simulated/walls.dm
  code/modules/halo/doors/halo_doors.dm
  code/modules/halo/factions/__defs.dm
  code/modules/halo/factions/_controller.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/_globals.dm
  code/modules/halo/factions/hails.dm
  code/modules/halo/factions/objectives.dm
  code/modules/halo/factions/process.dm
  code/modules/halo/factions/quest/_quest.dm
  code/modules/halo/factions/quest/defenders.dm
  code/modules/halo/factions/quest/finish.dm
  code/modules/halo/factions/quest/loot.dm
  code/modules/halo/factions/quest/process.dm
  code/modules/halo/factions/quest/quest_finish.dm
  code/modules/halo/factions/quest/shuttle_instance.dm
  code/modules/halo/factions/quest/~undefs.dm
  code/modules/halo/factions/quest_finalise.dm
  code/modules/halo/factions/quest_generate.dm
  code/modules/halo/factions/rep_rewards.dm
  code/modules/halo/factions/supply.dm
  code/modules/halo/machinery/generic_door_subtype_defines.dm
  code/modules/halo/overmap/fusion_thruster.dmi
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/shuttles/shuttle.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/geminus_city/innie_quest/program_comms.dm
  maps/geminus_city/innie_quest/program_shuttle.dm
  maps/geminus_city/innie_quest/shuttle_fuel.dm
  maps/geminus_city/innie_quest/shuttle_power.dm
  maps/geminus_city/innie_quest/transport_area.dm
  maps/geminus_city/innie_quest/transport_shuttle.dm
  maps/geminus_city/invasion_geminus_unit_tests.dm
  maps/submaps/civilian/bank1.dmm
  maps/submaps/civilian/drugalug1.dmm
  maps/submaps/civilian/factory1.dmm
  maps/urf_flagship/first_deck.dmm
  maps/~mapsystem/maps_unit_testing.dm
  nano/templates/comms_innie.tmpl
  nano/templates/shuttle_innie.tmpl
Labels: Bugfix, Ready, enhancement/QOL, in-progress, mapping, priority/high

#2379 Bugfixes and Mapchanges
  baystation12.dme
  code/modules/halo/clothing/doner_item_base.dm
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_innie.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/covenant/energybarricade_vacuum.dm
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/icons/Energy Sword_inhand Human.dmi
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/species_items/yanmee_outfits.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/lighting/lighting_setup.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/Exoplanet Research/overmap.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/overmap.dm
  maps/urf_flagship/first_deck.dmm
Labels: Balancing, Bugfix

#2381 CRS Transgression fixes
  backup/unsc_achlys.dmm
  code/modules/halo/covenant/comms.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/areas.dm
Labels: Bugfix, mapping, priority/med

#2388 Vehicle ammo
  baystation12.dme
  code/game/objects/items.dm
  code/modules/halo/icons/machinery/rearm_repair_station.dmi
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/structures/covvendors.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/rearm_repair_station.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/halo/weapons/turrets/ammo.dm
  code/modules/mob/grab/normal/grab_normal.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/projectile.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/overmap.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
  maps/urf_flagship/first_deck.dmm
  maps/urf_flagship/overmap.dm
Labels: Balancing, enhancement/QOL, feature

#2382 Covenant submap additions & General fixes
  maps/submaps/areas.dm
  maps/submaps/civilian/bank1.dmm
  maps/submaps/civilian/drugalug1.dmm
  maps/submaps/civilian/factory1.dmm
  maps/submaps/covenant/backup/citadelle1.dmm
  maps/submaps/covenant/citadelle1.dmm
  maps/submaps/covenant/citadelle_admin.dmm
  maps/submaps/covenant/hidden_mine.dmm
  maps/submaps/covenant/no_mans_land.dmm
Labels: enhancement/QOL, mapping

#2411 ha ha vt9 go disappear
  baystation12.dme
  code/modules/halo/overmap/nav_data_computer.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/invasion_geminus.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL, feature

#2408 First Contact Tweaks
  baystation12.dme
  code/__defines/overmap.dm
  code/game/turfs/simulated/walls.dm
  code/modules/halo/overmap/req_console_ships.dm
  code/modules/overmap/ships/ship.dm
  icons/obj/guncabinet.dmi
  maps/CRS_Unyielding_Transgression/overmap.dm
  maps/Exoplanet Mining/overmap.dm
  maps/UNSC_Halberd_Class/overmap.dm
  maps/UNSC_With_Noble_Cause/overmap.dm
  maps/UNSC_With_Noble_Cause/presets.dm
  maps/faction_bases/civ_shuttle.dmm
  maps/first_contact/jobs.dm
  maps/first_contact/outfits.dm
  maps/kig_yar_pirates/missionary.dmm
  maps/ks7_elmsville/KS7_535_1.dmm
  maps/ks7_elmsville/areas.dm
  maps/ks7_elmsville/overmap.dm
  maps/ks7_elmsville/presets.dm
  maps/urf_flagship/overmap.dm
Labels: Balancing, enhancement/QOL
