Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-07, with the labels that each got.

#2605 Fix for perma-extended
  compile.sh
  maps/geminus_city/geminus_city_map.dm
Labels: Bugfix, enhancement/QOL

#2607 Jetpacks and various small changes
  baystation12.dme
  code/__defines/misc.dm
  code/game/atoms.dm
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/turfs/turf.dm
  code/modules/clothing/clothing.dm
  code/modules/halo/abilities/flight.dm
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/jetpack.dmi
  code/modules/halo/clothing/jetpacks.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/sangheili/sangheili.dm
  code/modules/halo/covenant/species/sanshyuum/sanshyuum.dm
  code/modules/halo/covenant/species/tvoan/skirmisher.dm
  code/modules/halo/covenant/species/unggoy/grunt.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/misc/explosion_cratering.dm
  code/modules/halo/misc/explosion_craters.dmi
  code/modules/halo/mobs/movement_sfx.dm
  code/modules/halo/sounds/conc_rifle_explode.ogg
  code/modules/halo/sounds/conc_rifle_fire.ogg
  code/modules/halo/sounds/jetpack_move.ogg
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/unsc/hrunting.dm
  code/modules/halo/unsc/spartan.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/halo/weapons/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/icons/Covenant_Projectiles.dmi
  code/modules/halo/weapons/icons/jiralhanae_gear.dmi
  code/modules/halo/weapons/icons/jiralhanae_obj_large.dmi
  code/modules/halo/weapons/launchers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/life.dm
  code/modules/mob/mob_movement.dm
  code/modules/multiz/movement.dm
  code/modules/projectiles/gun_overheat.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: Bugfix, enhancement/QOL, feature

#2612 Misc minor fixes and tweaks
  code/datums/browser.dm
  code/game/jobs/job/job.dm
  code/game/machinery/kitchen/cooking_machines/_cooker.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/species/tvoan/skirmisher.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon.dm
  code/modules/halo/unsc/jobs/ONI.dm
  code/modules/halo/unsc/jobs/ai.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/operation_trebuchet/UNSC_Yolotanker/jobs.dm
Labels: Bugfix, enhancement/QOL

#2613 Various tweaks and additions
  baystation12.dme
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/covenant/invasion_scanner.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj_heavy.dmi
  code/modules/halo/covenant/species/tvoan/skirmisher.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/mobs/movement_sfx.dm
  code/modules/halo/overmap/automated_defense.dm
  code/modules/halo/overmap/icons/Sparrowhawk.dmi
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/sounds/banshee_move.ogg
  code/modules/halo/sounds/sparrowhawk_move.ogg
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/structures/barbedwire.dm
  code/modules/halo/vehicles/types/banshee.dm
  code/modules/halo/vehicles/types/banshee.dmi
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/sparrowhawk.dm
  code/modules/halo/vehicles/types/sparrowhawk.dmi
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/jiralhanae_gear.dmi
  code/modules/halo/weapons/icons/jiralhanae_obj.dmi
  code/modules/halo/weapons/icons/jiralhanae_obj_large.dmi
  code/modules/mob/living/life.dm
  code/modules/projectiles/projectile/bullets.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: enhancement/QOL, feature

#2630 Misc bugfixes and tweaks
  code/_onclick/hud/hud.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/machinery/autosurgeon/autosurgeon.dm
  code/modules/halo/machinery/autosurgeon/interact_hand.dm
  code/modules/halo/machinery/autosurgeon/surgery_internal.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/research/_global.dm
  code/modules/halo/research/computer_program/ui_SelectedTech.dm
  code/modules/halo/research/designs/weapons.dm
  code/modules/halo/research/machines/protolathe/_protolathe.dm
  code/modules/halo/research/research_database.dm
  code/modules/halo/research/techprint/_techprint.dm
  code/modules/halo/research/techprint/strings.dm
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/halo/weapons/spartan_laser.dm
  maps/_gamemodes/firefight/resupply_crates.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
Labels: Bugfix, enhancement/QOL

#2635 Bugfixes
  code/controllers/configuration.dm
  code/game/jobs/job/job.dm
  code/modules/halo/research/computer_program/destruct.dm
  code/modules/halo/research/techprint/destruct.dm
  code/modules/mob/observer/ghost/ghost.dm
  maps/_gamemodes/_popbalance.dm
Labels: Bugfix

#2636 Brain will now die 4x faster from oxyloss
  code/modules/organs/internal/brain.dm
Labels: enhancement/QOL

#2642 Fix Embedded Grenades Causing Immortality
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Bugfix, Ready

#2647 stabilises weapon rifling
  code/game/atoms.dm
  code/game/turfs/turf.dm
  code/modules/halo/elevation_overrides/atom.dm
Labels: Bugfix

#2648 Adds server admin verb to reload config files
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/world.dm
Labels: enhancement/QOL

#2646 Research fixes and improvements
  baystation12.dme
  code/game/machinery/computer/computer.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/machinery.dm
  code/modules/halo/research/_global.dm
  code/modules/halo/research/computer_program/destruct.dm
  code/modules/halo/research/designs/_designs.dm
  code/modules/halo/research/designs/circuits.dm
  code/modules/halo/research/designs/computers/drive.dm
  code/modules/halo/research/designs/computers/drive_portable.dm
  code/modules/halo/research/designs/computers/drive_tablet.dm
  code/modules/halo/research/designs/computers/processor.dm
  code/modules/halo/research/designs/computers/processor_tablet.dm
  code/modules/halo/research/designs/glasses_huds.dm
  code/modules/halo/research/designs/misc_circuits.dm
  code/modules/halo/research/designs/stock_parts.dm
  code/modules/halo/research/designs/weapons.dm
  code/modules/halo/research/faction.dm
  code/modules/halo/research/helpers.dm
  code/modules/halo/research/machines/_research.dm
  code/modules/halo/research/machines/destructive.dm
  code/modules/halo/research/machines/destructive_build.dm
  code/modules/halo/research/machines/dissembler.dm
  code/modules/halo/research/machines/dissembler_build.dm
  code/modules/halo/research/machines/heavy_lathe.dmi
  code/modules/halo/research/machines/protolathe/_protolathe.dm
  code/modules/halo/research/machines/protolathe/build.dm
  code/modules/halo/research/machines/protolathe/circuit_imprinter.dm
  code/modules/halo/research/machines/protolathe/components.dm
  code/modules/halo/research/machines/protolathe/craft.dm
  code/modules/halo/research/machines/protolathe/interact.dm
  code/modules/halo/research/machines/protolathe/materials.dm
  code/modules/halo/research/machines/protolathe/process.dm
  code/modules/halo/research/machines/protolathe/reagents.dm
  code/modules/halo/research/machines/protolathe/resources.dm
  code/modules/halo/research/machines/protolathe/ui.dm
  code/modules/halo/research/machines/protolathe/ui_strings.dm
  code/modules/halo/research/machines/research.dmi
  code/modules/halo/research/techprint/types/computer/computer_processing.dm
  code/modules/halo/research/techprint/types/computer/data_storage.dm
  code/modules/halo/research/techprint/types/computer_hardware.dm
  code/modules/halo/research/techprint/types/core/lasers.dm
  code/modules/halo/research/techprint/types/core/sensors.dm
  code/modules/halo/research/techprint/types/covenant_armour_shields.dm
  code/modules/halo/research/techprint/types/tablet_hardware.dm
  code/modules/halo/research/techprint/unknown.dm
  code/unit_tests/map_tests.dm
Labels: Bugfix, enhancement/QOL, feature

#2651 The Big Grunty PR
  baystation12.dme
  code/game/turfs/simulated/floor_acts.dm
  code/modules/clothing/clothing.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/covenant/items/Cards.dmi
  code/modules/halo/covenant/items/cards.dm
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/species/kigyar/kig-yar.dm
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/species/unggoy/_grunt.dm
  code/modules/halo/covenant/species/unggoy/armour.dm
  code/modules/halo/covenant/species/unggoy/clothing.dm
  code/modules/halo/covenant/species/unggoy/grunt_gear.dmi
  code/modules/halo/covenant/species/unggoy/grunt_outfits.dm
  code/modules/halo/covenant/species/unggoy/rebreather.dm
  code/modules/halo/covenant/species/unggoy/tank.dm
  code/modules/halo/covenant/species/unggoy/~undefs.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: Balancing, Bugfix, enhancement/QOL, spriting

#2662 Minor research fixes
  code/modules/halo/research/machines/protolathe/_protolathe.dm
  code/modules/halo/research/machines/protolathe/build.dm
  code/modules/halo/research/machines/protolathe/circuit_imprinter.dm
  code/modules/halo/research/techprint/strings.dm
Labels: Bugfix

#2663 Mostly covenant fixes and tweaks
  baystation12.dme
  code/modules/halo/covenant/species/kigyar/kig-yar.dm
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/species/kigyar/kigyar_ranger.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_armour.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_greaves.dm
  code/modules/halo/covenant/species/unggoy/armour.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/insurrection/soe_jobs.dm
  code/modules/halo/insurrection/soe_outfits.dm
  code/modules/halo/medicine/firstaid.dm
  maps/SOE_Argentum/includes.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/geminus_city/invasion_geminus_unit_tests.dm
Labels: Bugfix, enhancement/QOL

#2664 Fixes mining drill runtime error
  code/modules/mining/drilling/drill.dm
Labels: Bugfix

#2659 Various bugfixes and item tweaks
  baystation12.dme
  code/game/objects/effects/explosion_particles.dm
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/halo/abilities/flight.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/turfs/interiorstructures.dm
  code/modules/halo/unsc/jobs/ai.dm
  code/modules/halo/unsc/jobs/spartan_two.dm
  code/modules/halo/vehicles/vehicle_occupant.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/automated_AA.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/shield_gauntlet_effect.dm
  code/modules/halo/weapons/icons/automated_anti_air.dmi
  code/modules/halo/weapons/rifles.dm
  code/modules/multiz/movement.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/attachment_profiles.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: Bugfix, enhancement/QOL, feature

#2665 Shouting bang will no longer delete ODP floor
  code/game/turfs/simulated/floor_acts.dm
Labels: Bugfix

#2667 BR tweak
  code/modules/halo/abilities/flight.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/covenant/items/ammo_belt.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/weapons/rifles.dm
Labels: enhancement/QOL

#2675 Minor lagfix tweaks and balance modifications
  code/modules/halo/abilities/flight.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/overmap/sectors.dm
Labels: Balancing

#2674 Misc Tweaks
  code/modules/admin/admin_verbs.dm
  code/modules/customitems/item_spawning.dm
  code/modules/halo/clothing/armor_repair/clothing.dm
  code/modules/halo/covenant/airlocks/multitile_airlocks.dm
  code/modules/halo/research/designs/_designs.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/materials/materials.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/organs/internal/brain.dm
Labels: Bugfix, enhancement/QOL

#2679 Vehicle tweaks
  code/modules/halo/vehicles/types/banshee.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/sparrowhawk.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Balancing

#2700 Tweakfixes
  baystation12.dme
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/colonist/jobs.dm
  code/modules/halo/research/machines/protolathe/components.dm
  code/modules/halo/research/techprint/types/computer/computer_processing.dm
  code/modules/halo/research/techprint/types/core/biology.dm
  code/modules/halo/research/techprint/types/core/energy_storage.dm
  code/modules/halo/research/techprint/types/core/lasers.dm
  code/modules/halo/research/techprint/types/core/sensors.dm
  code/modules/halo/shuttles/pelican.dmi
  code/modules/halo/unsc/jobs/colonist.dm
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/halo/vehicles/mobile_spawn_datums.dm
  code/modules/halo/vehicles/types/spirit.dmi
  code/modules/halo/vehicles/vehicle_cargo.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: Bugfix, enhancement/QOL
