Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-06, with the labels that each got.

#2467 Critical Reclamation Fix + NPC vehicle stuff
  code/modules/halo/covenant/invasion_scanner.dm
  code/modules/halo/covenant/invasion_scanner_pinpointers.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/kigyar/kig-yar.dm
  code/modules/halo/covenant/species/sangheili/sangheili.dm
  code/modules/halo/covenant/species/sanshyuum/sanshyuum.dm
  code/modules/halo/covenant/species/tvoan/skirmisher.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/misc/atom_despawner.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/mobs/simple_mob_ai.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/unsc/spartan.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/hostile/commanded/commanded.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: bug, enhancement/QOL

#2469 atom despawner overflow changes
  code/modules/halo/misc/atom_despawner.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: bug

#2470 makes scan-progress msg transmit on SQUAD comms
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/grenades.dm
  maps/_gamemodes/invasion/gamemode.dm
Labels: enhancement/QOL

#2475 dumb AI chip for anti smart AI
  baystation12.dme
  code/game/machinery/doors/airlock.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/custom_ai_objects/custom_ai_type.dm
  code/modules/halo/custom_ai_objects/cyberwarfare.dm
  code/modules/halo/custom_ai_objects/cyberwarfare_commands.dm
  code/modules/halo/custom_ai_objects/dumb_ai_chip.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/research/rdconsole.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
Labels: bug, enhancement/QOL, feature

#2478 ML QoL Adjustments
  maps/unsc_achlys/achlys_jobs.dm
  maps/unsc_achlys/unsc_achlys_Z1.dmm
  maps/unsc_achlys/unsc_achlys_Z2.dmm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
  maps/unsc_achlys/unsc_dante_Z1.dmm
Labels: enhancement/QOL, mapping, not a bug, oversight, priority/low

#2476 Adds custom radio message admin verb
  baystation12.dme
  code/game/objects/items/devices/radio/radio.dm
  code/modules/halo/admin/_verbs.dm
  code/modules/halo/admin/difficulty.dm
  code/modules/halo/admin/ert_ship_spawn.dm
  code/modules/halo/admin/fleet_spawn.dm
  code/modules/halo/admin/radio_message.dm
  code/modules/halo/admin/spawn_conversion.dm
  code/modules/halo/admin/start_flood_attack.dm
  code/modules/halo/admin/truce.dm
  code/modules/halo/factions/announce.dm
Labels: Ready, feature

#2474 Some Reclamation refactors and tweaks
  baystation12.dme
  code/modules/halo/colonist/jobs.dm
  code/modules/halo/colonist/outfits.dm
  code/modules/halo/insurrection/innie_antag.dm
  code/modules/halo/insurrection/innie_jobs.dm
  code/modules/halo/insurrection/innie_outfits.dm
  code/modules/halo/insurrection/x52_jobs.dm
  code/modules/halo/insurrection/x52_outfits.dm
  code/modules/halo/insurrection/x52_spawns.dm
  code/modules/halo/misc/bumpstairs.dm
  code/modules/halo/misc/bumpstairs_oni.dm
  code/modules/halo/misc/bumpstairs_road.dm
  code/modules/halo/misc/bumpstairs_room.dm
  code/modules/halo/misc/bumpstairs_sewer.dm
  code/modules/halo/misc/faction_banner.dm
  code/modules/halo/misc/fakewall.dm
  code/modules/halo/misc/ramps.dmi
  code/modules/halo/misc/sewer_tunnel_thin.dm
  code/modules/halo/unsc/jobs/colonists.dm
  code/modules/halo/unsc/jobs/colonists_outfits.dm
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/halo/unsc/jobs/marines.dm
  maps/Admin
  maps/Covenant
  maps/Exoplanet
  maps/Research
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/faction_bases/geminus_innie_base/areas.dm
  maps/faction_bases/geminus_innie_base/geminus_innie_base.dmm
  maps/faction_bases/geminus_innie_base/overmap.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_city_spawns.dm
  maps/geminus_city/innie_spawns.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/geminus_city/x52_spawns.dm
  maps/operation_trebuchet/insurrection_outfits.dm
Labels: Ready, enhancement/QOL

#2481 scanner destruction messages
  maps/_gamemodes/invasion/gamemode.dm
Labels: enhancement/QOL

#2473 [DNM] Partial remapping of Geminus
  maps/geminus_city/areas.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: Do Not Merge, enhancement/QOL, in-progress, mapping

#2482 Fix or update UNSC and Cov requisition subships
  maps/npc_ships/req_console_ships/cov_cheap.dmm
  maps/npc_ships/req_console_ships/cov_heavyarmed.dmm
  maps/npc_ships/req_console_ships/cov_laserplatform_experimental.dmm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
  maps/npc_ships/req_console_ships/cov_tender.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_cheap.dmm
  maps/npc_ships/req_console_ships/unsc_heavyarmed.dmm
  maps/npc_ships/req_console_ships/unsc_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/unsc_podcarrier.dmm
  maps/npc_ships/req_console_ships/unsc_tender.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
Labels: Bugfix, enhancement/QOL, mapping

#2486 dumb ai incompatible cyberwarfare commands
  code/game/machinery/vending.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/covenant/species/kigyar/clothing.dm
  code/modules/halo/covenant/species/kigyar/skirm_clothing.dmi
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirm_clothing.dmi
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/custom_ai_objects/custom_ai_type.dm
  code/modules/halo/machinery/ammo_fabricator.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/smg.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/gun.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/_gamemodes/invasion/gamemode.dm
  maps/geminus_city/areas.dm
  maps/kig_yar_pirates/presets.dm
Labels: Balancing, Bugfix, enhancement/QOL

#2485 Geminus ONI base plus general Reclamation tweaks and fixes
  baystation12.dme
  code/game/jobs/job_controller.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/bump_teleporter.dm
  code/game/objects/effects/landmarks.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/halo/misc/artifact_spawn.dm
  code/modules/halo/misc/artifact_spawn.dmi
  code/modules/halo/misc/bumpstairs.dm
  code/modules/halo/misc/faction_banner.dm
  code/modules/halo/misc/sewer_tunnel_thin.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/shuttles/dropship_landing_points.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/unsc/access.dm
  code/modules/halo/unsc/jobs/ONI.dm
  code/modules/halo/unsc/jobs/_base.dm
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/landmark.dmi
  code/modules/paperwork/faxmachine.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/spawnpoint.dm
  maps/faction_bases/complex046/complex046.dm
  maps/faction_bases/complex046/complex046.dmi
  maps/faction_bases/complex046/complex046.dmm
  maps/faction_bases/complex046/complex046_area.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/faction_bases/rabbit_hole_base/areas.dm
  maps/faction_bases/rabbit_hole_base/overmap.dm
  maps/faction_bases/rabbit_hole_base/rabbit_hole_base.dmm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: Bugfix, enhancement/QOL, feature, mapping, spawns

#2492 Little maptweaks
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/icons/machinery/rearm_repair_station.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/areas.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: enhancement/QOL, mapping

#2493 Brute fixes and additions
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj_heavy.dmi
  code/modules/halo/sounds/mauler_firing.ogg
  code/modules/halo/weapons/covenant/brute.dm
Labels: enhancement/QOL, spriting

#2494 Dropship sealing and auto-generated drop markers
  code/game/machinery/cryo.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, feature

#2495 pilot noslip
  code/modules/mob/mob_movement.dm
Labels: bug

#2501 Third Attempt to Fix Brute Uniforms
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
Labels: Bugfix

#2504 Tvoan Re-sprite
  code/modules/halo/covenant/species/kigyar/clothing.dm
  code/modules/halo/covenant/species/kigyar/jackalclothing.dmi
  code/modules/halo/covenant/species/kigyar/kig-yar.dm
  code/modules/halo/covenant/species/kigyar/r_kig-yar.dmi
  code/modules/halo/covenant/species/kigyar/ranger_kigyar.dmi
  code/modules/halo/covenant/species/kigyar/ranger_tvoan.dmi
  code/modules/halo/covenant/species/tvoan/r_skirmishers.dmi
  code/modules/halo/covenant/species/tvoan/skirm_clothing.dmi
  code/modules/halo/covenant/species/tvoan/skirm_fullsprite.dmi
  code/modules/halo/covenant/species/tvoan/skirmisher.dm
Labels: enhancement/QOL, spriting

#2496 minor bugfixes to vehicles and dumb ais
  code/modules/halo/abilities/dodge_roll.dm
  code/modules/halo/custom_ai_objects/dumb_ai_chip.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Do Not Merge, bug, enhancement/QOL

#2505 lunge stun and barricade tweaks
  code/game/objects/items.dm
  code/modules/halo/covenant/structures_machines/energybarricade.dm
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/structures/barricade.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: Balancing, enhancement/QOL

#2500 ODP Cassius lower deck atmospherics and other Reclamation tweaks/fixes
  code/datums/repositories/follow.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/atmospherics/components/unary/vent_scrubber.dm
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/materials/material_recipes.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/areas.dm
  maps/geminus_city/geminus_hud_icons.dmi
Labels: Bugfix, Ready, enhancement/QOL, feature, mapping

#2512 Fixes and re-enables NPC fleet spawning (as UNSC only)
  baystation12.dme
  code/modules/halo/admin/fleet_spawn.dm
  code/modules/halo/factions/fleet_handling.dm
  code/modules/halo/factions/npc_fleet.dm
  code/modules/halo/factions/process.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/npc_fleets.dm
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/overmap/ships/ship.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
Labels: Bugfix

#2513 Updated Sprites & Covenant Smoke Grenade
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/covenant/drop_pod_beacon.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
Labels: enhancement/QOL, feature, spriting

#2515 Covenant Medical Resprites
  baystation12.dme
  code/modules/halo/covenant/medical/first_aid.dm
  code/modules/halo/covenant/medical/health_analyser.dm
  code/modules/halo/covenant/medical/medical.dmi
  code/modules/halo/covenant/medical/medkits.dm
  code/modules/halo/covenant/medical/pills.dm
Labels: enhancement/QOL, spriting

#2514 Additions as part of a minor/medium rework of spartan gear.
  baystation12.dme
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/halo/unsc/items.dmi
  code/modules/halo/unsc/spartan_hardsuits.dm
  icons/mob/rig_back.dmi
  icons/mob/rig_modules.dmi
Labels: Ready, enhancement/QOL, feature, in-progress

#2519 New sprite for barricades
  code/modules/halo/covenant/species/kigyar/jackalclothing.dmi
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/species/kigyar/kigyar_ranger.dm
  code/modules/halo/covenant/species/kigyar/ranger_kigyar.dmi
  code/modules/halo/covenant/species/kigyar/ranger_tvoan.dmi
  code/modules/halo/covenant/species/tvoan/skirm_clothing.dmi
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/structures/barricade.dm
  code/modules/halo/structures/structures.dmi
  maps/_gamemodes/firefight/materials.dm
Labels: enhancement/QOL, spriting

#2520 Minor fixes to Geminus
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, mapping

#2522 Prophet Chair + Vehicle Fixes
  baystation12.dme
  code/game/objects/structures/window.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/sangheili/sangheili.dm
  code/modules/halo/unsc/spartan.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/throne.dmi
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Bugfix, enhancement/QOL

#2528 prophet throne spritefix and co's sword/magnum
  code/modules/halo/abilities/dodge_roll.dm
  code/modules/halo/custom_ai_objects/dumb_ai_chip.dm
  code/modules/halo/flood/flood_spawn.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/unsc/jobs/officers_outfits.dm
  code/modules/halo/vehicles/supply_pods.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/_external_icons.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/unsc_achlys/achlys_objects.dm
Labels: Bugfix, enhancement/QOL

#2526 Pop balancing
  baystation12.dme
  code/game/jobs/job/job.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/unsc/jobs/ODST.dm
  code/modules/halo/unsc/jobs/marines.dm
  code/modules/halo/unsc/jobs/officers.dm
  maps/_gamemodes/_popbalance.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
Labels: Balancing, Ready, feature

#2531 Makes tech floors tileable
  baystation12.dme
  code/modules/halo/structures/citymapturfs.dm
  code/modules/halo/turfs/floor_tech.dmi
  code/modules/halo/turfs/tech_floors.dm
  code/modules/halo/turfs/tile.dmi
  maps/faction_bases/complex046/complex046.dmm
Labels: feature, mapping

#2534 Unlocks two spartan slots in phase 2
  code/modules/halo/factions/fleet_handling.dm
  code/unit_tests/map_tests.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: Balancing

#2536 Significant ODP map changes including UNSC AI, upper deck atmos, external airlock
  code/controllers/communications.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/embedded_controller/embedded_controller_base.dm
  code/game/mecha/mech_sensor.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/halo/unsc/jobs/ai.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/ai_items.dm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL, feature, mapping

#2537 Fix for latejoin pop balancing
  code/game/jobs/job/job.dm
Labels: Bugfix

#2539 Misc Reclamation tweaks and fixes
  code/modules/halo/factions/fleet_handling.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: Balancing, Bugfix, mapping

#2540 Various tweaks and fixes
  baystation12.dme
  code/modules/halo/Forerunner/knight.dm
  code/modules/halo/Forerunner/knight.dmi
  code/modules/halo/Forerunner/species/knight/knight.dm
  code/modules/halo/Forerunner/species/knight/knight.dmi
  code/modules/halo/Forerunner/species/knight/knight_armour.dm
  code/modules/halo/Forerunner/species/knight/knight_armour.dmi
  code/modules/halo/Forerunner/species/knight/knight_blood.dmi
  code/modules/halo/Forerunner/species/knight/knight_dam.dmi
  code/modules/halo/Forerunner/species/knight/knight_outfit.dm
  code/modules/halo/Forerunner/species/knight/knight_template.dmi
  code/modules/halo/Forerunner/watcher.dm
  code/modules/halo/Forerunner/watcher.dmi
  code/modules/halo/abilities/knight_tp.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/covenant/simple_mobs/_covenant.dm
  code/modules/halo/covenant/species/sanshyuum/clothing.dm
  code/modules/halo/covenant/turfs/floor.dm
  code/modules/halo/sounds/binaryrifle_fire.ogg
  code/modules/halo/sounds/binaryrifle_reload.ogg
  code/modules/halo/sounds/boltshot_fire.ogg
  code/modules/halo/sounds/boltshot_reload.ogg
  code/modules/halo/sounds/boltshot_sg_fire.ogg
  code/modules/halo/sounds/species_pain_screams/knightscream.ogg
  code/modules/halo/sounds/species_pain_screams/knightscream2.ogg
  code/modules/halo/sounds/species_pain_screams/knightscream3.ogg
  code/modules/halo/sounds/suppressor_fire.ogg
  code/modules/halo/sounds/suppressor_reload.ogg
  code/modules/halo/turfs/forerunner/floor.dm
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/halo/vehicles/types/throne.dmi
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/halo/weapons/forerunner/boxes.dm
  code/modules/halo/weapons/forerunner/grenade.dm
  code/modules/halo/weapons/forerunner/melee.dm
  code/modules/halo/weapons/forerunner/pistols.dm
  code/modules/halo/weapons/forerunner/rifles.dm
  code/modules/halo/weapons/forerunner/snipers.dm
  code/modules/halo/weapons/icons/forerunner_sprites.dmi
  code/modules/halo/weapons/icons/forerunner_sprites64.dmi
  code/modules/halo/weapons/icons/forerunner_sprites_inhand_l.dmi
  code/modules/halo/weapons/icons/forerunner_sprites_inhand_r.dmi
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Balancing, Bugfix, enhancement/QOL, feature

#2541 moves flood SA types into their own files, nerfs marine, sangheili, o…
  baystation12.dme
  code/modules/halo/flood/flood.dm
  code/modules/halo/flood/types/achlys.dm
  code/modules/halo/flood/types/carrier.dm
  code/modules/halo/flood/types/combat_form.dm
  code/modules/halo/flood/types/human.dm
  code/modules/halo/flood/types/infestor.dm
  code/modules/halo/flood/types/pure.dm
  code/modules/halo/flood/types/sangheili.dm
Labels: Balancing

#2549 More silence bug debugging
  code/_helpers/game.dm
  code/_helpers/unsorted.dm
  code/modules/mob/living/say.dm
Labels: bug

#2546 Plasma weapon overheating
  baystation12.dme
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_overheat.dm
  code/modules/projectiles/guns/energy.dm
Labels: Bugfix, enhancement/QOL

#2545 hypospray faction-check
  code/modules/halo/Forerunner/knight.dmi
  code/modules/halo/Forerunner/species/knight/knight.dmi
  code/modules/halo/Forerunner/species/knight/knight_armour.dmi
  code/modules/halo/Forerunner/watcher.dmi
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/icons/forerunner_sprites.dmi
  code/modules/halo/weapons/icons/forerunner_sprites64.dmi
  code/modules/halo/weapons/icons/forerunner_sprites_inhand_l.dmi
  code/modules/halo/weapons/icons/forerunner_sprites_inhand_r.dmi
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: enhancement/QOL

#2552 Fix a bug with burst fire weapons not bursting
  code/modules/projectiles/gun.dm
Labels: Bugfix

#2555 Various fixes and changes
  code/game/machinery/recharger.dm
  code/game/machinery/vending.dm
  code/game/objects/weapons.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/outfits/mobile_spawn_outfits.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/melee.dm
  code/modules/projectiles/guns/energy.dm
Labels: Balancing, enhancement/QOL

#2556 sane overheating
  code/modules/projectiles/gun_overheat.dm
Labels: Balancing

#2557 less nade choice
  code/_helpers/unsorted.dm
  code/game/machinery/vending.dm
  code/game/mecha/combat/Hrunting.dm
  code/game/mecha/mecha.dm
  code/modules/halo/covenant/items/ammo_belt.dm
  code/modules/halo/difficulty_setting.dm
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/launchers.dm
  code/modules/overmap/ships/ship.dm
  code/modules/projectiles/guns/projectile.dm
Labels: Balancing

#2559 Possible fix for silence and immortality bug
  code/modules/halo/overmap/npc_shipmap_handler.dm
Labels: Bugfix

#2560 Takes op:rf, brutecraft and achlys out of the map rotation
  .travis.yml
  maps/ccs_battlecruiser/includes.dm
  maps/doisac/includes.dm
  maps/unsc_achlys/includes.dm
Labels: enhancement/QOL

#2562 chem OD balancing
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: Balancing, enhancement/QOL

#2575 Fix for autobalance still counting dead players as alive
  code/game/jobs/job/job.dm
Labels: Bugfix

#2578 Multiple fixes, tweaks and enhancements (mostly to structures)
  code/game/objects/items/stacks/stack.dm
  code/modules/detectivework/forensics.dm
  code/modules/halo/covenant/materials.dm
  code/modules/halo/doors/halo_doors.dm
  code/modules/halo/doors/halo_multitile.dm
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/structures/sandbag.dm
  code/modules/halo/structures/tanktrap.dm
  code/modules/materials/material_recipes.dm
  code/modules/multiz/turf.dm
Labels: Balancing, Bugfix, enhancement/QOL

#2590 some balance changes
  baystation12.dme
  code/game/machinery/bioprinter.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/halo/chemicals/recipes.dm
  code/modules/halo/covenant/items/ammo_belt.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/halo/weapons/covenant/shield_gauntlet_effect.dm
  code/modules/mob/living/living_defense.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: Balancing, enhancement/QOL

#2600 ai access airlock fix
  code/game/machinery/doors/airlock.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Bugfix
