Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-08, with the labels that each got.

#2711 Reverts a vehicle movement tweak that has led to inconsistent vehicle movement
  code/modules/halo/vehicles/vehiclebase.dm
Labels: Bugfix

#2716 Various QoL and maptweaks for loadouts and ks7
  baystation12.dme
  code/game/machinery/vending.dm
  code/modules/halo/abilities/flight.dm
  code/modules/halo/misc/equipment_loadouts.dm
  code/modules/halo/overmap/nav_data_computer.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/mob/living/life.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
Labels: Balancing, enhancement/QOL, oversight

#2713 Gameplay Tweaks
  code/game/objects/effects/bump_teleporter.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/misc/bumpstairs.dm
  code/modules/halo/misc/bumpstairs_oni.dm
  code/modules/halo/misc/bumpstairs_road.dm
  code/modules/halo/shuttles/dropship_landing_points.dm
  code/modules/halo/unsc/jobs/officers.dm
  code/modules/halo/vehicles/vehicle_cargo.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/objectives.dm
  maps/faction_bases/complex046/complex046.dm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL

#2725 Tweaks
  code/modules/halo/covenant/species/lekgolo/lekgolo_attack.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/fleet_handling.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/factions/process.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/covenant_pods.dmi
  code/modules/halo/vehicles/vehicle_cargo.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
Labels: Balancing, enhancement/QOL

#2738 Bugfixes and tweaks
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/floor_acts.dm
  code/game/turfs/simulated/floor_damage.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/modules/halo/covenant/access.dm
  code/modules/halo/covenant/jobs/AI.dm
  code/modules/halo/covenant/jobs/huragok.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/jobs/sanshyuum.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/jobs/yanmee.dm
  code/modules/halo/covenant/turfs/floor.dm
  code/modules/halo/covenant/turfs/floors.dmi
  code/modules/halo/overmap/slipspace/covenant.dm
  code/modules/halo/turfs/floor_tech.dmi
  code/modules/halo/turfs/tech_floors.dm
  code/modules/halo/unsc/jobs/colonist.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/ks7_elmsville/hud_icons.dmi
  maps/ks7_elmsville/jobdefs.dm
Labels: Bugfix, enhancement/QOL, spawns

#2739 Bugfixes and tweaks
  code/modules/halo/vehicles/vehiclebase_air.dm
Labels: Bugfix, Vehicles

#2740 KS7 maptweaks + brute changes
  code/modules/halo/clothing/marine.dm
  code/modules/halo/covenant/items/ammo_belt.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/weapons/smg.dm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
  maps/ks7_elmsville/presets_pvp_additions.dm
Labels: Balancing, enhancement/QOL

#2755 Tweaks and fixes
  baystation12.dme
  code/modules/halo/covenant/species/unggoy/grunt_gear.dmi
  code/modules/halo/structures/ODST_Droppod.dmi
  code/modules/halo/vehicles/mobile_spawn_datums.dm
  code/modules/halo/vehicles/types/ODST_Droppod.dmi
  code/modules/halo/vehicles/types/SOEIV.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/bumblebee_full.dmi
  code/modules/halo/vehicles/types/cov_droppod.dmi
  code/modules/halo/vehicles/types/covenant_pods.dmi
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/drop_pod_covenant.dm
  code/modules/halo/vehicles/types/drop_pod_covenant.dmi
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: Bugfix, enhancement/QOL, spriting

#2756 support call-ins
  baystation12.dme
  code/modules/halo/icons/evac_zones.dmi
  code/modules/halo/leader_support/job_overrides.dm
  code/modules/halo/leader_support/supply_drop.dm
  code/modules/halo/leader_support/supply_drop_evac.dm
  code/modules/halo/leader_support/supply_drop_shieldgen.dm
  code/modules/halo/leader_support/supply_drop_tachud.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/leader_support/support_item.dm
  code/modules/halo/leader_support/support_options.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/warthog.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/complex046/complex046.dmm
  nano/templates/leader_support_item.tmpl
Labels: enhancement/QOL, feature

#2764 ODP Replacement + minor bugfixes/tweaks
  code/game/machinery/doors/airlock.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/doors/3xblastdoors/3xblastdoors_normal.dmi
  code/modules/halo/doors/halo_multitile.dm
  code/modules/halo/leader_support/supply_drop_evac.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/misc/loot_distributor.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/misc/payload.dmi
  code/modules/halo/unsc/jobs/_base.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/launchers.dm
  code/modules/hydroponics/seed.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/ODP_Cassius/new_areas.dm
  maps/faction_bases/ODP_Cassius/presets.dm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
Labels: Balancing, Bugfix, enhancement/QOL, feature

#2765 gives odp cassius a way to be destroyed
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: Bugfix

#2766 Minor vendor tweaks and QOL map additions
  .travis.yml
  baystation12.dme
  code/game/objects/items/weapons/grenades/grenade.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/nano_template_backup/leader_support_item.tmpl
  code/modules/halo/weapons/covenant/grenades.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: Balancing, enhancement/QOL, oversight

#2771 Covenant cargo shuttle
  baystation12.dme
  code/modules/economy/Accounts.dm
  code/modules/halo/covenant/access.dm
  code/modules/halo/covenant/jobs/huragok.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/jobs/sanshyuum.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/jobs/yanmee.dm
  code/modules/halo/covenant/structures_machines/consoles.dmi
  code/modules/halo/covenant/structures_machines/conveyor.dm
  code/modules/halo/covenant/structures_machines/conveyor.dmi
  code/modules/halo/covenant/structures_machines/shuttle_engine.dm
  code/modules/halo/covenant/supply/equipment.dm
  code/modules/halo/covenant/supply/weapons_ammo.dm
  code/modules/halo/factions/__defs.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/factions/reputation.dm
  code/modules/halo/factions/supply.dm
  code/modules/halo/supply/covenant.dm
  code/modules/halo/supply/innie.dm
  code/modules/halo/supply/oni.dm
  code/modules/halo/supply/program/Topic.dm
  code/modules/halo/supply/program/mutators.dm
  code/modules/halo/supply/program/print.dm
  code/modules/halo/supply/program/ui_interact.dm
  code/modules/halo/supply/unsc.dm
  code/modules/halo/trade/shuttle_buy.dm
  code/modules/halo/trade/supply_order.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/areas.dm
  maps/CRS_Unyielding_Transgression/backup/CRS_Unyielding_Transgression.dmm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/faction_bases/complex046/complex046.dm
  maps/geminus_city/geminus_city.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
  maps/ks7_elmsville/ks7_elmsville.dm
  maps/ks7_elmsville/unit_tests.dm
  nano/css/layout_covenant.css
  nano/images/HW_Logo_Covenant.png
  nano/images/uiBackground-Covenant.png
  nano/templates/faction_supply.tmpl
  nano/templates/layout_covenant.tmpl
Labels: feature, spriting

#2773 New cov supply packs, map tweaks, bandolier tweaks, pop balance minimum threshold
  baystation12.dme
  code/game/gamemodes/nuclear/pinpointer.dm
  code/game/jobs/job/job.dm
  code/modules/clothing/under/accessories/storage.dm
  code/modules/halo/clothing/bandolier.dm
  code/modules/halo/covenant/supply/NPCs.dm
  code/modules/halo/covenant/supply/ammo_grenades.dm
  code/modules/halo/covenant/supply/atmospherics.dm
  code/modules/halo/covenant/supply/clothing.dm
  code/modules/halo/covenant/supply/construction.dm
  code/modules/halo/covenant/supply/equipment.dm
  code/modules/halo/covenant/supply/weapons.dm
  code/modules/halo/supply/covenant.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/_gamemodes/_popbalance.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/ODP_Cassius/new_areas.dm
Labels: enhancement/QOL, feature, mapping
