Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-05, with the labels that each got.

#2414 yanmee click-box change
  code/modules/halo/covenant/species/yanmee/r_yanmee.dmi
Labels: enhancement/QOL

#2415 ship spawn console poplocking
  code/modules/halo/factions/_faction.dm
  code/modules/halo/overmap/npc_ship_playercontrol.dm
  code/modules/halo/overmap/player_shuttles.dm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
Labels: enhancement/QOL

#2410 New random events, job arrival announcements, faction announcements
  baystation12.dme
  code/controllers/configuration.dm
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job/job.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/economy/TradeDestinations.dm
  code/modules/events/apc_damage.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/event_container.dm
  code/modules/events/event_dynamic.dm
  code/modules/events/event_manager.dm
  code/modules/events/infestation.dm
  code/modules/events/radiation_storm.dm
  code/modules/halo/comms/machines/_overmap_comms.dm
  code/modules/halo/comms/telecomms_jammers.dm
  code/modules/halo/comms/telecomms_receivers.dm
  code/modules/halo/covenant/airlocks/doors.dm
  code/modules/halo/covenant/structures_machines/comms.dm
  code/modules/halo/events/_ship.dm
  code/modules/halo/events/gravity_failure.dm
  code/modules/halo/events/grid_check.dm
  code/modules/halo/events/ion_storm.dm
  code/modules/halo/events/magnetic_storm.dm
  code/modules/halo/events/power_failure.dm
  code/modules/halo/events/spacevine.dm
  code/modules/halo/events/wallrot.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/announce.dm
  code/modules/halo/misc/admin_verbs.dm
  code/modules/halo/trade/TradeDestinations.dm
  code/modules/halo/turfs/streetobjs.dm
  code/modules/halo/unsc/faxmachine.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/power/lighting.dm
  code/procs/announce.dm
Labels: Bugfix, Ready, enhancement/QOL, feature, overmap, spawns

#2417 uparmors ships
  code/modules/halo/covenant/structures_machines/comms.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  maps/Admin Planet/surface.dmm
  maps/Asteroid Listening Post/Asteroid_1.dmm
  maps/Asteroid Listening Post/Asteroid_2.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/npc_ships/ert_ship_human.dmm
  maps/npc_ships/req_console_ships/cov_cheap.dmm
  maps/npc_ships/req_console_ships/cov_heavyarmed.dmm
  maps/npc_ships/req_console_ships/cov_laserplatform_experimental.dmm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
  maps/npc_ships/req_console_ships/cov_tender.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_cheap.dmm
  maps/npc_ships/req_console_ships/unsc_heavyarmed.dmm
  maps/npc_ships/req_console_ships/unsc_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/unsc_podcarrier.dmm
  maps/npc_ships/req_console_ships/unsc_tender.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  maps/npc_ships/req_console_ships/urf_cheap.dmm
  maps/npc_ships/req_console_ships/urf_heavyarmed.dmm
  maps/npc_ships/req_console_ships/urf_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/urf_podcarrier.dmm
  maps/npc_ships/req_console_ships/urf_tender.dmm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, feature

#2403 Recolored Brute Armors
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj.dmi
Labels: enhancement/QOL, spriting

#2420 ks7 map tweaks
  maps/ks7_elmsville/KS7_535_1.dmm
Labels: enhancement/QOL, oversight

#2421 Adds correctly coloured muzzle effects for covenant weapons
  baystation12.dme
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/muzzle_effects.dm
  code/modules/halo/weapons/covenant/muzzle_effects.dmi
Labels: enhancement/QOL, spriting

#2425 Add a panic bunker
  baystation12.dme
  code/controllers/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_procs.dm
Labels: Ready, enhancement/QOL, priority/med

#2426 Firefight fixes and tweaks
  code/controllers/communications.dm
  code/modules/halo/covenant/items/tools.dmi
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/weapons/covenant/handheld_shields.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dmi
  code/modules/halo/weapons/covenant/shield_gauntlet_lefthand.dmi
  code/modules/halo/weapons/covenant/shield_gauntlet_mob.dmi
  code/modules/halo/weapons/covenant/shield_gauntlet_righthand.dmi
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  maps/_gamemodes/firefight/_mode.dm
  maps/_gamemodes/firefight/resupply.dm
  maps/_gamemodes/firefight/resupply_crates.dm
  maps/_gamemodes/firefight/subtypes/crusade.dm
  maps/_gamemodes/firefight/subtypes/crusade_resupply.dm
  maps/crusade/crusade.dm
  maps/crusade/map.dm
  maps/desert_outpost/desert_outpost.dmm
  maps/firefight/firefight.dm
  maps/firefight/map.dm
  maps/octanus_landing/octanus_landing.dmm
  maps/stranded/map.dm
  maps/stranded/stranded.dm
Labels: Balancing, Bugfix, Head developer approved self-merge

#2428 First contact fixes and tweaks
  baystation12.dme
  code/modules/halo/covenant/structures_machines/faxmachine.dm
  code/modules/halo/insurrection/faxmachine.dm
  code/modules/halo/unsc/faxmachine.dm
  code/modules/halo/unsc/unsc_fax.dmi
  code/modules/paperwork/faxmachine.dm
  code/modules/paperwork/photocopier.dm
  maps/Admin Planet/surface.dmm
  maps/Exoplanet Mining/PYK248.dmm
  maps/Exoplanet Mining/presets.dm
  maps/UNSC_With_Noble_Cause/singledeck.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/geminus_city/geminus_city_map.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/kig_yar_pirates/missionary.dmm
  maps/ks7_elmsville/KS7_535_1.dmm
  maps/ks7_elmsville/areas.dm
  maps/ks7_elmsville/presets.dm
  maps/urf_flagship/first_deck.dmm
Labels: Bugfix, enhancement/QOL

#2430 Sprite fixes
  code/modules/halo/covenant/simple_mobs/simple_mobs48.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/sangheili/r_elite.dmi
Labels: Bugfix, enhancement/QOL

#2432 Weapon Balance Pass
  code/modules/halo/sounds/plaspistol_overheat.ogg
  code/modules/halo/sounds/plasrifle1shot.ogg
  code/modules/halo/sounds/plasrifle_overheat.ogg
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/charged.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/launchers.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/rifles.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/halo/weapons/smg.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/ammo.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/deploy_kits.dm
  code/modules/halo/weapons/turrets/plas_turret.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/projectiles/attachment_profiles.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
Labels: Balancing, enhancement/QOL, feature

#2433 removes an errant A from snipers.dm
  code/modules/halo/weapons/covenant/snipers.dm
Labels: Controversial

#2429 Geminus-Invasion fixes and tweaks
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/sound/crash.ogg
  code/modules/halo/sound/sprit_flyby.ogg
  code/modules/halo/sound/start.ogg
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/halo/unsc/jobs/crew_outfits.dm
  maps/Exoplanet Mining/backup/PYK248.dmm
  maps/_gamemodes/firefight/resupply.dm
  maps/_gamemodes/firefight/subtypes/crusade.dm
  maps/faction_bases/ODP_Cassius/backup/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/backup/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/spawnpoint.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/kig_yar_pirates/backup/missionary.dmm
  maps/ks7_elmsville/backup/KS7_535_1.dmm
  maps/ks7_elmsville/backup/KS7_535_2.dmm
  maps/submaps/covenant/backup/citadelle1.dmm
  maps/urf_flagship/backup/first_deck.dmm
Labels: Bugfix, enhancement/QOL

#2437 Massively reduces the effect of RNG on projectiles actually registering a hit
  baystation12.dme
  code/__defines/projectiles.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/projectile.dm
Labels: Balancing, enhancement/QOL

#2434 Reclamation tweaks and fixes
  baystation12.dme
  code/game/machinery/cryo.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/verbs/mapswitch.dm
  code/modules/atmospherics/components/portables_connector.dm
  code/modules/halo/covenant/_species.dm
  code/modules/halo/covenant/jobs/huragok.dm
  code/modules/halo/covenant/structures_machines/antimatter_bomb.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/npc_factions/flp.dm
  code/modules/halo/factions/npc_factions/gao.dm
  code/modules/halo/factions/npc_factions/khoros.dm
  code/modules/halo/factions/npc_factions/olympus.dm
  code/modules/halo/factions/objectives/objectives_cov.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/factions/quest_generate.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/misc/payload.dmi
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/icons/slipspace_drive_cov.dmi
  code/modules/halo/overmap/icons/slipspace_drive_human.dmi
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/overmap/weapons/auto_mac_program.dm
  code/modules/halo/vehicles/supply_pods.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/weapons/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/overmap/ships/ship.dm
  code/modules/research/server.dm
  icons/turf/areas.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/areas.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/areas.dm
  maps/geminus_city/innie_jobs.dm
Labels: Balancing, Bugfix, Ready, enhancement/QOL, mapping, overmap

#2439 firefight respawn fix
  code/modules/mob/living/simple_animal/simple_animal.dm
  maps/_gamemodes/firefight/_mode.dm
Labels: Bugfix

#2436 Firefight misc fixes and improvements
  baystation12.dme
  code/__defines/misc.dm
  code/modules/halo/NPC/npc_overmind.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/covenant/jobs/kigyar.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/jobs/sanshyuum.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/jobs/yanmee.dm
  code/modules/halo/covenant/simple_mobs/_covenant.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/mobs/simple_mob_ai.dm
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dmi
  code/modules/halo/weapons/covenant/shield_gauntlet_effect.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/projectile.dm
  maps/_gamemodes/firefight/_mode.dm
  maps/_gamemodes/firefight/overmind.dm
  maps/_gamemodes/firefight/resupply.dm
  maps/_gamemodes/firefight/resupply_crates.dm
  maps/_gamemodes/firefight/resupply_landmarks.dm
  maps/_gamemodes/firefight/start.dm
  maps/_gamemodes/firefight/subtypes/crusade.dm
  maps/_gamemodes/firefight/subtypes/crusade_resupply.dm
  maps/_gamemodes/firefight/subtypes/crusade_resupply_crates.dm
  maps/desert_outpost/desert_outpost.dmm
  maps/octanus_landing/octanus_landing.dmm
Labels: Balancing, Bugfix, Ready, enhancement/QOL, mapping

#2441 Firefight tweaks and fixes
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/lobby_music/_lobby_music.dm
  maps/_gamemodes/firefight/_mode.dm
  maps/_gamemodes/firefight/evac_ship.dm
  maps/_gamemodes/firefight/process.dm
  maps/_gamemodes/firefight/resupply.dm
  maps/_gamemodes/firefight/resupply_landmarks.dm
  maps/_gamemodes/firefight/spawn.dm
  maps/_gamemodes/firefight/spawn.dmi
  maps/_gamemodes/firefight/start.dm
  maps/desert_outpost/desert_outpost.dmm
  maps/octanus_landing/octanus_landing.dmm
Labels: Bugfix, enhancement/QOL

#2442 Firefight tweaks and fixes
  code/game/machinery/floodlight.dm
  code/modules/halo/unsc/combatdogs.dm
  maps/_gamemodes/firefight/_mode.dm
  maps/_gamemodes/firefight/resupply.dm
  maps/_gamemodes/firefight/resupply_landmarks.dm
  maps/_gamemodes/firefight/subtypes/crusade_resupply.dm
Labels: Bugfix, enhancement/QOL

#2446 gives glassing some player feedback
  code/controllers/voting/vote_types.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/overmap/sectors.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/sector_icon_damage.dmi
Labels: enhancement/QOL

#2448 armour vendors to the odp
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/structures/gunvendors.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: oversight

#2452 dropship overmap range buff
  code/game/turfs/simulated/walls.dm
  code/modules/halo/misc/atom_despawner.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/vehiclebase_air_overmap.dm
  code/modules/halo/weapons/lmg.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
Labels: enhancement/QOL

#2450 Unggoy Minor Fixes And Slight Brute Name change
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/species/jiralhanae/first_jiralhanae.txt
Labels: Bugfix, enhancement/QOL

#2453 Marine Helmet Sprite Fixes
  code/modules/halo/clothing/marine.dm
Labels: enhancement/QOL

#2440 Updates the Human BODY
  code/modules/halo/covenant/species/jiralhanae/blood_jiralhanae.dmi
  code/modules/halo/covenant/species/jiralhanae/dam_jiralhanae.dmi
  code/modules/halo/covenant/species/jiralhanae/dam_mask_jiralhanae.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/sangheili/blood_elite.dmi
  code/modules/halo/covenant/species/sangheili/dam_elite.dmi
  code/modules/halo/covenant/species/sangheili/dam_mask_elite.dmi
  code/modules/halo/covenant/species/sangheili/sangheili.dm
  code/modules/halo/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left_elite.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right_elite.dmi
  icons/mob/human_races/r_human.dmi
Labels: enhancement/QOL, in-progress

#2459 Covenant Vendor Null Entry Fixes
  code/modules/halo/covenant/structures_machines/covvendors.dm
Labels: Bugfix

#2461 Reworks phase 2 of Reclamation
  baystation12.dme
  code/__defines/items_clothing.dm
  code/datums/repositories/mobs.dm
  code/modules/halo/covenant/invasion_scanner.dm
  code/modules/halo/covenant/invasion_scanner_pinpointers.dm
  code/modules/halo/covenant/items/artifact_pinpointer.dm
  code/modules/halo/covenant/structures_machines/scanner.dmi
  code/modules/halo/misc/payload.dm
  code/modules/halo/overmap/slipspace_engine.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/halo/weapons/turrets/HMG.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/_gamemodes/invasion/gamemode.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_1.dmm
  maps/faction_bases/ODP_Cassius/ODP_Cassius_2.dmm
  maps/faction_bases/ODP_Cassius/spawnpoint.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/invasion_geminus.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: Balancing, bug, enhancement/QOL, feature

#2464 Jammer Fix
  maps/unsc_achlys/achlys_gm.dm
  maps/unsc_achlys/achlys_objects.dm
Labels: Balancing, Bugfix, Ready, enhancement/QOL, priority/med
