Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-03, with the labels that each got.

#2280 Achlys Hotfix
  maps/unsc_achlys/achlys_jobs.dm
  maps/unsc_achlys/achlys_objects.dm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
  maps/unsc_achlys/unsc_dante_Z2.dmm
Labels: Bugfix, enhancement/QOL, priority/high

#2279 Boarding pod drop pod
  code/controllers/voting/vote_types.dm
  code/modules/halo/machinery/boarding_beacon_launcher.dm
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/halo/weapons/drop_pod_beacon.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
Labels: enhancement/QOL

#2277 Medical Streamlining
  code/modules/halo/chemicals/containers.dm
  code/modules/halo/covenant/medical.dm
  code/modules/halo/covenant/medical.dmi
  code/modules/halo/structures/covvendors.dm
  code/modules/halo/structures/gunvendors.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/urf_flagship/first_deck.dmm
Labels: Balancing, enhancement/QOL, mapping

#2284 unggoy mobilespawn buff
  code/modules/halo/outfits/mobile_spawn_outfits.dm
Labels: Balancing

#2286 Armour and shield rebalance
  baystation12.dme
  code/__defines/items_clothing.dm
  code/game/objects/items.dm
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/misc/armourspecials/overshield.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/species_items/grunt.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/orion.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/sanshyuum.dm
  code/modules/halo/species_items/skirmisher_armour.dm
  code/modules/halo/species_items/skirmisher_gauntlets.dm
  code/modules/halo/species_items/yanmee.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/types/escape_pelican.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/handheld_shields.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/snipers.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/attachments/sights.dm
  code/modules/projectiles/projectile/bullets.dm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
Labels: Balancing

#2290 various species speed changes
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/orion.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/sanshyuum.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/species/yanmee.dm
Labels: Balancing

#2298 Tweaks
  code/_onclick/click.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/covenant/medical.dm
  code/modules/halo/species/brutes.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/species/sangheili.dm
  code/modules/halo/species/spartan.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/grenades.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/organs/external/_external_damage.dm
Labels: Balancing

#2319 Further tweaks and bugfixes
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/species_items/kig-yar.dm
  code/modules/halo/species_items/lekgolo_ui.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/projectiles/gun.dm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
  maps/urf_flagship/first_deck.dmm
Labels: Balancing, Bugfix

#2321 Biofoam fix
  code/modules/halo/chemicals/medicine.dm
Labels: Bugfix

#2322 xor armour fix
  code/modules/halo/clothing/doneritems.dm
Labels: Bugfix

#2320 Momentum based vehicle movement
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehicle_occupant.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
Labels: enhancement/QOL, feature

#2323 takeoff/landing fix
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
Labels: Bugfix

#2330 Air vehicles can move z-levels
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/multiz/movement.dm
Labels: enhancement/QOL, feature

#2336 wrecked airlock update
  icons/obj/doors/door_assembly.dmi
Labels: priority/med, spriting

#2349 NPC ship prominence increase
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  code/modules/halo/overmap/npc_fleets.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/overmap/weapons/overmap_projectile.dm
  code/modules/halo/sounds/OneProblemAtATime.ogg
  code/modules/halo/sounds/slip_rupture_detected.ogg
  maps/_gamemodes/invasion/gamemode.dm
Labels: feature

#2355 Map fix for Covvies
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/areas.dm
  maps/CRS_Unyielding_Transgression/backup/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping, oversight

#2345 Weekend bugfixes
  code/__defines/mobs.dm
  code/game/jobs/job/job.dm
  code/modules/halo/chemicals/containers.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/custom_ai_objects/ai_outfit.dm
  code/modules/halo/icons/overmap/req_combat.dmi
  code/modules/halo/icons/overmap/req_heavyarmed.dmi
  code/modules/halo/icons/overmap/req_macplatform.dmi
  code/modules/halo/icons/overmap/req_podcarrier.dmi
  code/modules/halo/icons/overmap/req_tender.dmi
  code/modules/halo/icons/overmap/req_trooptransport.dmi
  code/modules/halo/icons/species/jiralhanae_gear.dmi
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/npc_ship_requests.dm
  code/modules/halo/overmap/req_console_ships.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/species_items/jiralhanae_outfit.dm
  code/modules/halo/species_items/yanmee_outfits.dm
  code/modules/halo/structures/gunvendors.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/dual_wielding.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  maps/CRS_Unyielding_Transgression/outfits.dm
  maps/UNSC_Halberd_Class/halberdclass_new.dmi
  maps/UNSC_Halberd_Class/overmap.dm
  maps/urf_flagship/first_deck.dmm
Labels: Balancing, Bugfix
