Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-11, with the labels that each got.

#2823 A collection of changes and updates, small and large
  baystation12.dme
  code/modules/halo/NPC/npc_overmind.dm
  code/modules/halo/abilities/flight.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/covenant/simple_mobs/_covenant.dm
  code/modules/halo/covenant/simple_mobs/elite.dm
  code/modules/halo/covenant/simple_mobs/grunt.dm
  code/modules/halo/covenant/simple_mobs/jackal.dm
  code/modules/halo/covenant/simple_mobs/overmind.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_defence.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/sangheili/sangheili.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/leader_support/job_overrides.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/leader_support/support_item.dm
  code/modules/halo/mobs/ambient_fauna/frog.dm
  code/modules/halo/mobs/elevation_handling.dm
  code/modules/halo/mobs/grenade_throwing.dm
  code/modules/halo/mobs/holster_verb.dm
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/unsc/jobs/ODST.dm
  code/modules/halo/unsc/overmind.dm
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/halo/unsc/spartan.dm
  code/modules/halo/weapons/M545.dm
  code/modules/halo/weapons/ammo_5mm.dm
  code/modules/halo/weapons/ammo_shotshell.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/halo/weapons/flamethrowers.dm
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/plas_turret.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/mob_movement.dm
  icons/mob/animal.dmi
  icons/mob/screen_full.dmi
  maps/base_assault/base_assault.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
  maps/faction_bases/CassiusMoonStation/cassiusmoon.dm
  maps/faction_bases/CassiusMoonStation/presets.dm
  maps/faction_bases/complex046/complex046.dmm
  maps/urf_flagship/first_deck.dmm
Labels: Balancing, enhancement/QOL, hacktoberfest-accepted

#2833 Hellbringer flamethrower heat fix
  code/modules/ZAS/Fire_simple.dm
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/squads/waypoints.dmi
  code/modules/halo/weapons/flamethrowers.dm
Labels: Balancing, Bugfix

#2836 Move to GitHub Actions for CI
  .github/workflows/tests.yml
  .travis.yml
  scripts/validateTravisContainsAllMaps.sh
Labels: Ready

#2851 Prepare for GitHub Actions Updates
  .github/workflows/tests.yml
  test/run-test.sh
  tools/GenerateGlobalVarAccess/gen_globals.py
  tools/PunctuationChecker/punctuation-checker.py
  tools/TagMatcher/tag-matcher.py
  tools/dmitool/dmitool.py
Labels: Ready

#2855 Add autopunctuation
  code/_helpers/text.dm
  code/modules/mob/language/language.dm
Labels: enhancement/QOL

#2856 makes popbalance take job pop cost into account
  code/game/jobs/job/job.dm
  maps/_gamemodes/_popbalance.dm
Labels: Bugfix, oversight

#2857 Say/me inputs are now escapable
  code/modules/mob/say.dm
  code/modules/mob/typing_indicator.dm
Labels: enhancement/QOL

#2860 makes the popbalance system take the joining player into account when determining total faction players
  code/game/jobs/job/job.dm
Labels: Balancing, oversight
