Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2020-01, with the labels that each got.

#2092 Update BYOND to 513 in Travis
  .travis.yml
  code/_helpers/text.dm
  code/_helpers/unsorted.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/supply_display.dm
  code/game/objects/items/devices/violin.dm
  code/game/objects/items/weapons/paint.dm
  code/game/objects/structures/musician.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/machinery/autosurgeon/surgery_external.dm
  code/modules/halo/machinery/autosurgeon/surgery_internal.dm
  code/modules/halo/medicine/combat.dm
  code/modules/halo/species/grunts.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/spartan.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/pai/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
  code/modules/organs/blood.dm
  code/modules/organs/external/_external.dm
  code/modules/scripting/Implementations/_Logic.dm
  code/modules/scripting/Options.dm
  code/modules/scripting/Scanner/Scanner.dm
  code/modules/surgery/generic.dm
  code/modules/xenoarcheaology/artifacts/replicator.dm
  code/modules/xenoarcheaology/finds/talking.dm
  code/world.dm
Labels: enhancement/QOL

#2095 hotfixes
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/structures/covvendors.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/ship.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
Labels: bug

#2099 flagship update balance pass
  code/game/turfs/simulated/walls.dm
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/overmap/player_shuttles.dm
  code/modules/overmap/sectors.dm
  maps/Asteroid Listening Post/overmap.dm
  maps/SOE_Argentum/jobs.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/URF Commando Ship/jobs.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/geminus_city/invasion_geminus.dm
  maps/npc_ships/req_console_ships/cov_cheap.dmm
  maps/npc_ships/req_console_ships/cov_heavyarmed.dmm
  maps/npc_ships/req_console_ships/cov_laserplatform_experimental.dmm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
  maps/npc_ships/req_console_ships/cov_tender.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_cheap.dmm
  maps/npc_ships/req_console_ships/unsc_heavyarmed.dmm
  maps/npc_ships/req_console_ships/unsc_podcarrier.dmm
  maps/npc_ships/req_console_ships/unsc_tender.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  maps/npc_ships/req_console_ships/urf_cheap.dmm
  maps/npc_ships/req_console_ships/urf_heavyarmed.dmm
  maps/npc_ships/req_console_ships/urf_podcarrier.dmm
  maps/npc_ships/req_console_ships/urf_tender.dmm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
  maps/urf_flagship/first_deck.dmm
  maps/urf_flagship/overmap.dm
Labels: enhancement/QOL

#2100 Flagship Update Quickfixes and minor whitelist changes
  code/modules/halo/factions/objectives/objectives_innie.dm
  maps/CRS_Unyielding_Transgression/jobs.dm
Labels: oversight

#2101 Removes an accidental shipyard and moves the URF mission area
  maps/Exoplanet Research/Exoplanet Research Ice/overmap.dm
  maps/urf_flagship/first_deck.dmm
Labels: bug

#2103 Ship Weapon Rebalances/Fixes
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
Labels: bug, enhancement/QOL

#2107 Wall explosion damage buff
  code/game/turfs/simulated/walls.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/weapons/charged.dm
  code/modules/halo/weapons/pistols.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/projectiles/guns/projectile.dm
Labels: bug, enhancement/QOL

#2109 Ultra Swords and some other fixes/balances
  code/modules/halo/overmap/req_console_ships.dm
  code/modules/halo/species_items/sangheili_outfits.dm
  code/modules/halo/weapons/covenant/brute.dm
  maps/_gamemodes/invasion/gamemode.dm
Labels: enhancement/QOL

#2111 Block Pre-513 Compilers
  code/world.dm
Labels: enhancement/QOL, oversight

#2112 Reverts wall explosion code changes (mostly)
  code/game/turfs/simulated/walls.dm
  code/modules/halo/overmap/player_shuttles.dm
  maps/_gamemodes/invasion/gamemode.dm
Labels: enhancement/QOL

#2110 Nanu's Donator Armor
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/sounds/hurtflesh2.ogg
Labels: enhancement/QOL

#2116 Fixed Nanu's Armor
  code/modules/halo/clothing/doneritems.dm
Labels: enhancement/QOL

#2114 huragok iron
  code/modules/halo/covenant/huragok/huragok_items.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/species/orion.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/organs/external/_external.dm
  code/modules/overmap/sectors.dm
  maps/_gamemodes/invasion/gamemode_reclamation.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/innie_jobs.dm
  maps/geminus_city/innie_spawns.dm
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/geminus_city/x52_jobs.dm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL

#2117 stops combat prophet
  maps/geminus_city/innie_jobs.dm
Labels: bug

#2118 Donor Items
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/icons/species/Sangheili_Combat_Harness.dmi
  code/modules/halo/weapons/icons/Belt_Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL

#2120 Various fixes and additions
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/modules/emotes/definitions/_mob.dm
  code/modules/emotes/definitions/audible.dm
  code/modules/halo/machinery/scanning_console.dm
  code/modules/halo/sounds/need_weapon.ogg
  code/modules/halo/species/yanmee.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/targeting/targeting_triggers.dm
  maps/ONI_Prowler/jobs.dm
Labels: enhancement/QOL, feature

#2121 researcher spawn faction fix
  code/game/jobs/job_controller.dm
  code/game/mecha/combat/Hrunting.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/mecha/working/hoverpod.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/overmap/weapons/covie_pulse_turret.dm
  code/modules/halo/overmap/weapons/laser_designator.dm
  code/modules/halo/overmap/weapons/proj_deck_gun.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/item_worth/worths_list.dm
  maps/Exoplanet Research/Exoplanet Research Ice/jobs.dm
Labels: bug

#2126 Intro Blurb Oversight
  maps/unsc_achlys/achlys_jobs.dm
Labels: oversight

#2131 ai console use fix
  code/modules/halo/overmap/weapons/overmap_weapon.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/species_items/spartan.dm
Labels: bug

#2128 Additional Donor Sprites
  code/modules/clothing/shoes/magboots.dm
  code/modules/halo/clothing/doneritems.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/icons/species/Sangheili_Combat_Harness.dmi
Labels: enhancement/QOL

#2127 Revert "Disable The Achyls Test"
  .travis.yml
  scripts/validateTravisContainsAllMaps.sh
Labels: enhancement/QOL

#2132 Addresses Travis Concerns
  maps/unsc_achlys/achlys_outfits.dm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
Labels: enhancement/QOL, in-progress, not a bug, oversight

#2139 Adds observer spawn unit test and safety checks
  code/modules/mob/observer/ghost/ghost.dm
  code/unit_tests/map_tests.dm
Labels: enhancement/QOL

#2134 Added a few weapons and some pieces of armor to the mission shuttle o…
  code/modules/halo/machinery/autosurgeon/autosurgeon.dm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, mapping

#2135 general balancing changes
  code/modules/halo/clothing/odst.dm
  code/modules/halo/species_items/sangheili.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/lmg.dm
  code/modules/halo/weapons/pistols.dm
  maps/UNSC_Bertels/jobs.dm
  maps/UNSC_Bertels/outfits.dm
Labels: enhancement/QOL

#2140 Tweaks after packwar testing
  code/game/machinery/doors/simple.dm
  code/game/objects/effects/effect_system.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/lighting/lighting_atom.dm
Labels: enhancement/QOL

#2141 Enable effects dont block lighting optimisation
  code/game/objects/effects/effect_system.dm
Labels: enhancement/QOL

#2144 needlenerf revert
  code/modules/halo/species_items/jiralhanae.dm
  code/modules/halo/weapons/covenant/ammo.dm
Labels: enhancement/QOL

#2143 Packwar obj process debugging
  code/controllers/Processes/obj.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/recycling/conveyor2.dm
Labels: enhancement/QOL

#2146 A lesson is learned...
  code/modules/mob/new_player/new_player.dm
Labels: Controversial, New Contributor Friendly, Suggestion, ackchyually, bug, duplicate, enhancement/QOL, feature, not a bug, oversight, priority/critical, priority/high, priority/low, priority/med

#1843 Vehicles cleanup and fixes
  baystation12.dme
  code/_helpers/mobs.dm
  code/modules/halo/covenant/spirit.dm
  code/modules/halo/vehicles/__defs.dm
  code/modules/halo/vehicles/finalwarthog-chaingun.dmi
  code/modules/halo/vehicles/supply_pods.dm
  code/modules/halo/vehicles/types/Bull.dmi
  code/modules/halo/vehicles/types/Cobra.dmi
  code/modules/halo/vehicles/types/GCPD_Warthog.dmi
  code/modules/halo/vehicles/types/SOEIV.dm
  code/modules/halo/vehicles/types/Scorpion.dmi
  code/modules/halo/vehicles/types/Warthog.dmi
  code/modules/halo/vehicles/types/Wraith.dmi
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/bumblebee_full.dmi
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/covenant_pods.dmi
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/escape_pods.dm
  code/modules/halo/vehicles/types/finalwarthog-chaingun.dmi
  code/modules/halo/vehicles/types/finalwarthog-turretless.dmi
  code/modules/halo/vehicles/types/finalwarthog.dmi
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/ghost.dmi
  code/modules/halo/vehicles/types/innie_scorpion.dmi
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/mongoose.dmi
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/shadow.dmi
  code/modules/halo/vehicles/types/spectre_unfinished.dmi
  code/modules/halo/vehicles/types/spirit.dmi
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehicle_cargo.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehicle_occupant.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/~undefs/~undefs.dm
  code/modules/xenoarcheaology/anomaly_container.dm
  maps/doisac/mercenaries_spawn.dm
Labels: bug, enhancement/QOL, feature, overmap

#2148 Various Fixes
  code/modules/halo/factions/objectives/objectives_unsc.dm
  code/modules/halo/overmap/req_console_ships.dm
  code/modules/halo/overmap/weapons/missile_pods.dm
  code/modules/halo/overmap/weapons/plasmatorpedoes.dm
  code/modules/halo/species/kig-yar.dm
  code/modules/halo/turfs/covenant/materials.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/projectiles/guns/launcher/syringe_gun.dm
  maps/Exoplanet Research/Exoplanet Research Ice/overmap.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/npc_ships/req_console_ships/cov_cheap.dmm
  maps/npc_ships/req_console_ships/cov_heavyarmed.dmm
  maps/npc_ships/req_console_ships/cov_laserplatform_experimental.dmm
  maps/npc_ships/req_console_ships/cov_podcarrier.dmm
  maps/npc_ships/req_console_ships/cov_tender.dmm
  maps/npc_ships/req_console_ships/cov_trooptransport.dmm
  maps/npc_ships/req_console_ships/unsc_cheap.dmm
  maps/npc_ships/req_console_ships/unsc_heavyarmed.dmm
  maps/npc_ships/req_console_ships/unsc_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/unsc_podcarrier.dmm
  maps/npc_ships/req_console_ships/unsc_tender.dmm
  maps/npc_ships/req_console_ships/unsc_trooptransport.dmm
  maps/npc_ships/req_console_ships/urf_cheap.dmm
  maps/npc_ships/req_console_ships/urf_heavyarmed.dmm
  maps/npc_ships/req_console_ships/urf_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/urf_podcarrier.dmm
  maps/npc_ships/req_console_ships/urf_tender.dmm
  maps/npc_ships/req_console_ships/urf_trooptransport.dmm
Labels: bug, enhancement/QOL

#2130 Rework of LB.
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
  maps/UNSC_Halberd_Class/areas.dm
Labels: Do Not Merge, enhancement/QOL, mapping

#2152 Operation: Red Flag fixes
  baystation12.dme
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job_controller.dm
  code/game/movietitles.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/spartan_armour_abilities.dm
  code/modules/halo/clothing/spartan_armour_abilities_types.dm
  code/modules/halo/clothing/spartan_armour_abilities_wrench.dm
  code/modules/halo/clothing/spartan_gear.dmi
  code/modules/halo/covenant/computer.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  maps/ccs_battlecruiser/backup/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/backup/planet_staging.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser1.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser2.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser3.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser4.dmm
  maps/ccs_battlecruiser/ccs_battlecruiser5.dmm
  maps/ccs_battlecruiser/jobs/elite.dm
  maps/ccs_battlecruiser/jobs/spartan.dm
  maps/ccs_battlecruiser/planet_staging.dmm
  maps/ccs_battlecruiser/playernav.dm
Labels: bug, enhancement/QOL, mapping, spawns

#2153 Gives Murmillo's common
  code/modules/halo/species_items/skirmisher_outfits.dm
Labels: enhancement/QOL, oversight

#2154 Admin Conversion Tools
  baystation12.dme
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/covenant/multitile_airlocks.dm
  code/modules/halo/machinery/covenant/doors.dm
  code/modules/halo/misc/admin_spawn_conversion.dm
  code/modules/halo/misc/conversion_contracts.dm
  code/modules/halo/misc/convert_contract.dmi
  code/modules/halo/species/ai-squads.dm
  code/modules/halo/species_items/lekgolo_attack.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/ammo.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/turrets/ammo.dm
  code/modules/projectiles/projectile/bullets.dm
  maps/unsc_achlys/achlys_gm.dm
Labels: enhancement/QOL, feature

#2156 Revert "Revert "Gives Murmillo's common""
  code/modules/halo/species_items/skirmisher_outfits.dm
Labels: feature

#2137 Achlys Hotfix1
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/structures/door_assembly.dm
  code/modules/halo/flood/flood_spawn_proxy.dm
  maps/unsc_achlys/achlys_jobs.dm
  maps/unsc_achlys/achlys_objects.dm
  maps/unsc_achlys/achlys_outfits.dm
  maps/unsc_achlys/unsc_achlys_Z1.dmm
  maps/unsc_achlys/unsc_achlys_Z2.dmm
  maps/unsc_achlys/unsc_achlys_Z3.dmm
  maps/unsc_achlys/unsc_achlys_Z4.dmm
  maps/unsc_achlys/unsc_dante_Z1.dmm
  maps/unsc_achlys/unsc_dante_Z2.dmm
Labels: enhancement/QOL, in-progress, oversight

#2158 Changes for LB
  maps/UNSC_Halberd_Class/UNSC_Light_Brigade.dmm
Labels: enhancement/QOL, mapping
