Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2021-07, with the labels that each got.

#2966 Fix initial population of mobs_in_sectors list
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Bugfix, Ready

#2963 Modernises aiming with the addition of click-drag fire.
  baystation12.dme
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_attack.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_ui.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/weapons/ACL55.dm
  code/modules/halo/weapons/BR55.dm
  code/modules/halo/weapons/BR85.dm
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/M545.dm
  code/modules/halo/weapons/M6D.dm
  code/modules/halo/weapons/M6S.dm
  code/modules/halo/weapons/M7.dm
  code/modules/halo/weapons/M739.dm
  code/modules/halo/weapons/MA5B.dm
  code/modules/halo/weapons/SRS99.dm
  code/modules/halo/weapons/_gunsautofire.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/forerunner/rifles.dm
  code/modules/halo/weapons/icons/dragaim_icon.dmi
  code/modules/halo/weapons/icons/dragaim_icon2.dmi
  code/modules/halo/weapons/icons/dragaim_missile.dmi
  code/modules/halo/weapons/spartan_laser.dm
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/plas_turret.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
Labels: Balancing, Bugfix, enhancement/QOL, feature

#2971 Emplacement Dispersion Changes
  code/game/objects/items/weapons/grenades/explosive.dm
  code/modules/halo/weapons/MA37.dm
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/plas_turret.dm
  code/modules/halo/weapons/turrets/turret.dm
Labels: Balancing, enhancement/QOL

#2978 A variety of vehicle tweaks (And some minor CnH changes)
  baystation12.dme
  code/game/machinery/deployable.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_attack.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_defence.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_ui.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/vehicles/rearm_repair_station.dm
  code/modules/halo/vehicles/types/banshee.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/sparrowhawk.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehicle_action_buttons.dm
  code/modules/halo/vehicles/vehicle_cargo.dm
  code/modules/halo/vehicles/vehicle_occupant.dm
  code/modules/halo/vehicles/vehicle_smoke_countermeasures.dm
  code/modules/halo/vehicles/vehicleactionicons.dmi
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/_guns.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/icons/Covenant_Projectiles.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/turrets/ammo.dm
  maps/base_assault_neutral_base/overmap.dm
Labels: Balancing, enhancement/QOL, feature

#2980 Huragok Engineer Repair Patch
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/covenant/species/huragok/robot_items.dm
  code/modules/halo/covenant/species/huragok/robot_modules.dm
Labels: Balancing, feature
