Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2021-12, with the labels that each got.

#3007 Stop inconclusive map votes from crashing server
  code/controllers/voting/_vote.dm
  code/controllers/voting/announce_result.dm
  code/controllers/voting/vote_types.dm
Labels: Bugfix, Ready

#3015 Removal of Species locking & Spartan Self Destruct Changes
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/covenant/species/unggoy/_grunt.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL

#3013 Balance tweaks long awaited
  code/game/machinery/deployable.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_ui.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/misc/atom_despawner.dm
  code/modules/halo/mobs/elevation_handling.dm
  code/modules/halo/shuttles/dropship_landing_points.dm
  code/modules/halo/squads/squad-waypoint-controller.dm
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/squads/squad_camera_console.dm
  code/modules/halo/structures/_destructible.dm
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/halo/vehicles/types/banshee.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/sparrowhawk.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/vehicle_occupant.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/vehicles/vehiclebase_air_overmap.dm
  code/modules/halo/weapons/BR55.dm
  code/modules/halo/weapons/BR85.dm
  code/modules/halo/weapons/M392.dm
  code/modules/halo/weapons/ammo_9-5mm.dm
  code/modules/halo/weapons/ammo_shotshell.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/halo/weapons/forerunner/melee.dm
  code/modules/halo/weapons/forerunner/snipers.dm
  code/modules/halo/weapons/shotguns.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/materials/material_recipes.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: Balancing

#3017 makes the ONI base viable
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, mapping

#3021 Gives Yanmee IDs
  code/modules/halo/covenant/items/Cards.dmi
  code/modules/halo/covenant/items/cards.dm
  code/modules/halo/covenant/species/yanmee/yanmee_outfits.dm
Labels: enhancement/QOL, spriting

#3009 Wings for the Yanme'e
  baystation12.dme
  code/modules/halo/abilities/flight.dm
  code/modules/halo/clothing/jetpacks.dm
  code/modules/halo/clothing/yanmee_wings.dm
  code/modules/halo/clothing/yanmee_wings.dmi
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/covenant/species/yanmee/yanmee_outfits.dm
  code/modules/halo/sounds/yanmee_flying.ogg
  code/modules/mob/living/carbon/human/examine.dm
Labels: enhancement/QOL, spriting

#3026 Emotes
  code/modules/emotes/definitions/_mob.dm
  code/modules/halo/emotes/emotes.dm
  code/modules/halo/sounds/licensed/Usage.txt
  code/modules/halo/sounds/licensed/boo.ogg
  code/modules/halo/sounds/licensed/cannot_aim.ogg
  code/modules/halo/sounds/licensed/nipple.ogg
Labels: enhancement/QOL, feature

#3030 fixes a few oversights in ONI oops
  maps/faction_bases/complex046/complex046.dmm
Labels: mapping, oversight
