Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2021-01, with the labels that each got.

#2887 Adds Mgalekgolo and Spartan IIs to Base Assault
  baystation12.dme
  code/__defines/species_languages_halo.dm
  code/game/objects/items.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/halo/covenant/jobs/mgalekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_attack.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_defence.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_outfit.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_ui.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_gauntlets.dm
  code/modules/halo/covenant/species/yanmee/clothing.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/mobs/simplemob_radio.dm
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/structures/girder_override.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/ammo_g40mm.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/hunter_projectiles.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/melee.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/mob_helpers.dm
  maps/Admin Planet/surface.dmm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/base_assault/base_assault.dm
  maps/base_assault/base_assault_gm.dm
  maps/base_assault_unsc_defend_vs_urf/base_assault_unsc_defend_vs_urf.dm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
  maps/ks7_elmsville/hud_icons.dmi
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_1.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_2.dmm
  maps/operation_trebuchet/UNSC_Yolotanker/UNSC_Yolotanker_Deck_3.dmm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, feature

#2888 Nerfs biofoam, standardises pain-getting and adds a new painkiller
  baystation12.dme
  code/__defines/suppression.dm
  code/modules/halo/chemicals/containers.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/chemicals/recipes.dm
  code/modules/halo/covenant/medical/first_aid.dm
  code/modules/halo/covenant/medical/pills.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/misc/suppression.dm
  code/modules/halo/storage/IFAK.dm
  code/modules/halo/weapons/SDSR10.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  icons/mob/screen1_Midnight.dmi
  icons/mob/screen1_Orange.dmi
  icons/mob/screen1_White.dmi
  icons/mob/screen1_alien.dmi
  icons/mob/screen1_old.dmi
Labels: Balancing, Controversial, enhancement/QOL, feature

#2895 Make link in new round alerts clickable
  code/modules/ext_scripts/discord.dm
Labels: discord/forum/web integration, enhancement/QOL

#2896 Fix jackal command uplink
  code/modules/halo/leader_support/supply_drop_tachud.dm
Labels: Bugfix
