Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2022-02, with the labels that each got.

#3116 Covvie gun sprite improvements
  code/modules/halo/weapons/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/icons/Covenant_Projectiles.dmi
Labels: enhancement/QOL, spriting

#3124 Wildwehraboo Donor armour
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: Donor

#3122 T-vaoan spawn hotfixes
  code/modules/halo/covenant/species/tvoan/skirmisher_outfits.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: Bugfix

#3126 Oxygen Indicator Fix + New Atmos Indicators
  icons/mob/screen/midnight.dmi
  icons/mob/screen/minimalist.dmi
  icons/mob/screen/old-noborder.dmi
  icons/mob/screen/old.dmi
  icons/mob/screen/orange.dmi
  icons/mob/screen/white.dmi
  icons/mob/screen1.dmi
Labels: enhancement/QOL

#3127 Fix pass
  code/game/jobs/job/job.dm
  code/game/jobs/job_controller.dm
  code/game/objects/explosion.dm
  code/modules/halo/covenant/species/huragok/outfit.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_defence.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_outfit.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/slipspace/damage_destroy.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/weapons/ammo_12-7mm.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/modular_computers/file_system/program.dm
Labels: enhancement/QOL, Balancing, Bugfix

#3134 Zagarnt Donor gear
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
Labels: spriting, Donor

#3136 Geminus smelter
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  maps/geminus_city/geminuscity_1.dmm
Labels: enhancement/QOL, mapping, Balancing

#3137 Poplock deadlock breaker
  code/game/jobs/job/job.dm
Labels: enhancement/QOL

#3140 jetpack distribution tweak
  code/modules/halo/clothing/jetpacks.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/machinery/gunvendors.dm
  maps/geminus_city/geminuscity_1.dmm
Labels: enhancement/QOL

#3149 woodentucker donor 2
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/lekgolo/hunters.dmi
Labels: Donor

#3151 Aroliacue - Map Bugfixes for ODP Cassius and Complex 046 Electric Boogaloo
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, mapping

#3142 Adds spicy extended as a gamemode
  baystation12.dme
  code/__defines/gamemode.dm
  code/game/antagonist/antagonist.dm
  code/game/antagonist/antagonist_add.dm
  code/game/antagonist/antagonist_factions.dm
  code/game/antagonist/antagonist_update.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/game_mode_latespawn.dm
  code/game/gamemodes/objective.dm
  code/modules/halo/antag_overrides/changeling.dm
  code/modules/halo/antag_overrides/objectives.dm
  code/modules/halo/antag_overrides/revolutionary.dm
  code/modules/halo/antag_overrides/targeted_objective.dm
  code/modules/halo/antag_overrides/traitor.dm
  code/modules/halo/misc/conversion_contracts.dm
  code/modules/halo/unsc/jobs/colonist.dm
  code/modules/halo/weapons/spartan_laser.dm
  maps/_gamemodes/randantag/randantag.dm
  maps/first_contact/mapdef.dm
  maps/geminus_city/geminus_city_map.dm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/ks7_elmsville/mapdef.dm
Labels: feature, Controversial

#3152 EMAC Fixes
  maps/npc_ships/req_console_ships/unsc_macplatform_experimental.dmm
Labels: enhancement/QOL, mapping

#3155 Geminus City Botany
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, feature

#3158 CRS Update One
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping

#3160 Defender mob tweaks
  code/datums/supplypacks/engineering.dm
  code/game/antagonist/station/cultist.dm
  code/game/jobs/job/job.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/halo/covenant/species/yanmee/yanmee.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/weapons/attachments/secondary_weapon.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, Balancing

#3163 CO headset fix + CRS Map Changes
  code/modules/halo/comms/headsets.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping, Bugfix

#3165 Update billymom2 donator gear
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
Labels: Donor
