Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2022-09, with the labels that each got.

#3226 Pocket system generalisation + Minor tweaks
  code/__defines/items_clothing.dm
  code/game/objects/items/weapons/storage/internal.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/storage.dm
  code/modules/halo/Forerunner/species/knight/knight.dm
  code/modules/halo/Forerunner/species/knight/knight_armour.dm
  code/modules/halo/clothing/civilian.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/covenant/items/ammo_belt.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/kigyar/clothing.dm
  code/modules/halo/covenant/species/kigyar/kigyar_ranger.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/sanshyuum/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_armour.dm
  code/modules/halo/covenant/species/unggoy/armour.dm
  code/modules/halo/covenant/species/yanmee/clothing.dm
  code/modules/halo/weapons/M7.dm
Labels: enhancement/QOL, feature

#3228 Gives UNSC and URF ammo drops shotgun shell boxes
  code/modules/halo/leader_support/supply_drop_variants.dm
Labels: enhancement/QOL

#3231 Covenant OB Tweaking
  code/modules/halo/overmap/weapons/Energy_projector.dm
Labels: enhancement/QOL, Balancing
