Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2022-01, with the labels that each got.

#3059 Balance tweaks
  baystation12.dme
  code/game/turfs/turf.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_gauntlets.dm
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/overmap/npc_shipmap_handler.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/attachments/barrel.dm
  code/modules/halo/weapons/attachments/general_attachments.dm
  code/modules/halo/weapons/attachments/lights.dm
  code/modules/halo/weapons/attachments/secondary_weapon.dm
  code/modules/halo/weapons/attachments/sights.dm
  code/modules/halo/weapons/attachments/stocks.dm
  code/modules/halo/weapons/covenant/pistols.dm
Labels: enhancement/QOL, Balancing

#3064 MK.VII Armour
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/spartan_laser.dm
Labels: spriting

#3067 Create UNSC Squad + More
  code/modules/halo/covenant/admin_covenant_strike_team.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
  code/modules/halo/covenant/species/sangheili/sangheili_outfits.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_outfits.dm
  code/modules/halo/covenant/species/unggoy/grunt_outfits.dm
  code/modules/halo/covenant/species/yanmee/yanmee_outfits.dm
  code/modules/halo/outfits/mobile_spawn_outfits.dm
  code/modules/halo/unsc/jobs/ODST_outfits.dm
  code/modules/halo/unsc/jobs/marines_outfits.dm
  code/modules/halo/unsc/jobs/spartan_two_outfits.dm
Labels: feature

#3070 Fracture: Tenrai
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/spartan_armour_variants.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/machete.dmi
Labels: spriting

#3071 secondary weapon fixes
  code/modules/halo/weapons/attachments/secondary_weapon.dm
  code/modules/halo/weapons/covenant/brute.dm
Labels: Balancing

#3072 walk sfx
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_greaves.dm
  code/modules/halo/covenant/species/unggoy/clothing.dm
  code/modules/halo/covenant/species/yanmee/clothing.dm
  code/modules/halo/sounds/walk_sounds/brute_boots.ogg
  code/modules/halo/sounds/walk_sounds/generic_walk.ogg
  code/modules/halo/sounds/walk_sounds/hunter_walk.ogg
  code/modules/halo/sounds/walk_sounds/marine_boots.ogg
  code/modules/halo/sounds/walk_sounds/spartan_boots.ogg
Labels: enhancement/QOL

#3057 WIP Eluxor's Jackal Clothing Emporium
  code/modules/halo/NPC/NPC_types/kig_yar.dm
  code/modules/halo/covenant/species/kigyar/clothing.dm
  code/modules/halo/covenant/species/kigyar/jackalclothing.dmi
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  maps/kig_yar_pirates/presets.dm
Labels: spriting

#3073 Yoroi Armor Darkening
  code/modules/halo/clothing/spartan_armour.dmi
Labels: spriting

#3074 Aroliacue Donor
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/item_jumpsuit_ship.dmi
  code/modules/halo/clothing/mob_jumpsuit_ship.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/machete.dmi
Labels: spriting

#3078 Minor sprite offset and layering tweaks
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: enhancement/QOL

#3075 Finally, Kig-Yar Shield Fixes
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
Labels: enhancement/QOL

#3084 More Armour
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/spartan_armour_variants.dm
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/halo/unsc/spartan_hardsuits.dm
Labels: spriting, Donor

#3076 MERGE NOW "Eluxor's new brutes'"
  code/__defines/species_languages.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/halo/covenant/species/jiralhanae/Jiralhanae_mob.dmi
  code/modules/halo/covenant/species/jiralhanae/Jiralhanae_mob_old.dmi
  code/modules/halo/covenant/species/jiralhanae/blood_jiralhanae.dmi
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/dam_jiralhanae.dmi
  code/modules/halo/covenant/species/jiralhanae/dam_mask_jiralhanae.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gearold.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_hair.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_hair.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_hair_old.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_template.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_weapons.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_weapons_big.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_weaponsold.dmi
  code/modules/halo/covenant/species/tvoan/r_skirmisher_template.dmi
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/sprite_accessories.dm
Labels: enhancement/QOL, spriting

#3082 explosion logging and nuked effects tweak
  code/modules/halo/misc/payload.dm
Labels: enhancement/QOL

#3091 Gives the regal shipmaster armor sprites to normal shipmaster armor
  code/modules/halo/covenant/species/sangheili/clothing.dm
Labels: enhancement/QOL

#3095 SoE Unwhitelist
  code/modules/halo/insurrection/soe_jobs.dm
  maps/URF Commando Ship/jobs.dm
Labels: spawns

#3096 Speedy Spritefix
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/item_jumpsuit_ship.dmi
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/mob_jumpsuit_ship.dmi
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
Labels: Bugfix, Ready

#3099 ONI Hotfix 2: Appeasing XO, the final boss
  code/modules/halo/unsc/jobs/ONI.dm
  maps/Exoplanet Research/Exoplanet Research Ice/jobs.dm
Labels: Do Not Merge, Bugfix

#3100 Ghostsay changes
  code/datums/communication/dsay.dm
Labels: enhancement/QOL, feature

#3104 Misc. Brute Fixes and Chieftain armor.
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
  code/modules/halo/weapons/covenant/brute.dm
Labels: enhancement/QOL, spriting

#3109 Minor ammo tweaks that may or may not help with the lag
  code/modules/halo/covenant/language_teacher.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/misc/atom_despawner.dm
  code/modules/halo/unsc/jobs/ONI.dm
  code/modules/halo/unsc/jobs/ONI_outfits.dm
  code/modules/projectiles/ammunition.dm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL

#3110 Misc fixes
  code/game/atoms_movable.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/vehicles/types/hrunting.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/grenades.dm
Labels: enhancement/QOL, Balancing

#3112 woodentucker donor gear
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/lekgolo/hunters.dmi
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_ui.dm
Labels: Donor

#3111 Adds a multitool to the UNSC utility belt.
  code/modules/halo/machinery/gunvendors.dm
Labels: enhancement/QOL

#3090 Spartan Rig Changes
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/halo/unsc/spartan_hardsuits.dm
Labels: enhancement/QOL, feature

#3113 Port MC change from tgstation
  code/controllers/subsystem.dm
Labels: priority/high, Bugfix, Ready

#3115 Removes spec ops skirmishers (AKA fixes the t'vaoan sprite not rendering)
  code/modules/halo/covenant/species/tvoan/r_skirmisher_template.dmi
Labels: spriting, Bugfix

#3114 Turns T'vaoan Champion into a roundstart role.
  code/modules/halo/covenant/jobs/tvoan.dm
Labels: enhancement/QOL
