Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2022-03, with the labels that each got.

#3166 Covenant goblin + Some weapon tweaks
  baystation12.dme
  code/game/jobs/job/job.dm
  code/modules/halo/clothing/pilot.dm
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/sounds/goblin_cannon.ogg
  code/modules/halo/sounds/goblin_shotgun.ogg
  code/modules/halo/vehicles/supply_pods.dm
  code/modules/halo/vehicles/types/goblin.dm
  code/modules/halo/vehicles/types/goblin_vehicle.dmi
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/ammo_boxes.dm
  code/modules/halo/weapons/ammo_shotshell.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/icons/Covenant_Projectiles.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/shotguns.dm
  code/modules/halo/weapons/spartan_laser.dm
  code/modules/mob/hear_say.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/bullets.dm
Labels: enhancement/QOL, feature, Balancing

#3169 autosurgeon alignment fix
  code/modules/halo/machinery/autosurgeon/autosurgeon.dm
  code/modules/halo/vehicles/types/goblin.dm
  code/modules/halo/vehicles/types/hrunting.dm
Labels: priority/high, Bugfix

#3175 2022-03-11 fixes
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/M739.dm
  code/modules/halo/weapons/MA3.dm
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, Bugfix

#3176 Wide ranging tweaks
  code/game/jobs/job/job.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/weapons/M392.dm
Labels: enhancement/QOL, Balancing

#3179 Changes Covenant Radiation
  code/modules/projectiles/gun.dm
Labels: needs changelog
