Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2022-08, with the labels that each got.

#3202 X-52 Apparel & Armor Fixes
  code/modules/halo/clothing/inniearmor.dmi
  code/modules/halo/clothing/insurrectionists.dm
Labels: enhancement/QOL, Bugfix

#3206 Innie gear tweaks
  code/modules/halo/clothing/armorsets.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/insurrection/soe_outfits.dm
  code/modules/halo/leader_support/job_overrides.dm
  code/modules/halo/leader_support/supply_drop_tachud.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/leader_support/support_item.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/weapons/MA37.dm
  code/modules/halo/weapons/landmine_presets.dm
  code/modules/halo/weapons/shotguns.dm
Labels: enhancement/QOL, feature, Balancing

#3208 Removes scope pop up menu, merges use-scope(sidearm) into use-scope.
  code/modules/halo/weapons/BR85.dm
  code/modules/halo/weapons/M6C.dm
  code/modules/halo/weapons/M6D.dm
  code/modules/halo/weapons/M6S.dm
  code/modules/halo/weapons/M7.dm
  code/modules/halo/weapons/SDSR10.dm
  code/modules/halo/weapons/SRS99.dm
  code/modules/halo/weapons/_guns.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/spartan_laser.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, Bugfix

#3209 MA37 Sprites
  code/modules/halo/weapons/MA37.dm
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL

#3213 Innie cargo changes
  code/modules/halo/insurrection/access_ids.dm
  code/modules/halo/insurrection/innie_jobs.dm
  code/modules/halo/insurrection/soe_jobs.dm
  code/modules/halo/supply/innie.dm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, mapping, Bugfix

#3212 Balance tweaking
  code/game/jobs/job/job.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/covenant/invasion_scanner.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/overmap/umbilicals.dm
  code/modules/halo/unsc/jobs/officers_outfits.dm
  code/modules/halo/vehicles/vehiclebase.dm
Labels: enhancement/QOL, Balancing, Bugfix

#3214 Glove bugfix
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/halo/clothing/donor_innie.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/oni_guard.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/clothing/urf_commando_sets.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_gauntlets.dm
  code/modules/halo/covenant/species/unggoy/clothing.dm
  code/modules/halo/covenant/species/yanmee/clothing.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
Labels: enhancement/QOL

#3217 Minor fixes and tweaks
  baystation12.dme
  code/modules/halo/overmap/weapons/Energy_projector.dm
  code/modules/halo/overmap/weapons/MAC.dm
  code/modules/halo/weapons/Handgonne.dm
  code/modules/halo/weapons/SDSR10.dm
  code/modules/halo/weapons/SRS99.dm
  code/modules/halo/weapons/ammo_14-5mm.dm
  code/modules/halo/weapons/heavysniper.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: enhancement/QOL

#3218 properly integrates the suppression tweak
  code/modules/projectiles/projectile.dm
Labels: Bugfix

#3219 Backend tweaks to poplock system
  code/game/jobs/job/job.dm
  code/modules/mob/new_player/new_player.dm
Labels: Bugfix

#3220 Gamemode QoL and enjoyment tweaks
  code/modules/halo/factions/_faction.dm
  code/modules/halo/factions/objectives/_objectives.dm
  code/modules/halo/overmap/combat_npc_ship.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/faction_bases/CassiusMoonStation/destroy_effects.dm
  maps/faction_bases/ODP_Cassius/ODP_Cassius.dm
  maps/geminus_city/geminus_city_overmap.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/ks7_elmsville/overmap.dm
Labels: enhancement/QOL, feature, Balancing

#3222 shifts ONI spawn points around
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL
