Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2023-05, with the labels that each got.

#3398 Covenant Species Emotes Expansion
  code/modules/emotes/definitions/_mob.dm
  code/modules/halo/emotes/emotes.dm
  code/modules/halo/sounds/licensed/chirrup/engineer_chirrup1.ogg
  code/modules/halo/sounds/licensed/chirrup/engineer_chirrup2.ogg
  code/modules/halo/sounds/licensed/chirrup/engineer_chirrup3.ogg
  code/modules/halo/sounds/licensed/chirrup/engineer_chirrup4.ogg
  code/modules/halo/sounds/licensed/chitter/bugger_chitter.ogg
  code/modules/halo/sounds/licensed/covenant/brute_covenant.ogg
  code/modules/halo/sounds/licensed/covenant/bugger_covenant.ogg
  code/modules/halo/sounds/licensed/covenant/elite_covenant.ogg
  code/modules/halo/sounds/licensed/covenant/grunt_covenant.ogg
  code/modules/halo/sounds/licensed/covenant/jackal_covenant.ogg
  code/modules/halo/sounds/licensed/covenant/prophet_covenant.ogg
  code/modules/halo/sounds/licensed/covenant/skirmisher_covenant.ogg
  code/modules/halo/sounds/licensed/forerunner/brute_forerunner.ogg
  code/modules/halo/sounds/licensed/forerunner/bugger_forerunner.ogg
  code/modules/halo/sounds/licensed/forerunner/jackal_forerunner.ogg
  code/modules/halo/sounds/licensed/forerunner/skirmisher_forerunner.ogg
  code/modules/halo/sounds/licensed/panic/grunt_panic.ogg
  code/modules/halo/sounds/licensed/warcry/brute_warcry.ogg
Labels: enhancement/QOL

#3402 URF Liberator Overhaul & Emote Fix
  code/modules/halo/emotes/emotes.dm
  code/modules/halo/structures/blast_doors_decorative.dm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, mapping

#3400 Updates Covenant Vendors
  code/modules/halo/covenant/structures_machines/covvendors.dm
Labels: enhancement/QOL

#3401 broote melee
  code/modules/halo/weapons/covenant/brute.dm
Labels: enhancement/QOL

#3375 [READY TO MERGE] Research QOL, Jetpack Flight Failure Improvements and Covenant Forerunner Weapons
  baystation12.dme
  code/modules/halo/covenant/supply/covholyweapons.dm
  code/modules/halo/research/designs/ai.dm
  code/modules/halo/research/designs/circuits.dm
  code/modules/halo/research/designs/computers/drive.dm
  code/modules/halo/research/designs/computers/drive_portable.dm
  code/modules/halo/research/designs/computers/drive_tablet.dm
  code/modules/halo/research/designs/computers/processor.dm
  code/modules/halo/research/designs/computers/processor_tablet.dm
  code/modules/halo/research/designs/glasses_huds.dm
  code/modules/halo/research/designs/grenade.dm
  code/modules/halo/research/designs/implants.dm
  code/modules/halo/research/designs/stock_parts.dm
  code/modules/halo/research/designs/weapons.dm
  code/modules/halo/research/designs/weapons_plasma.dm
  code/modules/halo/research/techprint/types/ablative.dm
  code/modules/halo/research/techprint/types/ai.dm
  code/modules/halo/research/techprint/types/armour_upgrades.dm
  code/modules/halo/research/techprint/types/computer/computer_processing.dm
  code/modules/halo/research/techprint/types/computer/data_storage.dm
  code/modules/halo/research/techprint/types/computer_hardware.dm
  code/modules/halo/research/techprint/types/core/biology.dm
  code/modules/halo/research/techprint/types/core/energy_storage.dm
  code/modules/halo/research/techprint/types/core/lasers.dm
  code/modules/halo/research/techprint/types/core/matter_compression.dm
  code/modules/halo/research/techprint/types/core/miniaturisation.dm
  code/modules/halo/research/techprint/types/core/sensors.dm
  code/modules/halo/research/techprint/types/electromagnetism.dm
  code/modules/halo/research/techprint/types/languages.dm
  code/modules/halo/research/techprint/types/plasma.dm
  code/modules/halo/research/techprint/types/shields.dm
  code/modules/halo/research/techprint/types/weapons.dm
Labels: enhancement/QOL, Balancing, Ready
