Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2023-12, with the labels that each got.

#3513 Covenant Flashlights for all Equipment Vendors
  code/modules/halo/covenant/structures_machines/covvendors.dm
  maps/faction_bases/Cassius_Base/cassius_base.dmm
Labels: enhancement/QOL

#3514 Covenant SmartFridge, Anti-Air Emplacement, Newscaster
  baystation12.dme
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/covenant/structures_machines/newscaster.dm
  code/modules/halo/covenant/structures_machines/newscaster.dmi
  code/modules/halo/covenant/structures_machines/smartfridge.dmi
  code/modules/halo/weapons/automated_AA.dm
  code/modules/halo/weapons/icons/automated_anti_air.dmi
  icons/obj/terminals.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: spriting

#3512 Carrier form fix for stranded and reduced time between waves
  code/modules/halo/flood/types/carrier.dm
  maps/_gamemodes/firefight/_mode.dm
Labels: enhancement/QOL, Bugfix

#3517 Forerunner Wall & Floor Tiles
  baystation12.dme
  code/modules/halo/forerunner/turfs/floor.dm
  code/modules/halo/forerunner/turfs/floors.dmi
  code/modules/halo/forerunner/turfs/materials.dm
  code/modules/halo/forerunner/turfs/walls.dm
  code/modules/halo/turfs/forerunner/floor.dm
  code/modules/halo/turfs/forerunner/floors.dmi
  code/modules/halo/turfs/forerunner/walls.dm
  icons/turf/wall_masks.dmi
  maps/Exoplanet Research/ExoResearch_2.dmm
Labels: mapping, spriting

#3516 Rework the Flood firefight map "Desert Outpost"
  code/modules/halo/icons/railing.dmi
  code/modules/halo/structures/barricade.dm
  code/modules/halo/structures/stairs_decorative.dm
  icons/obj/stairs.dmi
  maps/desert_outpost/areas.dm
  maps/desert_outpost/desert_outpost1.dmm
  maps/desert_outpost/desert_outpost2.dmm
  maps/desert_outpost/desert_outpost_map.dm
  maps/desert_outpost/desert_outpost_old.dmm
  maps/desert_outpost/desert_outpost_overmap.dm
  maps/firefight/firefight.dm
  maps/firefight/map.dm
  maps/stranded/map.dm
  maps/stranded/stranded.dm
Labels: enhancement/QOL, mapping

#3518 Forerunner & Maintenance Door Sounds & Additional Flora for Mapping
  baystation12.dme
  code/modules/halo/Forerunner/airlocks/doors.dm
  code/modules/halo/doors/halo_doors.dm
  code/modules/halo/flora/ausflora.dm
  code/modules/halo/flora/ausflora.dmi
  code/modules/halo/flora/vines.dmi
  code/modules/halo/sounds/airlock_sounds/forerunnerdoor32close.ogg
  code/modules/halo/sounds/airlock_sounds/forerunnerdoor32open.ogg
  code/modules/halo/sounds/airlock_sounds/maintenance32close.ogg
  code/modules/halo/sounds/airlock_sounds/maintenance32open.ogg
Labels: enhancement/QOL, mapping

#3519 Minor Update
  code/modules/halo/covenant/species/unggoy/grunt_gear.dmi
  code/modules/halo/covenant/structures_machines/light.dmi
  code/modules/halo/covenant/structures_machines/lights.dm
  code/modules/halo/covenant/structures_machines/newscaster.dm
  code/modules/halo/covenant/structures_machines/newscaster.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: spriting

#3520 Further Sprite Fixes
  code/modules/halo/covenant/structures_machines/light.dmi
  code/modules/halo/flora/ausflora.dm
  code/modules/halo/flora/ausflora.dmi
  code/modules/halo/flora/jungle_tree.dm
  code/modules/halo/flora/jungleflora.dmi
  code/modules/halo/flora/jungletree.dmi
  code/modules/halo/flora/jungletreelarge.dmi
  code/modules/halo/flora/swamp_ausflora.dmi
  code/modules/halo/flora/swamp_ausflora_large.dmi
  code/modules/halo/flora/vines.dmi
Labels: spriting, Bugfix

#3521 Add some clutter to stranded/firefight maps and fix last wave airdrop
  maps/desert_outpost/desert_outpost1.dmm
  maps/desert_outpost/desert_outpost2.dmm
Labels: mapping
