Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2023-01, with the labels that each got.

#3237 CRS Changes and Improvements
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, mapping

#3240 The Geminus Rooftops Update
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, mapping

#3236 New Covenant Multi-tile Airlock Sounds & Other Additions
  code/game/machinery/vending.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/modules/halo/covenant/airlocks/multitile_airlocks.dm
  code/modules/halo/sounds/airlock_sounds/covenantdoor128close.ogg
  code/modules/halo/sounds/airlock_sounds/covenantdoor128open.ogg
  code/modules/halo/sounds/airlock_sounds/covenantdoor64close.ogg
  code/modules/halo/sounds/airlock_sounds/covenantdoor64open.ogg
  code/modules/halo/sounds/airlock_sounds/covenantdoor96open.ogg
  icons/obj/terminals.dmi
  icons/obj/vending.dmi
  icons/turf/flooring/decals.dmi
Labels: enhancement/QOL, feature

#3232 Mini armor patches are now mini
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/clothing/armor_repair/armor_repair_sprites.dmi
Labels: enhancement/QOL, spriting

#3242 ODP Botox Injection
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: enhancement/QOL, mapping

#3244 ODP Medbay Improvements and Airlocks
  code/game/objects/effects/decals/warning_stripes.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/sounds/r_alert_alarm_loop.ogg
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: enhancement/QOL, mapping

#3249 ODP Botox Injection 3 and Misc Changes
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/sounds/r_alert_alarm_loop.ogg
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, mapping

#3238 Profiler Subsystem
  baystation12.dme
  code/__defines/logging.dm
  code/__defines/stack_trace.dm
  code/__defines/subsystems.dm
  code/__defines/tick.dm
  code/_helpers/global_access.dm
  code/_helpers/stack_trace.dm
  code/controllers/subsystems/profiler.dm
  test/run-test.sh
Labels: enhancement/QOL

#3241 Adds callback datum
  baystation12.dme
  code/__defines/callback.dm
  code/datums/callbacks.dm
Labels: enhancement/QOL

#3246 Small bugfixes
  .gitignore
  code/__defines/colors.dm
  code/__defines/gamemode.dm
  code/__defines/items_clothing.dm
  code/__defines/math_physics.dm
  code/__defines/misc.dm
  code/__defines/mobs.dm
  code/_helpers/game.dm
  code/_helpers/icons.dm
  code/_macros.dm
  code/controllers/ProcessScheduler/core/processScheduler.dm
  code/datums/repositories/crew/~defines.dm
  code/datums/wires/vending.dm
  code/game/dna/dna2.dm
  code/game/machinery/floodlight.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/devices/suit_sensor_jammer.dm
  code/game/objects/items/devices/whistle.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/curtains.dm
  code/game/turfs/doodads/_flora.dm
  code/game/turfs/doodads/_tree.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_secrets.dm
  code/modules/alarm/alarm.dm
  code/modules/client/client_procs.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/halo/Forerunner/monitor.dm
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/research/techprint/unknown.dm
  code/modules/halo/vehicles/vehiclebase_air.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/landmine_construct.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/integrated_electronics/logic.dm
  tools/GenerateGlobalVarAccess/gen_globals.py
  tools/PunctuationChecker/punctuation-checker.py
  tools/TagMatcher/tag-matcher.py
Labels: enhancement/QOL, Bugfix

#3247 Some vscode stuff
  .editorconfig
  .git-blame-ignore-revs
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  rome.json
Labels: enhancement/QOL

#3250 ODP Overdosed on Botox
  code/modules/food/replicator.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/sounds/station_firing_sequence.ogg
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: enhancement/QOL, mapping

#3245 Various defines
  baystation12.dme
  code/__defines/lists.dm
  code/__defines/math_physics.dm
  code/__defines/subsystem-priority.dm
  code/__defines/subsystems.dm
  code/_macros.dm
Labels: enhancement/QOL

#3253 ODP Fixes and Cargo Updates
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, mapping

#3254 Earplugs
  baystation12.dme
  code/modules/halo/clothing/earplugs.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/machinery/gunvendors.dm
Labels: enhancement/QOL, feature

#3257 ODP Maintenance Changes
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: enhancement/QOL, mapping

#3258 Power Rating increase for Atmospheric Vents
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/atmospherics/components/unary/vent_scrubber.dm
Labels: Balancing

#3255 Destroyed pods now cause a random amount of damage
  code/modules/halo/vehicles/types/drop_pod.dm
Labels: enhancement/QOL, in-progress

#3259 De-legitimises the cheap tactic of slipspace-driving important round objectives
  code/modules/halo/overmap/slipspace/_slipspace.dm
  code/modules/halo/overmap/slipspace/core.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/base_assault_neutral_base/gm.dm
Labels: enhancement/QOL, Balancing

#3260 Brain Medication in Medical Vendors
  code/modules/halo/chemicals/containers.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/machinery/gunvendors.dm
Labels: enhancement/QOL, feature

#3261 ODP and CRS Adjustments
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: enhancement/QOL, mapping

#3263 Supply Drop Improvements
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/medicine/combat.dm
Labels: enhancement/QOL

#3262 Slowdown chem fix
  baystation12.dme
  code/controllers/configuration.dm
  code/modules/halo/mobs/human_movement_delay.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/shield_generators/shield.dm
Labels: enhancement/QOL, Bugfix

#3264 hidden techprint fix
  code/modules/halo/research/_global.dm
  code/modules/halo/research/techprint/_techprint.dm
  code/modules/halo/research/techprint/checks.dm
  code/modules/halo/research/techprint/unknown.dm
Labels: enhancement/QOL, Bugfix

#3266 ensures hyperzine only applies to slowdowns, instead of resetting speedboosts
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Bugfix

#3267 cloaking system tweaks
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/sounds/walk_sounds/brute_boots.ogg
  code/modules/halo/sounds/walk_sounds/spartan_boots.ogg
Labels: enhancement/QOL

#3269 Slowdown Tweaks
  code/__defines/items_clothing.dm
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/weapons/M41.dm
  code/modules/halo/weapons/M545.dm
  code/modules/halo/weapons/M739.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/halo/weapons/flamethrowers.dm
  code/modules/halo/weapons/turrets/deploy_kits.dm
  code/modules/halo/weapons/turrets/turret.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, Balancing

#3268 covenant bomb respawner for invasion
  code/modules/halo/covenant/invasion_bomb_respawner.dm
  code/modules/halo/covenant/invasion_scanner.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/CRS_Unyielding_Transgression/overmap.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/postload_includes.dm
  maps/geminus_city/invasion_geminus.dm
Labels: enhancement/QOL

#3271 SPI armour, infiltration gear and other minor tweaks
  .github/workflows/tests.yml
  baystation12.dme
  code/_helpers/time.dm
  code/_onclick/click.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/vending.dm
  code/game/objects/items.dm
  code/modules/halo/clothing/spartan_gear.dm
  code/modules/halo/clothing/spi_armour.dm
  code/modules/halo/clothing/spi_armour.dmi
  code/modules/halo/clothing/spi_armour_stealth.dm
  code/modules/halo/clothing/spi_sets.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/unggoy/armour.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/machinery/pointbased_vendor.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/misc/armourspecials/cloaking_overrides.dm
  code/modules/halo/misc/armourspecials/gear_defs.dm
  code/modules/halo/misc/door_spoofers.dm
  code/modules/halo/misc/ewar_spoofer.dmi
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/M6S.dm
  code/modules/halo/weapons/M7.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/melee.dm
  maps/crusade/hud_icons.dmi
  maps/crusade/map.dm
  maps/firefight/hud_icons.dmi
  maps/firefight/map.dm
  maps/stranded/map.dm
Labels: enhancement/QOL, feature

#3273 AI Core on Geminus
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, mapping

#3272 ODP Tweaks
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: mapping

#3274 Aroliacue Donor Gear Adjustments
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/odst.dmi
Labels: Donor

#3278 Cloak System Tweaks
  code/_onclick/click.dm
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/special_armour.dm
  code/modules/halo/misc/armourspecials/armourspecials.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/unsc/jobs/ONI.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/ks7_elmsville/hud_icons.dmi
Labels: enhancement/QOL

#3283 repair bench upgrades
  code/modules/halo/clothing/armor_repair/repair_bench.dm
  code/modules/halo/clothing/special_armour.dm
  code/modules/halo/weapons/SRS99.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/halo/weapons/forerunner/snipers.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL

#3281 Plasma Grenade Fixes + Nerf
  code/modules/halo/weapons/covenant/grenades.dm
Labels: enhancement/QOL, Balancing, Bugfix

#3280 Spec Ops English, Spartan ONI and CO Sangheili
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/species/sangheili/sangheili_outfits.dm
  code/modules/halo/covenant/species/unggoy/grunt_outfits.dm
  code/modules/halo/unsc/jobs/officers_outfits.dm
  code/modules/halo/unsc/jobs/spartan_two.dm
Labels: enhancement/QOL

#3282 Eipharius shotgun ammo box sprites + barbed wire fix
  code/modules/halo/structures/structures.dmi
  code/modules/halo/weapons/ammo_boxes.dm
  icons/obj/ammo.dmi
Labels: enhancement/QOL, spriting

#3285 Fixes and tweaks
  code/game/objects/weapons.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_defence.dm
  code/modules/halo/weapons/melee.dm
Labels: enhancement/QOL

#3286 Adds a few more checks to the projectile ignore
  code/__defines/mobs.dm
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/misc/suppression.dm
  code/modules/halo/overmap/planetfall.dm
  code/modules/maps/reader.dm
  code/modules/projectiles/gun.dm
Labels: enhancement/QOL, Bugfix

#3287 Mapfixes and Bull APC Fix
  baystation12.dme
  code/modules/halo/machinery/kitchenvendor.dm
  code/modules/halo/vehicles/types/bull.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
Labels: enhancement/QOL, mapping

#3294 XO Code Updates + Map Updates
  code/modules/halo/vehicles/types/drop_pod.dm
  maps/faction_bases/complex046/complex046.dmm
  maps/ks7_elmsville/KS7_535_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/areas.dm
Labels: enhancement/QOL, mapping

#3297 Lighting Subsystem
  baystation12.dme
  code/_helpers/global_access.dm
  code/controllers/Processes/lighting.dm
  code/controllers/subsystems/lighting.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_source.dm
  test/run-test.sh
Labels: enhancement/QOL

#3295 🌞
  baystation12.dme
  code/_global_vars/lists/objects.dm
  code/_helpers/global_access.dm
  code/controllers/Processes/sun.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/sun.dm
  code/datums/sun.dm
  test/run-test.sh
Labels: enhancement/QOL

#3298 Crash landing and night missions
  baystation12.dme
  code/game/objects/structures/grille.dm
  code/game/objects/weapons.dm
  code/game/turfs/unsimulated.dm
  code/modules/halo/covenant/simple_mobs/_covenant.dm
  code/modules/halo/covenant/turfs/floor.dm
  code/modules/halo/covenant/turfs/walls.dm
  code/modules/halo/flood/flood_constructor_builder.dm
  code/modules/halo/flood/flood_constructor_builder.dmi
  code/modules/halo/flood/flood_door.dmi
  code/modules/halo/flood/flood_doors.dm
  code/modules/halo/flood/flood_floor.dmi
  code/modules/halo/flood/flood_materials.dm
  code/modules/halo/flood/flood_turfs.dm
  code/modules/halo/flood/flood_window.dm
  code/modules/halo/flood/flood_window.dmi
  code/modules/halo/flood/floodwall.dmi
  code/modules/halo/insurrection/simple_mobs.dm
  code/modules/halo/misc/autolight.dm
  code/modules/halo/misc/payload.dm
  code/modules/halo/mobs/builder.dm
  code/modules/halo/mobs/converter.dm
  code/modules/halo/mobs/faction_builders.dm
  code/modules/halo/overmap/base_npc_ships.dm
  code/modules/halo/overmap/planetfall.dm
  code/modules/halo/sounds/airlock_sounds/flood_hit_sfx.ogg
  code/modules/halo/sounds/airlock_sounds/flood_open.ogg
  code/modules/halo/sounds/effects/rules_of_nature.ogg
  code/modules/halo/turfs/streetobjs.dm
  code/modules/halo/unsc/simple_mobs.dm
  code/modules/halo/weapons/M7.dm
  code/modules/mob/grab/grab_datum.dm
  code/modules/mob/grab/grab_object.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/multiz/turf.dm
  code/modules/overmap/sectors.dm
  icons/turf/wall_masks.dmi
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/faction_base_unsc.dm
  maps/geminus_city/areas.dm
  maps/geminus_city/geminus_city_map.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
  maps/ks7_elmsville/mapdef.dm
  maps/slayer/slayer_itemspawn_markers.dm
Labels: enhancement/QOL, feature

#3265 [READY TO MERGE] Cargo Overhaul
  baystation12.dme
  code/datums/supplypacks/supplypack.dm
  code/modules/halo/comms/channel_presets.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/covenant/supply/ammo_grenades.dm
  code/modules/halo/covenant/supply/atmospherics.dm
  code/modules/halo/covenant/supply/clothing.dm
  code/modules/halo/covenant/supply/construction.dm
  code/modules/halo/covenant/supply/covNPCs.dm
  code/modules/halo/covenant/supply/covengineering.dm
  code/modules/halo/covenant/supply/coveva.dm
  code/modules/halo/covenant/supply/covexplosives.dm
  code/modules/halo/covenant/supply/covfood.dm
  code/modules/halo/covenant/supply/covmedical.dm
  code/modules/halo/covenant/supply/covmisc.dm
  code/modules/halo/covenant/supply/covregammo.dm
  code/modules/halo/covenant/supply/covweapons.dm
  code/modules/halo/covenant/supply/equipment.dm
  code/modules/halo/covenant/supply/weapons.dm
  code/modules/halo/factions/supply.dm
  code/modules/halo/unsc/supply/NPCs.dm
  code/modules/halo/unsc/supply/ammo.dm
  code/modules/halo/unsc/supply/engineering.dm
  code/modules/halo/unsc/supply/eva.dm
  code/modules/halo/unsc/supply/explosives.dm
  code/modules/halo/unsc/supply/food.dm
  code/modules/halo/unsc/supply/gear.dm
  code/modules/halo/unsc/supply/medical.dm
  code/modules/halo/unsc/supply/misc.dm
  code/modules/halo/unsc/supply/regammo.dm
  code/modules/halo/unsc/supply/specammo.dm
  code/modules/halo/unsc/supply/weapons.dm
  code/modules/halo/weapons/covenant/cov_ammo_boxes.dm
Labels: enhancement/QOL, mapping, feature

#3315 Stealth static colour and vehicle exit fixes
  code/modules/halo/clothing/jetpacks.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/multiz/turf.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/unsc_achlys/achlys_areas.dm
Labels: enhancement/QOL, Balancing

#3316 Readds telecomms jammers as actual useful items.
  code/controllers/communications.dm
  code/modules/halo/comms/__readme_defines.dm
  code/modules/halo/comms/machines/jammer.dm
  code/modules/halo/comms/machines/telecomms_64.dmi
  code/modules/halo/comms/machines/telecomms_jammers.dmi
  code/modules/halo/comms/telecomms_jammers.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, feature

#3322 Difference of Opinion QOL Update
  maps/UNSC_Difference_Of_Opinion/unscDoO.dmm
Labels: enhancement/QOL, mapping

#3318 melee embed fix 2
  code/modules/halo/storage/pocketstorage.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Balancing

#3324 crashland deletes important objects
  code/modules/halo/misc/autolight_and_weather.dm
  code/modules/halo/overmap/planetfall.dm
Labels: enhancement/QOL

#3310 Disables the globals_access MD5 check
  test/run-test.sh
Labels: enhancement/QOL

#3326 ONI Cargo Fixes and Reduction of Equipment in Vendors
  baystation12.dme
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/machinery/pointbased_vendor.dm
  code/modules/halo/trade/trade_items/bars.dm
  code/modules/halo/unsc/supply/NPCs.dm
  code/modules/halo/unsc/supply/engineering.dm
  code/modules/halo/unsc/supply/eva.dm
  code/modules/halo/unsc/supply/explosives.dm
  code/modules/halo/unsc/supply/food.dm
  code/modules/halo/unsc/supply/medical.dm
  code/modules/halo/unsc/supply/misc.dm
  code/modules/halo/unsc/supply/onispecial.dm
  code/modules/halo/unsc/supply/regammo.dm
  code/modules/halo/unsc/supply/specammo.dm
  code/modules/halo/unsc/supply/weapons.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/covenant/launchers.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
Labels: enhancement/QOL, mapping

#3325 geminus area fix
  code/game/objects/items/weapons/storage/uplink_kits.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_attack.dm
  code/modules/halo/misc/autolight_and_weather.dm
  code/modules/halo/overmap/planetfall.dm
  code/modules/halo/unsc/jobs/ODST.dm
  code/modules/halo/vehicles/supply_pods.dm
  code/modules/overmap/exoplanets/desert.dm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, Bugfix

#3307 Event subsystem
  baystation12.dme
  code/_helpers/global_access.dm
  code/controllers/Processes/event.dm
  code/controllers/subsystems/event.dm
  code/controllers/verbs.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gameticker.dm
  code/modules/events/event.dm
  code/modules/modular_computers/file_system/programs/command/comm.dm
  code/modules/overmap/events/event.dm
Labels: enhancement/QOL

#3302 Inactivity subsystem
  baystation12.dme
  code/_helpers/global_access.dm
  code/controllers/Processes/inactivity.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/inactivity.dm
Labels: enhancement/QOL

#3331 selling stacks now multiplies price by the stack number
  code/modules/halo/NPC/npc.dm
  code/modules/halo/NPC/npc_buysell.dm
  code/modules/halo/NPC/npc_trade.dm
Labels: enhancement/QOL

#3333 Braindeath on ghost
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/vehicles/mobile_spawn_datums.dm
  code/modules/halo/weapons/M545.dm
  code/modules/halo/weapons/M739.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/organs/_organ_setup.dm
Labels: enhancement/QOL, Balancing

#3343 [READY TO MERGE] Map Updates, Huragok Changes and More
  baystation12.dme
  code/game/machinery/bioprinter.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/covenant/species/huragok/robot_items.dm
  code/modules/halo/covenant/species/huragok/robot_modules.dm
  code/modules/halo/covenant/structures_machines/energybarricade_vacuum.dm
  code/modules/halo/misc/RCD_modified.dm
  code/modules/halo/unsc/supply/food.dm
  code/modules/halo/unsc/supply/onispecial.dm
  code/modules/halo/unsc/supply/regammo.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Difference_Of_Opinion/unscDoO.dmm
  maps/area_holders/include.dm
  maps/area_holders/overmap_ship_area_holder.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
Labels: enhancement/QOL, feature

#3344 Orion convert item
  baystation12.dme
  code/modules/halo/insurrection/orion.dm
  code/modules/halo/insurrection/orion_gear.dm
  code/modules/halo/misc/neural_lace_injectors.dm
  code/modules/halo/misc/species_converter.dm
Labels: enhancement/QOL, feature

#3347 Wave respawns and some popbalance tweaks
  code/game/jobs/job/job.dm
  code/modules/halo/factions/_faction.dm
  code/modules/halo/vehicles/mobile_spawn_datums.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/observer/ghost/ghost.dm
  maps/_gamemodes/_popbalance.dm
Labels: enhancement/QOL, feature

#3348 Orion conversion syringe in-game
  code/modules/halo/trade/trade_items/bars.dm
  code/modules/halo/trade/trade_items/ore.dm
  code/modules/halo/unsc/supply/onispecial.dm
  maps/faction_bases/complex046/complex046.dmm
Labels: feature

#3350 Orion Price Increase
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/jumpsuits.dm
  code/modules/halo/covenant/supply/covengineering.dm
  code/modules/halo/sounds/HybridRifleFiring.ogg
  code/modules/halo/trade/trade_items/bars.dm
  code/modules/halo/trade/trade_items/crops.dm
  code/modules/halo/trade/trade_items/organs.dm
  code/modules/halo/unsc/jobs/officers_outfits.dm
  code/modules/halo/unsc/supply/engineering.dm
  code/modules/halo/unsc/supply/onispecial.dm
  code/modules/halo/weapons/icons/Back_Weapons64.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
  code/modules/halo/weapons/icons/forerunner_sprites64.dmi
  code/modules/halo/weapons/icons/machete.dmi
  code/modules/halo/weapons/icons/weapon_sprites_inhand64_l.dmi
  code/modules/halo/weapons/icons/weapon_sprites_inhand64_r.dmi
  code/modules/halo/weapons/melee.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/UNSC_Difference_Of_Opinion/unscDoO.dmm
  maps/faction_bases/CassiusMoonStation/CassiusMoon.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/npc_ships/req_console_ships/cov_tender.dmm
  maps/npc_ships/req_console_ships/unsc_tender.dmm
  maps/npc_ships/req_console_ships/urf_tender.dmm
Labels: enhancement/QOL, Balancing, Bugfix

#3353 shotshell and explosion throw rebalance
  code/modules/halo/weapons/ammo_shotshell.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: enhancement/QOL, Balancing

#3354 makes tracerless ammo urf bolt action rifle only
  code/modules/halo/unsc/supply/specammo.dm
  code/modules/halo/weapons/Handgonne.dm
  code/modules/halo/weapons/SRS99.dm
  code/modules/halo/weapons/ammo_14-5mm.dm
  code/modules/halo/weapons/heavysniper.dm
Labels: enhancement/QOL

#3355 Neural lace improvements
  code/__defines/items_clothing.dm
  code/modules/halo/clothing/yanmee_wings.dm
  code/modules/halo/clothing/yanmee_wings.dmi
  code/modules/halo/covenant/items/cards.dm
  code/modules/halo/covenant/species/tvoan/skirm_clothing.dmi
  code/modules/halo/covenant/species/tvoan/skirmisher_armour.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_gauntlets.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_greaves.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_helmet.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_outfits.dm
  code/modules/halo/covenant/species/yanmee/clothing.dm
  code/modules/halo/covenant/species/yanmee/yanmee_gear.dmi
  code/modules/halo/covenant/species/yanmee/yanmee_outfits.dm
  code/modules/halo/misc/neural_lace_injectors.dm
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/unsc/supply/onispecial.dm
  code/modules/halo/weapons/M6D.dm
  code/modules/halo/weapons/M6S.dm
  icons/obj/assemblies.dmi
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
Labels: enhancement/QOL, mapping, spriting

#3356 Large Radio text and ammodrop tweaks
  baystation12.dme
  code/game/jobs/job/job.dm
  code/modules/clothing/clothing.dm
  code/modules/halo/_defs_radio_speech_sizes.dm
  code/modules/halo/colonist/jobs.dm
  code/modules/halo/covenant/jobs/AI.dm
  code/modules/halo/covenant/jobs/huragok.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/covenant/jobs/mgalekgolo.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/jobs/sanshyuum.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/jobs/unggoy.dm
  code/modules/halo/covenant/jobs/yanmee.dm
  code/modules/halo/insurrection/innie_jobs.dm
  code/modules/halo/insurrection/soe_jobs.dm
  code/modules/halo/insurrection/x52_jobs.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/unsc/jobs/ODST.dm
  code/modules/halo/unsc/jobs/ONI.dm
  code/modules/halo/unsc/jobs/ai.dm
  code/modules/halo/unsc/jobs/crew.dm
  code/modules/halo/unsc/jobs/marines.dm
  code/modules/halo/unsc/jobs/officers.dm
  code/modules/halo/unsc/jobs/spartan_two.dm
  code/modules/halo/weapons/forerunner/snipers.dm
  code/modules/mob/hear_say.dm
Labels: enhancement/QOL

#3357 Grenade effectiveness tweaks
  code/game/objects/items/weapons/grenades/grenade.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo.dm
  code/modules/halo/covenant/species/lekgolo/lekgolo_defence.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/grenades.dm
  code/modules/halo/weapons/forerunner/grenade.dm
  code/modules/halo/weapons/grenades.dm
Labels: enhancement/QOL, Balancing

#3358 Projectile Parry Tweaks
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/weapons.dm
  code/modules/halo/weapons/melee.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: enhancement/QOL, Balancing

#3359 Adds Prophet to Geminus
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/species/sanshyuum/clothing.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
Labels: enhancement/QOL, feature, Balancing, Bugfix

#3365 UNSC DoO General Map Fixes and QoL
  maps/UNSC_Difference_Of_Opinion/unscDoO.dmm
Labels: enhancement/QOL, mapping

#3368 modfies grabbing's effects to be less oppressive and fixes an exploit with ZEAL armour
  code/modules/halo/clothing/insurrectionists.dm
  code/modules/halo/clothing/spi_armour.dm
  code/modules/mob/grab/grab_datum.dm
  code/modules/mob/grab/grab_object.dm
  code/modules/mob/grab/normal/norm_aggressive.dm
  code/modules/mob/grab/normal/norm_kill.dm
  code/modules/mob/grab/normal/norm_neck.dm
Labels: Balancing, Bugfix

#3370 Minor balance tweaks and a cool brute hammer buff
  code/modules/halo/misc/armourspecials/cloaking.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/forerunner/ammo.dm
Labels: enhancement/QOL, Balancing

#3371 reduces damage dealt by jetpack flight failure
  code/modules/mob/living/life.dm
Labels: enhancement/QOL, Balancing

#3376 Storage Item Slowdown Tweaks
  code/__defines/items_clothing.dm
  code/game/objects/items/weapons/storage/storage.dm
  maps/UNSC_Difference_Of_Opinion/unscDoO.dmm
Labels: enhancement/QOL, Balancing
