Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2023-07, with the labels that each got.

#3411 Geminus Hospital Stair Fix
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, Bugfix

#3414 suppressor tweak
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/halo/weapons/forerunner/rifles.dm
Labels: enhancement/QOL

#3415 Promethean weapon balance pass
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_gauntlets.dm
  code/modules/halo/covenant/supply/covholyweapons.dm
  code/modules/halo/weapons/ammo_7-62mm.dm
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/halo/weapons/forerunner/rifles.dm
Labels: enhancement/QOL, Balancing

#3416 SDSR sniper
  code/modules/halo/weapons/SDSR10.dm
Labels: Balancing

#3417 Experimental UNSC weapon supply drop
  baystation12.dme
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/research/designs/weapons.dm
  code/modules/halo/sounds/Spartan_Laser_Charge_Sound_Effect.ogg
  code/modules/halo/sounds/Spartan_Laser_Shot_Sound_Effect.ogg
  code/modules/halo/sounds/railgun_charge.ogg
  code/modules/halo/sounds/railgun_fire.ogg
  code/modules/halo/unsc/supply/specweapons.dm
  code/modules/halo/weapons/ammo_boxes.dm
  code/modules/halo/weapons/ammo_railslug.dm
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/railrifle.dm
  code/modules/halo/weapons/spartan_laser.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL, Balancing

#3419 CRS Unyielding Transgression Engineering Tool Storage Addition
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, mapping

#3418 adds the weapons from #3417 to the ONI arsenal too
  code/modules/halo/unsc/supply/specweapons.dm
  code/modules/halo/weapons/ammo_railslug.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/spartan_laser.dm
Labels: enhancement/QOL, Balancing

#3420 Nanoui object interactivity fix
  code/_onclick/adjacent.dm
  code/modules/halo/Forerunner/sentinel.dm
Labels: enhancement/QOL, Balancing

#3421 Donator Gear Update
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_innie.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/urf_commando.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj.dmi
  code/modules/halo/covenant/species/lekgolo/hunters.dmi
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: Donor

#3422 Allows for Belt Internals
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: enhancement/QOL

#3423 urf now has armory
  maps/operation_trebuchet/innie_base4.dmm
Labels: enhancement/QOL, mapping

#3424 SPI/Briefs Sprite Fixes
  code/modules/halo/clothing/spi_armour.dm
  code/modules/halo/clothing/spi_armour.dmi
  icons/mob/human.dmi
Labels: enhancement/QOL

#3425 CRS and Geminus Maptweaks
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, mapping
