Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2023-08, with the labels that each got.

#3427 Less armor for URF and UNSC NPC MAC ships.
  maps/npc_ships/req_console_ships/unsc_macplatform_experimental.dmm
  maps/npc_ships/req_console_ships/urf_macplatform_experimental.dmm
Labels: enhancement/QOL, mapping, Balancing

#3428 Fixes Husky's donor armor
  code/modules/halo/clothing/spartan_armour.dmi
Labels: enhancement/QOL

#3429 Boltshot tweaks
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/halo/weapons/forerunner/pistols.dm
  code/modules/halo/weapons/forerunner/rifles.dm
Labels: enhancement/QOL, Balancing

#3432 MultiZ Visibility Tweaks, Toproping Removal
  code/game/objects/structures/signs.dm
  code/modules/economy/ATM.dm
  code/modules/halo/misc/capture_node.dm
  code/modules/multiz/movement.dm
  code/modules/power/lighting.dm
Labels: enhancement/QOL, mapping, Controversial

#3430 DMR anti shield buff
  code/modules/halo/factions/objectives/objectives_innie.dm
  code/modules/halo/leader_support/job_overrides.dm
  code/modules/halo/weapons/ammo_7-62mm.dm
  code/modules/halo/weapons/covenant/ammo.dm
Labels: enhancement/QOL, Balancing

#3433 Planetary's Donator Murmillo Armor
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/tvoan/skirm_clothing.dmi
Labels: spriting, Donor

#3434 Timmypool's Donator Sangheili Minor Armor & Marshal KS7 Overhaul
  baystation12.dme
  code/modules/halo/clothing/civilian.dm
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/marshal.dm
  code/modules/halo/clothing/marshal.dmi
  code/modules/halo/comms/channel_presets.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  icons/mob/uniform.dmi
  maps/first_contact/jobs.dm
  maps/ks7_elmsville/KS7_535_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
  maps/ks7_elmsville/areas.dm
  maps/ks7_elmsville/hud_icons.dmi
  maps/ks7_elmsville/includes_pvp.dm
  maps/ks7_elmsville/jobdefs.dm
  maps/ks7_elmsville/lift.dm
  maps/ks7_elmsville/outfits.dm
  maps/ks7_elmsville/presets.dm
  maps/system_conquest/jobs.dm
Labels: enhancement/QOL, mapping, spriting, Bugfix, Donor

#3436 KS7 Marshal Spawnpoint Fix
  maps/ks7_elmsville/KS7_535_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/spawns_jobs.dm
Labels: Bugfix

#3437 suppressor smg analogue
  code/modules/halo/weapons/forerunner/ammo.dm
Labels: enhancement/QOL, Balancing

#3438 captain's ID fix
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/covenant/access.dm
  code/modules/halo/unsc/access.dm
Labels: Bugfix

#3440 ODST sprites resprite
  code/modules/halo/clothing/odst.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
Labels: enhancement/QOL, spriting

#3439 [READY TO MERGE] Medical Improvements
  code/__defines/items_clothing.dm
  code/game/machinery/Sleeper.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/halo/clothing/jumpsuits.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/covenant/items/ammo_belt.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/machinery/gunvendors.dm
Labels: enhancement/QOL, Balancing

#3441 QOL Visual/Audio Tweaks
  code/game/jobs/job/job.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/sounds/r_alert_alarm_loop.ogg
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  sound/effects/siren.ogg
Labels: enhancement/QOL

#3443 URF Liberator Cryo-Room Addition
  maps/urf_flagship/first_deck.dmm
Labels: mapping

#3442 Biofoam Sprites, Larger Pills & Smoke Grenade Buff
  code/game/objects/effects/effect_system.dm
  code/modules/halo/chemicals/containers.dm
  code/modules/halo/covenant/medical/first_aid.dm
  code/modules/halo/covenant/supply/covmedical.dm
  code/modules/halo/medicine/biofoam.dmi
  code/modules/halo/outfits/mobile_spawn_outfits.dm
  code/modules/halo/storage/IFAK.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, spriting

#3444 KS7 Marshal PD Fixes
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
Labels: enhancement/QOL, mapping

#3445 MA3 Worn Sprite Fix
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
Labels: Bugfix

#3447 Sound Updates, Marshal Buff, Warthog Crate Inventory
  code/game/gamemodes/events.dm
  code/game/gamemodes/events/power_failure.dm
  code/modules/halo/clothing/civilian.dm
  code/modules/halo/clothing/marshal.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/sounds/AI/Green_Alert_UNSC.ogg
  code/modules/halo/sounds/AI/Red_Alert_UNSC.ogg
  code/modules/halo/sounds/effects/Alert_State_Change.ogg
  code/modules/halo/sounds/effects/slipspace_jump.ogg
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/overmap/sectors.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/urf_flagship/overmap.dm
  sound/ambience/shipambience.ogg
  sound/effects/Explosion1.ogg
  sound/effects/Explosion2.ogg
Labels: enhancement/QOL, Experimental

#3446 M45t Shotgun Armor & Back Sprite & Police M6B Fire Effect
  code/modules/halo/sounds/Magnum_Low_Power_Fire.ogg
  code/modules/halo/weapons/M6D.dm
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/shotguns.dm
Labels: enhancement/QOL, spriting

#3449 MA3 Sprite Fix & M45t Worn Sprite Resize
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
Labels: Bugfix

#3453 fixes ex_act applicability
  code/game/objects/explosion.dm
Labels: enhancement/QOL, Balancing

#3452 Lore accurate button
  baystation12.dme
  code/game/objects/explosion.dm
  code/modules/halo/admin/lore_accurate.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/weapons/covenant/shield_gauntlet.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: enhancement/QOL, feature

#3451 Flamer and Sentinel Beam tweaks
  code/modules/halo/Forerunner/sentinel.dm
  code/modules/halo/weapons/flamethrowers.dm
Labels: enhancement/QOL, Balancing

#3454 Donator Armor
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/spartan_armour.dmi
  code/modules/halo/clothing/spi_armour.dmi
Labels: Donor

#3455 New Flood Carrier & Infection Form Sprite
  code/modules/halo/flood/flood_carrier.dmi
  code/modules/halo/flood/flood_carrier_old.dmi
  code/modules/halo/flood/flood_infection.dmi
  code/modules/halo/flood/flood_infection_old.dmi
  code/modules/halo/flood/types/carrier.dm
  code/modules/halo/flood/types/infestor.dm
Labels: spriting

#3460 Donator Gear Update
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_innie.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/odst.dmi
  code/modules/halo/clothing/odst_items.dmi
  code/modules/halo/covenant/species/unggoy/grunt_gear.dmi
  code/modules/halo/sounds/Mojave_Shotgun_Fire.ogg
  code/modules/halo/sounds/Mojave_Shotgun_Reload.ogg
  code/modules/halo/weapons/icons/Armor_Weapons.dmi
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL, Donor

#3459 Medical Equipment Improvements
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/halo/chemicals/containers.dm
  code/modules/halo/chemicals/medicine.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/machinery/buttons/alertbutton.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/organs/internal/brain.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, Balancing, Bugfix

#3463 Cryo Cell Guide
  code/modules/paperwork/paper.dm
  code/modules/reagents/reagent_containers/glass.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, mapping

#3464 Map Bugfixes, Chemistry Station Layering and Donor Gear Additions
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/dispenser/dispenser2.dm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, spriting, Bugfix

#3465 Eluxor's New Unggoy Sprites
  code/modules/halo/covenant/species/unggoy/armour.dm
  code/modules/halo/covenant/species/unggoy/grunt_gear.dmi
  code/modules/halo/covenant/species/unggoy/grunt_outfits.dm
  code/modules/halo/covenant/species/unggoy/r_unggoy.dmi
Labels: enhancement/QOL, spriting

#3466 Bruteshot Buff
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/weapons/covenant/brute.dm
Labels: enhancement/QOL, Balancing

#3461 KS7 Marshal + Hospital update + KS7 Area Icon update
  code/modules/clothing/under/accessories/badges.dm
  code/modules/halo/clothing/marshal.dm
  code/modules/halo/clothing/marshal.dmi
  icons/turf/areas.dmi
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/areas.dm
  maps/ks7_elmsville/hud_icons.dmi
  maps/ks7_elmsville/outfits.dm
  maps/ks7_elmsville/presets.dm
Labels: enhancement/QOL, mapping, spriting

#3467 scanpoint pinpointer tweaks
  code/modules/halo/covenant/invasion_scanner_pinpointers.dm
Labels: enhancement/QOL

#3468 objective secured capture node update
  code/modules/halo/misc/capture_node.dm
Labels: enhancement/QOL

#3470 Domodly's Donor Armor Fix
  code/modules/halo/clothing/donor_covenant.dm
Labels: Bugfix

#3471 EVA Rework
  baystation12.dme
  code/game/area/Space Station 13 areas.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/halo/clothing/armorsets.dm
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/oldeva.dmi
  code/modules/halo/clothing/spartan_armour_abilities_types.dm
  code/modules/halo/clothing/urf_commando.dm
  code/modules/halo/covenant/jobs/jiralhanae.dm
  code/modules/halo/covenant/jobs/kigyar.dm
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
  code/modules/halo/covenant/species/kigyar/clothing.dm
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/species/kigyar/kigyar_ranger.dm
  code/modules/halo/covenant/species/kigyar/ranger_kigyar.dmi
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/halo/covenant/species/sangheili/armoursets.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/sangheili/sangheili_outfits.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/covenant/supply/coveva.dm
  code/modules/halo/flood/flood.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/misc/armourspecials/gear_defs.dm
  code/modules/halo/misc/armourspecials/integrated_jetpack.dm
  code/modules/halo/sounds/space_ambience/Asphalt_And_Ablution.ogg
  code/modules/halo/sounds/space_ambience/From_Bones.ogg
  code/modules/halo/sounds/space_ambience/Glue.ogg
  code/modules/halo/sounds/space_ambience/Proceed_With_Caution.ogg
  code/modules/halo/sounds/space_ambience/Rain.ogg
  code/modules/halo/unsc/jobs/marines.dm
  code/modules/halo/unsc/jobs/marines_outfits.dm
  code/modules/halo/unsc/supply/eva.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  sound/effects/magboot_on.ogg
Labels: enhancement/QOL, Zlevels, feature, spriting, Balancing

#3472 Ilikesaying's Donor Fix
  code/modules/halo/clothing/donor_covenant.dm
  code/modules/halo/covenant/species/unggoy/grunt_gear.dmi
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/icons/Covenant_Projectiles.dmi
Labels: Bugfix

#3473 gun tracking and brute unpowered yeet fix
  code/controllers/voting/initiate_vote.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/overmap/sectors.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: enhancement/QOL, Balancing

#3476 EVA Bugfixes, Balance Changes and QOL Improvements
  code/modules/halo/clothing/armor_repair/armor_patch.dm
  code/modules/halo/clothing/armor_repair/clothing.dm
  code/modules/halo/clothing/marine.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_helmet.dm
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/machinery/gunvendors.dm
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/sounds/effects/armor_break.ogg
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/rifles.dm
Labels: enhancement/QOL, Balancing, Bugfix

#3477 Halo HUD element scaling and squad manager overhaul
  baystation12.dme
  code/_helpers/sanitize_values.dm
  code/modules/halo/misc/armourspecials/shields.dm
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/misc/halo_hud_scaling_pref.dm
  code/modules/halo/misc/loot_distributor.dm
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/squads/human_move_override.dm
  code/modules/halo/squads/squad-waypoint-controller.dm
  code/modules/halo/squads/squad-waypoint-manager.dm
  code/modules/halo/squads/waypoint_object.dm
  code/modules/halo/weapons/hud_counter.dm
Labels: enhancement/QOL, feature

#3478 System Conquest Barebones Implement
  baystation12.dme
  code/modules/halo/misc/capture_node.dm
  code/modules/halo/misc/loot_distributor.dm
  code/modules/halo/misc/system_conquest_console_spawns.dm
  code/modules/halo/overmap/automated_defense.dm
  code/modules/halo/overmap/nav_data_computer.dm
  maps/Exoplanet Research/ExoResearch_0.dmm
  maps/Exoplanet Research/ExoResearch_1.dmm
  maps/Exoplanet Research/ExoResearch_2.dmm
  maps/_gamemodes/gamemode_overrides.dm
  maps/_gamemodes/invasion/gamemode.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/_gamemodes/system_conquest/objectives/_SC_objectives.dm
  maps/_gamemodes/system_conquest/objectives/objective_attack.dm
  maps/_gamemodes/system_conquest/objectives/objective_hold.dm
  maps/_gamemodes/system_conquest/system_conquest.dm
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/glassed_planet/glassed_planet_1.dmm
  maps/glassed_planet/glassed_planet_2.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
  maps/ks7_elmsville/areas.dm
  maps/ks7_elmsville/includes_pvp.dm
  maps/ks7_elmsville/presets_pvp_additions.dm
  maps/system_conquest/mapfile.dm
Labels: enhancement/QOL, feature

#3479 urf slot opens on deaths
  code/modules/halo/insurrection/innie_jobs.dm
  code/modules/halo/insurrection/soe_jobs.dm
Labels: enhancement/QOL

#3481 hud glasses fix
  code/modules/halo/squads/hud_glasses.dm
  code/modules/halo/squads/human_move_override.dm
  code/modules/halo/squads/squad-waypoint-controller.dm
Labels: Bugfix

#3480 Capture node timescale fix
  code/modules/halo/misc/capture_node.dm
  maps/ks7_elmsville/presets.dm
Labels: Bugfix

#3482 minor plasma rifle max ammo buff
  code/modules/halo/weapons/covenant/rifles.dm
Labels: enhancement/QOL, Balancing

#3483 energy projector noheat fixes
  code/game/turfs/unsimulated/lava.dm
  code/modules/halo/overmap/weapons/Energy_projector.dm
Labels: Bugfix

#3484 base miss chance raise
  code/modules/mob/mob_helpers.dm
Labels: enhancement/QOL, Balancing

#3485 Mechs in cargo
  baystation12.dme
  code/game/supplyshuttle.dm
  code/modules/halo/covenant/supply/covvehicles.dm
  code/modules/halo/factions/__defs.dm
  code/modules/halo/factions/player_factions.dm
  code/modules/halo/unsc/supply/vehicles.dm
  nano/templates/faction_supply.tmpl
Labels: enhancement/QOL, feature

#3489 System conquest fixes
  maps/_gamemodes/system_conquest/objectives/_SC_objectives.dm
  maps/_gamemodes/system_conquest/objectives/objective_attack.dm
  maps/_gamemodes/system_conquest/objectives/objective_hold.dm
Labels: enhancement/QOL

#3488 Melee Stances
  baystation12.dme
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/factions/npc_factions/gear/electric_axe.dm
  code/modules/halo/factions/npc_factions/gear/explosive_spear.dm
  code/modules/halo/misc/melee_strikes.dm
  code/modules/halo/weapons/_lunging.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/halo/weapons/covenant/melee.dm
  code/modules/halo/weapons/forerunner/melee.dm
  code/modules/halo/weapons/icons/Covenant Weapons.dmi
  code/modules/halo/weapons/melee.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: enhancement/QOL, feature

#3487 Income buffs
  code/modules/halo/factions/player_factions.dm
Labels: enhancement/QOL, Balancing

#3458 Adds explosive immunity to stairs
  code/modules/multiz/structures.dm
Labels: enhancement/QOL, Zlevels, mapping, feature, Balancing

#3490 DoO hull segments
  maps/UNSC_Difference_Of_Opinion/unscDoO.dmm
Labels: enhancement/QOL, mapping

#3492 System conquest fixes
  code/modules/halo/clothing/special_armour_procs.dm
  code/modules/halo/overmap/req_console_ships.dm
Labels: Bugfix

#3494 Systems Conquest Faction Base Update
  code/modules/halo/covenant/structures_machines/covenant_steps.dmi
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/covenant/structures_machines/ramp.dm
  code/modules/halo/machinery/gunvendors.dm
  maps/faction_bases/Cassius_Base/cassius_base.dmm
  maps/faction_bases/cov_base/Covenant_Station.dmm
  maps/faction_bases/innie_base/Innie_Base.dmm
Labels: enhancement/QOL, mapping, Ready

#3496 Wall Ambient Occlusion, More Lighting Changes and ODP Detailing
  baystation12.dme
  code/__defines/_planes+layers.dm
  code/__defines/ao.dm
  code/__defines/ao_misc.dm
  code/__defines/directions.dm
  code/__defines/lighting.dm
  code/_helpers/global_access.dm
  code/controllers/subsystems/ao.dm
  code/game/atoms.dm
  code/game/objects/structures/catwalk.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_ao.dm
  code/game/turfs/turf_changing.dm
  icons/effects/lighting_overlay.dmi
  icons/turf/flooring/shadows.dmi
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  test/check-paths.sh
Labels: enhancement/QOL, mapping

#3498 Fixes Goblins (Pnap Battlesuits) Not Showing In Cargo
  code/modules/halo/covenant/supply/covvehicles.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
Labels: enhancement/QOL, Bugfix, Vehicles

#3497 [TESTMERGE] Ports Baystation Air Subsystem
  baystation12.dme
  code/__defines/ZAS.dm
  code/_helpers/global_access.dm
  code/_helpers/unsorted.dm
  code/controllers/Processes/air.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/processing/airflow.dm
  code/controllers/verbs.dm
  code/game/machinery/doors/door.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/turf_changing.dm
  code/modules/ZAS/Airflow.dm
  code/modules/ZAS/Atom.dm
  code/modules/ZAS/Connection.dm
  code/modules/ZAS/ConnectionGroup.dm
  code/modules/ZAS/Controller.dm
  code/modules/ZAS/Diagnostic.dm
  code/modules/ZAS/Fire.dm
  code/modules/ZAS/Turf.dm
  code/modules/ZAS/Zone.dm
  code/modules/ZAS/_docs.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/admin/verbs/grief_fixers.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/atmospherics/components/unary/heat_exchanger.dm
  code/modules/atmospherics/components/unary/thermal_plate.dm
  code/modules/maps/reader.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/overmap/exoplanets/exoplanet.dm
Labels: enhancement/QOL, ZAS, Zlevels, feature, Experimental

#3499 Ilikesaying's Donor Marine Armor
  code/modules/halo/clothing/donor_unsc.dm
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/clothing/marine_items.dmi
Labels: Donor

#3501 Bruteshot Nerf, Bodypart Toughness and Vehicle Repair Buff
  code/modules/halo/covenant/jobs/AI.dm
  code/modules/halo/misc/explosion_debris.dm
  code/modules/halo/unsc/jobs/ai.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/organs/external/head.dm
  code/modules/organs/external/standard.dm
Labels: enhancement/QOL, Balancing

#3500 New Hairstyles Update & Donor Gear Adjustment
  code/modules/halo/clothing/marine.dmi
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: enhancement/QOL, spriting, Donor

#3502 AI Balance Tweak
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Balancing

#3505 Human Audible Emotes & Anti-Matter Resprite
  code/modules/emotes/definitions/_mob.dm
  code/modules/halo/emotes/emotes.dm
  code/modules/halo/misc/payload.dmi
  code/modules/halo/sounds/species_audibles/femhuman1/femalert1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femberserk1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femcharge1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femcurse1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femgloat1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femmedic1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femoorah1.ogg
  code/modules/halo/sounds/species_audibles/femhuman1/femtaunt1.ogg
  code/modules/halo/sounds/species_audibles/human1/alert1.ogg
  code/modules/halo/sounds/species_audibles/human1/berserk1.ogg
  code/modules/halo/sounds/species_audibles/human1/charge1.ogg
  code/modules/halo/sounds/species_audibles/human1/curse1.ogg
  code/modules/halo/sounds/species_audibles/human1/gloat1.ogg
  code/modules/halo/sounds/species_audibles/human1/medic1.ogg
  code/modules/halo/sounds/species_audibles/human1/oorah1.ogg
  code/modules/halo/sounds/species_audibles/human1/taunt1.ogg
  code/modules/halo/sounds/species_audibles/human2/alert2.ogg
  code/modules/halo/sounds/species_audibles/human2/berserk2.ogg
  code/modules/halo/sounds/species_audibles/human2/charge2.ogg
  code/modules/halo/sounds/species_audibles/human2/curse2.ogg
  code/modules/halo/sounds/species_audibles/human2/gloat2.ogg
  code/modules/halo/sounds/species_audibles/human2/medic2.ogg
  code/modules/halo/sounds/species_audibles/human2/oorah2.ogg
  code/modules/halo/sounds/species_audibles/human2/taunt2.ogg
  code/modules/halo/sounds/species_audibles/human3/alert3.ogg
  code/modules/halo/sounds/species_audibles/human3/berserk3.ogg
  code/modules/halo/sounds/species_audibles/human3/charge3.ogg
  code/modules/halo/sounds/species_audibles/human3/curse3.ogg
  code/modules/halo/sounds/species_audibles/human3/gloat3.ogg
  code/modules/halo/sounds/species_audibles/human3/medic3.ogg
  code/modules/halo/sounds/species_audibles/human3/oorah3.ogg
  code/modules/halo/sounds/species_audibles/human3/taunt3.ogg
  code/modules/halo/sounds/species_audibles/human4/alert4.ogg
  code/modules/halo/sounds/species_audibles/human4/berserk4.ogg
  code/modules/halo/sounds/species_audibles/human4/charge4.ogg
  code/modules/halo/sounds/species_audibles/human4/curse4.ogg
  code/modules/halo/sounds/species_audibles/human4/gloat4.ogg
  code/modules/halo/sounds/species_audibles/human4/medic4.ogg
  code/modules/halo/sounds/species_audibles/human4/oorah4.ogg
  code/modules/halo/sounds/species_audibles/human4/taunt4.ogg
Labels: enhancement/QOL, feature, spriting

#3503 Many tweaks
  baystation12.dme
  code/game/objects/structures/flora.dm
  code/game/turfs/doodads/_flora.dm
  code/modules/halo/abilities/flight.dm
  code/modules/halo/covenant/supply/covvehicles.dm
  code/modules/halo/flora/swamp_mushrooms.dm
  code/modules/halo/flora/swamp_tree.dm
  code/modules/halo/icons/flora/swamp_mushroom.dmi
  code/modules/halo/icons/flora/swamp_tree.dmi
  code/modules/halo/icons/mecha_HruntingObsolete.dmi
  code/modules/halo/icons/mecha_Hruntingyggdrasilincluded.dmi
  code/modules/halo/machinery/pointbased_vendor.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL, Balancing

#3504 only valid melee has stances
  code/modules/halo/misc/melee_strikes.dm
Labels: enhancement/QOL

#3506 Bench Update
  code/modules/halo/structures/bench.dm
  code/modules/halo/structures/bench.dmi
Labels: enhancement/QOL, mapping

#3507 More Mapping Resources Update
  code/modules/halo/structures/fence.dm
  code/modules/halo/structures/fence.dmi
  code/modules/halo/structures/fountain.dm
  code/modules/halo/structures/fountain.dmi
  code/modules/halo/turfs/pavement2.dm
  code/modules/halo/turfs/pavement2.dmi
Labels: enhancement/QOL

#3509 Swamp Fauna & Outdoor Lamp
  baystation12.dme
  code/modules/halo/flora/ausflora.dm
  code/modules/halo/flora/jungle_tree.dm
  code/modules/halo/flora/jungleflora.dmi
  code/modules/halo/flora/jungletree.dmi
  code/modules/halo/flora/jungletreelarge.dmi
  code/modules/halo/flora/swamp_ausflora.dmi
  code/modules/halo/flora/swamp_ausflora_large.dmi
  code/modules/halo/icons/machinery/lamp.dm
  code/modules/halo/icons/machinery/lamp.dmi
  code/modules/halo/turfs/flooring/grass.dmi
  code/modules/halo/turfs/grass.dm
Labels: mapping

#3510 Update to Tech Floors & Jungle Tree Edit
  code/modules/halo/flora/ausflora.dm
  code/modules/halo/flora/jungle_tree.dm
  code/modules/halo/turfs/tech_floors.dm
Labels: enhancement/QOL, mapping
