Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2023-02, with the labels that each got.

#3381 Weapon balancing tweaks and a spartan buff
  code/modules/halo/clothing/spartan_armour.dm
  code/modules/halo/unsc/spartan.dm
  code/modules/halo/weapons/BR55.dm
  code/modules/halo/weapons/BR85.dm
  code/modules/halo/weapons/ammo_5mm.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/covenant/pistols.dm
  code/modules/halo/weapons/covenant/rifles.dm
  code/modules/halo/weapons/covenant/snipers.dm
Labels: enhancement/QOL, Balancing

#3382 slight tweaks to the time conc-hyper lasts in your system
  code/modules/halo/chemicals/medicine.dm
Labels: enhancement/QOL, Balancing

#3384 aegis map fix
  maps/faction_bases/oni_prowler/ONI_Prowler_Deck_1.dmm
  maps/faction_bases/oni_prowler/overmap.dm
Labels: enhancement/QOL, mapping

#3383 Adds Droppers and Nano-med Pluses to Various Faction Med-bays
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/complex046/complex046.dmm
Labels: enhancement/QOL, mapping

#3386 Adds Phantoms
  baystation12.dme
  code/modules/halo/vehicles/types/phantom.dmi
  code/modules/halo/vehicles/types/phantom_dropship.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
Labels: enhancement/QOL, feature
