Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2024-03, with the labels that each got.

#3537 Sangheili Secondary Armor Sprites
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/sangheili/sangheili_outfits.dm
Labels: enhancement/QOL, spriting, Ready

#3549 Adds Ai cameras to the second floor of Geminus city.
  maps/geminus_city/geminuscity_1.dmm
  maps/geminus_city/geminuscity_2.dmm
  maps/geminus_city/geminuscity_3.dmm
Labels: enhancement/QOL, mapping

#3550 Jiralhanae Honour Guard
  code/modules/halo/covenant/items/cards.dm
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_obj.dmi
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
Labels: spriting

#3551 Various Mapping Resources
  baystation12.dme
  code/game/turfs/flooring/flooring_decals.dm
  code/modules/halo/forerunner/sentinel_spawner.dm
  code/modules/halo/forerunner/structures_machines/data_templates.dmi
  code/modules/halo/forerunner/structures_machines/structures.dm
  icons/turf/flooring/decals.dmi
Labels: spriting
