Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2024-02, with the labels that each got.

#3528 Melee fix
  code/modules/halo/forerunner/Halo.dmi
  code/modules/halo/forerunner/Monitor.dmi
  code/modules/halo/forerunner/Sentinel.dmi
  code/modules/halo/forerunner/airlocks/door32.dmi
  code/modules/halo/forerunner/airlocks/doors.dm
  code/modules/halo/forerunner/forerunner_weapons.dmi
  code/modules/halo/forerunner/heavy_sentinel_spawner.dmi
  code/modules/halo/forerunner/knight.dm
  code/modules/halo/forerunner/knight.dmi
  code/modules/halo/forerunner/monitor.dm
  code/modules/halo/forerunner/sentinel.dm
  code/modules/halo/forerunner/sentinel_kit.dm
  code/modules/halo/forerunner/sentinel_kit.dmi
  code/modules/halo/forerunner/sentinel_spawner.dm
  code/modules/halo/forerunner/species/knight/knight.dm
  code/modules/halo/forerunner/species/knight/knight.dmi
  code/modules/halo/forerunner/species/knight/knight_armour.dm
  code/modules/halo/forerunner/species/knight/knight_armour.dmi
  code/modules/halo/forerunner/species/knight/knight_blood.dmi
  code/modules/halo/forerunner/species/knight/knight_dam.dmi
  code/modules/halo/forerunner/species/knight/knight_outfit.dm
  code/modules/halo/forerunner/species/knight/knight_template.dmi
  code/modules/halo/forerunner/watcher.dm
  code/modules/halo/forerunner/watcher.dmi
  code/modules/halo/misc/melee_strikes.dm
Labels: Bugfix

#3529 a different approach to fixing melee strikes
  code/modules/halo/misc/melee_strikes.dm
Labels: Bugfix

#3532 cool spartan stuff
  baystation12.dme
  code/modules/halo/insurrection/innie_outfits.dm
  code/modules/halo/insurrection/orion.dm
  code/modules/halo/misc/neural_lace_injectors.dm
  code/modules/halo/unsc/jobs/spartan_two.dm
  code/modules/halo/unsc/jobs/spartan_two_outfits.dm
  code/modules/halo/unsc/supply/explosives.dm
  code/modules/halo/unsc/supply/onispecial.dm
  code/modules/halo/weapons/M7.dm
  code/modules/halo/weapons/XM98.dm
  code/modules/halo/weapons/icons/Back_Weapons.dmi
  code/modules/halo/weapons/icons/Weapon Sprites.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL, Balancing, Bugfix

#3533 beam tracer fix
  code/modules/projectiles/projectile.dm
Labels: Bugfix

#3534 slight rifle tweaks from last pr
  code/modules/halo/weapons/XM98.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_left.dmi
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL

#3535 wall pen fixes
  code/modules/halo/weapons/ammo_7-62mm.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/halo/weapons/forerunner/ammo.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: enhancement/QOL, Balancing

#3531 Dropship Move Sound Effects & Swamp Tree Icon Fix
  code/modules/halo/flora/swamp_tree.dm
  code/modules/halo/sounds/vehicle_sfx/pelican_move.ogg
  code/modules/halo/sounds/vehicle_sfx/phantom_move.ogg
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/phantom_dropship.dm
Labels: enhancement/QOL, Bugfix

#3539 Kig-yar & T'vaoan Alt Jobs
  code/modules/halo/covenant/jobs/kigyar.dm
  code/modules/halo/covenant/jobs/tvoan.dm
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/species/tvoan/skirm_clothing.dmi
  code/modules/halo/covenant/species/tvoan/skirmisher_gauntlets.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_outfits.dm
Labels: enhancement/QOL

#3540 Human Covenant Gear
  code/modules/halo/clothing/human_covenant_gear.dm
  code/modules/halo/clothing/human_covenant_gear.dmi
Labels: enhancement/QOL, spriting

#3542 Updated Mjlonir Mark IV helmet sprites
  code/modules/halo/clothing/spartan_armour.dmi
Labels: enhancement/QOL, spriting

#3541 Gravity hammer balance and ODST call in fix
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
  code/modules/halo/leader_support/job_overrides.dm
  code/modules/halo/weapons/covenant/brute.dm
  code/modules/mob/mob_helpers.dm
Labels: enhancement/QOL, Balancing

#3543 fixes orion gun sprite
  code/modules/halo/sounds/silenced_double.ogg
  code/modules/halo/sounds/silenced_single.ogg
  code/modules/halo/sounds/silenced_triple.ogg
  code/modules/halo/weapons/XM98.dm
  code/modules/halo/weapons/icons/Weapon_Inhands_right.dmi
Labels: enhancement/QOL, Bugfix

#3544 LMG & Pelican Fire Sfx & Human Covenant Gear Include
  baystation12.dme
  code/modules/halo/sounds/lmg_fire.ogg
  code/modules/halo/sounds/pelican_fire.ogg
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/weapons/M739.dm
Labels: enhancement/QOL

#3545 Ups the amount of scanners that need to be destroyed to end the round
  maps/_gamemodes/invasion/gamemode.dm
Labels: Bugfix

#3546 Cargo Shadow Sprite & Jiralhanae Flag Accessory
  code/modules/halo/covenant/species/jiralhanae/clothing.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_gear.dmi
  code/modules/halo/covenant/structures_machines/covvendors.dm
  code/modules/halo/vehicles/types/shadow.dmi
Labels: enhancement/QOL, spriting

#3547 Tweaks how slowdown applies to humanmobs
  code/__defines/mobs.dm
  code/modules/halo/clothing/odst.dm
  code/modules/halo/covenant/species/tvoan/skirmisher.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/mob.dm
Labels: enhancement/QOL, Balancing
