Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2025-05, with the labels that each got.

#3607 Zealot Additions + Event Loadout
  code/modules/halo/covenant/jobs/sangheili.dm
  code/modules/halo/covenant/species/sangheili/Sangheili_Combat_Harness.dmi
  code/modules/halo/covenant/species/sangheili/clothing.dm
  code/modules/halo/covenant/species/sangheili/sangheili_outfits.dm
Labels: enhancement/QOL, spriting, Ready

#3609 URF Liberator AI Map Improvements
  maps/urf_flagship/first_deck.dmm
Labels: enhancement/QOL, mapping

#3610 Alt-Title Radio Speech Size Fix
  code/modules/mob/hear_say.dm
Labels: enhancement/QOL, Bugfix

#3612 Missing Roles Fix
  code/modules/halo/insurrection/x52_jobs.dm
  maps/_gamemodes/invasion/gamemode_revolution.dm
  maps/base_assault/base_assault.dm
  maps/base_assault_neutral_base/base_assault_neutral_base.dm
  maps/base_assault_neutral_base_taurus/base_assault_neutral_base_taurus.dm
  maps/faction_bases/faction_base_cov.dm
  maps/faction_bases/faction_base_innie.dm
  maps/geminus_city/geminus_hud_icons.dmi
  maps/geminus_city/invasion_geminus_jobdefs.dm
  maps/geminus_city_urf_active/jobdefs.dm
  maps/ks7_elmsville/hud_icons.dmi
  maps/ks7_elmsville/jobdefs.dm
  maps/system_conquest/jobs.dm
Labels: enhancement/QOL, Bugfix

#3614 disable client auth checks because byond is down /tg/ mirror
  code/modules/client/client_defines.dm
  code/modules/halo/insurrection/x52_jobs.dm
  maps/urf_flagship/includes.dm
  maps/urf_flagship/x52_spawns.dm
Labels: enhancement/QOL, Experimental

#3611 Additional Covenant Channels
  code/modules/halo/comms/channel_presets.dm
  code/modules/halo/comms/headsets.dm
  code/modules/halo/covenant/species/jiralhanae/jiralhanae_outfit.dm
  code/modules/halo/covenant/species/kigyar/kig-yar_outfits.dm
  code/modules/halo/covenant/species/sangheili/sangheili_outfits.dm
  code/modules/halo/covenant/species/sanshyuum/clothing.dm
  code/modules/halo/covenant/species/tvoan/skirmisher_outfits.dm
  code/modules/halo/covenant/species/unggoy/grunt_outfits.dm
  code/modules/halo/covenant/species/yanmee/yanmee_outfits.dm
Labels: enhancement/QOL
