Repository HaloSpaceStation/HaloSpaceStation13, pull requests merged in 2025-03, with the labels that each got.

#3574 Covenant Plasma Cannon + Ship & Sentinel Spawner Ftx
  baystation12.dme
  code/modules/halo/covenant/turfs/floors.dmi
  code/modules/halo/forerunner/sentinel_spawner.dm
  code/modules/halo/overmap/player_shuttles.dm
  code/modules/halo/overmap/req_console_ships.dm
  code/modules/halo/overmap/weapons/plasma_cannon.dm
  code/modules/halo/overmap/weapons/plasma_cannon.dmi
  code/modules/halo/overmap/weapons/plasma_cannon_2.dmi
  code/modules/halo/overmap/weapons/pulse_turret_tracers.dmi
  code/modules/halo/sounds/plasma_cannon_fire.ogg
  code/modules/halo/sounds/plasma_cannon_hit_sound.ogg
  code/modules/halo/sounds/plasma_cannon_loading.ogg
  code/modules/halo/sounds/sentinel_spawn.ogg
  maps/npc_ships/req_console_ships/cov_cannon_platform.dmm
Labels: enhancement/QOL, mapping, Ready

#3575 Sentinel Overhaul & Forerunner Faction Organization
  baystation12.dme
  code/modules/halo/forerunner/Sentinel.dmi
  code/modules/halo/forerunner/heavy_sentinel_spawner.dmi
  code/modules/halo/forerunner/items/unused.dmi
  code/modules/halo/forerunner/sentinel_spawner.dm
  code/modules/halo/forerunner/simple_mobs/monitor.dm
  code/modules/halo/forerunner/simple_mobs/monitor.dmi
  code/modules/halo/forerunner/simple_mobs/sentinel.dm
  code/modules/halo/forerunner/simple_mobs/sentinel.dmi
  code/modules/halo/forerunner/simple_mobs/sentinel_kit.dm
  code/modules/halo/forerunner/simple_mobs/sentinel_kit.dmi
  code/modules/halo/forerunner/simple_mobs/sentinel_protector.dm
  code/modules/halo/forerunner/simple_mobs/sentinel_protector.dmi
  code/modules/halo/forerunner/simple_mobs/sentinel_super.dm
  code/modules/halo/forerunner/simple_mobs/sentinel_super.dmi
  code/modules/halo/forerunner/structures_machines/heavy_sentinel_spawner.dmi
  code/modules/halo/forerunner/structures_machines/sentinel_spawner.dm
  code/modules/halo/forerunner/structures_machines/sentinel_spawner.dmi
  code/modules/halo/mobs/builder.dm
  code/modules/halo/mobs/converter.dm
  code/modules/halo/sounds/heavy_sentinel_spawn.ogg
  code/modules/halo/sounds/protector_healing_pulse.ogg
  code/modules/halo/sounds/protector_sentinel_fire.ogg
  code/modules/halo/sounds/protector_shield_pulse.ogg
Labels: enhancement/QOL, feature, spriting, Ready

#3577 Forerunner & Grass Floors
  code/game/turfs/unsimulated/grass.dm
  code/modules/halo/forerunner/turfs/floor.dm
  code/modules/halo/icons/turfs/grass.dmi
Labels: mapping, spriting

#3578 Super Sentinel Code Tweak, Large Plasma Cannon Sprite & Covvie Techfloor Sprite
  code/modules/halo/covenant/turfs/floor.dm
  code/modules/halo/forerunner/simple_mobs/sentinel_super.dm
  code/modules/halo/overmap/weapons/plasma_cannon.dm
  code/modules/halo/overmap/weapons/plasma_cannon_3.dmi
Labels: spriting, Balancing, Bugfix, Ready

#3579 Lifeworker Sprite & Minor KS7 Mapping & Misc Map Fixes
  code/modules/halo/covenant/species/huragok/huragok.dmi
  code/modules/halo/covenant/species/huragok/robot_modules.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/desert_outpost/desert_outpost2.dmm
  maps/ks7_elmsville/KS7_535_pvp_0.dmm
  maps/ks7_elmsville/KS7_535_pvp_1.dmm
  maps/ks7_elmsville/KS7_535_pvp_2.dmm
  maps/ks7_elmsville/presets_pvp_additions.dm
  maps/urf_flagship/first_deck.dmm
Labels: mapping, spriting, Bugfix, Ready

#3582 Map Tweaks, QoL Updates & Bug Fixes
  code/modules/halo/comms/telecomms_jammers.dm
  code/modules/halo/covenant/jobs/huragok.dm
  code/modules/halo/insurrection/access_ids.dm
  code/modules/halo/insurrection/soe_jobs.dm
  code/modules/halo/machinery/gunvendors.dm
  maps/CRS_Unyielding_Transgression/CRS_Unyielding_Transgression.dmm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
  maps/faction_bases/faction_base_innie.dm
  maps/faction_bases/innie_base/Innie_Base.dmm
  maps/urf_flagship/ai_items.dm
Labels: enhancement/QOL, mapping, Bugfix

#3585 Adds heavy sprite for gunvendors
  code/modules/halo/icons/machinery/gunvend.dmi
  code/modules/halo/machinery/gunvendors.dm
Labels: spriting

#3586 adds resprite for ironhammer equipment vendor
  code/modules/halo/icons/machinery/gunvend.dmi
  code/modules/halo/machinery/gunvendors.dm
Labels: enhancement/QOL, spriting

#3589 Emote Antispam
  code/modules/emotes/definitions/_mob.dm
  code/modules/emotes/definitions/audible.dm
Labels: enhancement/QOL, Bugfix

#3590 generate projectiles on request rather than storing in casing from start
  code/modules/halo/vehicles/vehiclebase_weaponry.dm
  code/modules/halo/weapons/attachments/secondary_weapon.dm
  code/modules/item_worth/Value_procs/obj/items.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/bullets.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: enhancement/QOL

#3592 Server Crash Fix #15195
  code/modules/mob/living/silicon/ai/ai.dm
Labels: priority/high, Bugfix

#3593 shifts projectile processing into its own subsystem
  baystation12.dme
  code/__defines/subsystem-priority.dm
  code/controllers/subsystems/projectiles.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL

#3595 Projectile code fixes and tweaks
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/projectiles.dm
  code/game/objects/objs.dm
  code/modules/halo/leader_support/supply_drop_variants.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL, Bugfix

#3596 nicer looking bullets
  code/modules/halo/chemicals/recipes.dm
  code/modules/halo/weapons/covenant/ammo.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL

#3597 Weapon Slowdown tweaks and turret tweaks
  code/modules/halo/weapons/M545.dm
  code/modules/halo/weapons/M739.dm
  code/modules/halo/weapons/SRS99.dm
  code/modules/halo/weapons/XM98.dm
  code/modules/halo/weapons/covenant/lmg.dm
  code/modules/halo/weapons/covenant/snipers.dm
  code/modules/halo/weapons/flamethrowers.dm
  code/modules/halo/weapons/forerunner/snipers.dm
  code/modules/halo/weapons/railrifle.dm
  code/modules/halo/weapons/turrets/HMG.dm
  code/modules/halo/weapons/turrets/ammo.dm
  code/modules/halo/weapons/turrets/chaingun.dm
  code/modules/halo/weapons/turrets/plas_turret.dm
  code/modules/halo/weapons/turrets/turret.dm
Labels: enhancement/QOL, Balancing

#3598 Vehicle tweaks
  code/__defines/misc.dm
  code/game/objects/objs.dm
  code/modules/halo/misc/atom_despawner.dm
  code/modules/halo/vehicles/__defs.dm
  code/modules/halo/vehicles/types/SOEIV.dm
  code/modules/halo/vehicles/types/banshee.dm
  code/modules/halo/vehicles/types/boarding_pod.dm
  code/modules/halo/vehicles/types/bull.dm
  code/modules/halo/vehicles/types/cobra.dm
  code/modules/halo/vehicles/types/drop_pod.dm
  code/modules/halo/vehicles/types/escape_pelican.dm
  code/modules/halo/vehicles/types/ghost.dm
  code/modules/halo/vehicles/types/goblin.dm
  code/modules/halo/vehicles/types/hrunting.dm
  code/modules/halo/vehicles/types/mongoose.dm
  code/modules/halo/vehicles/types/pelican.dm
  code/modules/halo/vehicles/types/phantom_dropship.dm
  code/modules/halo/vehicles/types/prophet_chair.dm
  code/modules/halo/vehicles/types/scorpion.dm
  code/modules/halo/vehicles/types/shadow.dm
  code/modules/halo/vehicles/types/sparrowhawk.dm
  code/modules/halo/vehicles/types/spirit_dropship.dm
  code/modules/halo/vehicles/types/warthog.dm
  code/modules/halo/vehicles/types/wraith.dm
  code/modules/halo/vehicles/vehicle_component_profiles.dm
  code/modules/halo/vehicles/vehiclebase.dm
  code/modules/projectiles/projectile.dm
Labels: enhancement/QOL, feature, Balancing

#3599 hull segment tweaks
  code/__defines/superstructure_defines.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/halo/vehicles/track_bound.dm
  code/modules/overmap/sectors.dm
  maps/faction_bases/ODP_Cassius/new_ODP_Cassius.dmm
Labels: enhancement/QOL, Balancing

#3600 minor hyperzine nerf
  code/modules/halo/chemicals/medicine.dm
Labels: enhancement/QOL, Balancing
